export type BrandTier =
  | "ultra-luxury"
  | "luxury"
  | "premium"
  | "contemporary"
  | "fast-fashion"
  | "department-stores";

export interface Brand {
  id: string;
  name: string;
  tier: BrandTier;
  origin: string;
  known: string;
  description: string;
  categories: string[];
}

export const BRANDS: Brand[] = [
  // ── Ultra Luxury ────────────────────────────────────────────────────
  {
    id: "b_lv",
    name: "Louis Vuitton",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Monogram Canvas, Trunks, RTW",
    description: "The world's most recognisable luxury house, founded 1854",
    categories: ["Bags", "Shoes", "RTW", "Accessories", "Jewellery"],
  },
  {
    id: "b_chanel",
    name: "Chanel",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "No. 5, Tweed Suits, 2.55 Bag",
    description: "Coco Chanel's timeless revolution in women's fashion",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_hermes",
    name: "Hermès",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Birkin, Kelly, Silk Scarves",
    description: "French craftmanship at its absolute pinnacle since 1837",
    categories: ["Bags", "Scarves", "Accessories", "Equestrian", "Home"],
  },
  {
    id: "b_dior",
    name: "Christian Dior",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "New Look, Lady Dior, Saddle Bag",
    description: "Parisian couture defining the feminine silhouette since 1947",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_balmain",
    name: "Balmain",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Structured Blazers, Gold Buttons, Power Dressing",
    description: "French power dressing at its most theatrical and bold",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_givenchy",
    name: "Givenchy",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Antigona Bag, 4G Logo",
    description: "Audrey Hepburn's favourite house, elegant and architectural",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_valentino",
    name: "Valentino",
    tier: "ultra-luxury",
    origin: "Rome, Italy",
    known: "Valentino Red, Rockstud",
    description: "Roman romance meets maximal elegance in every stitch",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_versace",
    name: "Versace",
    tier: "ultra-luxury",
    origin: "Milan, Italy",
    known: "Medusa, Baroque Prints, Safety Pin Dress",
    description: "Italian maximalism — bold, sensual, unapologetically opulent",
    categories: ["RTW", "Bags", "Shoes", "Jewellery"],
  },
  {
    id: "b_prada",
    name: "Prada",
    tier: "ultra-luxury",
    origin: "Milan, Italy",
    known: "Re-Nylon, Saffiano Leather, Triangle Logo",
    description: "Intellectual Italian luxury — cerebral, avant-garde, covetable",
    categories: ["Bags", "Shoes", "RTW", "Accessories"],
  },
  {
    id: "b_gucci",
    name: "Gucci",
    tier: "ultra-luxury",
    origin: "Florence, Italy",
    known: "GG Canvas, Bamboo Bag, Horsebit Loafer",
    description: "Florentine heritage remixed with Maximalist exuberance",
    categories: ["Bags", "Shoes", "RTW", "Accessories", "Jewellery"],
  },
  {
    id: "b_fendi",
    name: "Fendi",
    tier: "ultra-luxury",
    origin: "Rome, Italy",
    known: "Baguette Bag, Fur, Zucca Print",
    description: "Roman fur house turned global luxury powerhouse",
    categories: ["Bags", "Shoes", "RTW", "Furs", "Accessories"],
  },
  {
    id: "b_celine",
    name: "Celine",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Luggage Tote, Triomphe",
    description: "Parisian minimalism refined to its most powerful form",
    categories: ["Bags", "Shoes", "RTW", "Accessories"],
  },
  {
    id: "b_ysl",
    name: "Saint Laurent",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Le Smoking, Loulou Bag, Rock Edge",
    description: "YSL's rock-and-roll couture legacy, forever cool",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_bv",
    name: "Bottega Veneta",
    tier: "ultra-luxury",
    origin: "Vicenza, Italy",
    known: "Intrecciato Weave, Cassette Bag",
    description: "When your initials are enough — the art of quiet luxury",
    categories: ["Bags", "Shoes", "RTW", "Accessories"],
  },
  {
    id: "b_loewe",
    name: "Loewe",
    tier: "ultra-luxury",
    origin: "Madrid, Spain",
    known: "Puzzle Bag, Elephant Bag, Craft",
    description: "Spanish leather craft elevated to conceptual art",
    categories: ["Bags", "Shoes", "RTW", "Accessories"],
  },
  {
    id: "b_burberry",
    name: "Burberry",
    tier: "ultra-luxury",
    origin: "London, UK",
    known: "Nova Check, Trench Coat",
    description: "British heritage outerwear with a modern luxury edge",
    categories: ["Outerwear", "Bags", "RTW", "Accessories", "Shoes"],
  },
  {
    id: "b_mcqueen",
    name: "Alexander McQueen",
    tier: "ultra-luxury",
    origin: "London, UK",
    known: "Skull Scarf, Savage Beauty",
    description: "Dark romanticism — fashion as art, art as provocation",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_moncler",
    name: "Moncler",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Down Jackets, Grenoble",
    description: "Alpine luxury — performance outerwear for the jet set",
    categories: ["Outerwear", "RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_tomford",
    name: "Tom Ford",
    tier: "ultra-luxury",
    origin: "New York, USA",
    known: "Sensuality, Suiting, Beauty",
    description: "Hollywood-meets-Italian craftsmanship — pure seduction",
    categories: ["RTW", "Bags", "Shoes", "Beauty", "Eyewear"],
  },
  {
    id: "b_thombrowne",
    name: "Thom Browne",
    tier: "ultra-luxury",
    origin: "New York, USA",
    known: "Grey Suit, Grosgrain Stripe",
    description: "Reimagined Americana — tailoring as conceptual theatre",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_brunello",
    name: "Brunello Cucinelli",
    tier: "ultra-luxury",
    origin: "Solomeo, Italy",
    known: "Cashmere, Humanistic Capitalism",
    description: "The ultimate expression of quiet Italian luxury in cashmere",
    categories: ["RTW", "Knitwear", "Outerwear", "Accessories"],
  },
  {
    id: "b_loro",
    name: "Loro Piana",
    tier: "ultra-luxury",
    origin: "Quarona, Italy",
    known: "Vicuña, Baby Cashmere",
    description: "The rarest fibres, the most understated luxury on earth",
    categories: ["RTW", "Knitwear", "Accessories", "Home"],
  },
  {
    id: "b_zegna",
    name: "Zegna",
    tier: "ultra-luxury",
    origin: "Trivero, Italy",
    known: "Oasi Cashmere, Triple Stitch",
    description: "Italian menswear at the pinnacle — fabric to finish",
    categories: ["Menswear", "RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_dolce",
    name: "Dolce & Gabbana",
    tier: "ultra-luxury",
    origin: "Milan, Italy",
    known: "Sicily Bag, Baroque, Corset Dresses",
    description: "Southern Italian passion and maximalist sensuality",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_armani",
    name: "Giorgio Armani",
    tier: "ultra-luxury",
    origin: "Milan, Italy",
    known: "Power Suiting, Earth Tones",
    description: "The master of understated Italian elegance since 1975",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_vivienne",
    name: "Vivienne Westwood",
    tier: "ultra-luxury",
    origin: "London, UK",
    known: "Orb Logo, Punk Couture",
    description: "The grandmother of British punk made into high fashion",
    categories: ["RTW", "Jewellery", "Bags", "Shoes"],
  },
  {
    id: "b_marni",
    name: "Marni",
    tier: "ultra-luxury",
    origin: "Milan, Italy",
    known: "Colourful Geometry, Trunkaroo",
    description: "Artful eccentricity — colour, pattern, and joyful chaos",
    categories: ["RTW", "Bags", "Shoes", "Jewellery"],
  },
  {
    id: "b_maison_margiela",
    name: "Maison Margiela",
    tier: "ultra-luxury",
    origin: "Paris, France",
    known: "Tabi Boot, Deconstruction",
    description: "Fashion's most cerebral provocateur — deconstructed luxury",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },

  // ── Luxury / Designer ──────────────────────────────────────────────
  {
    id: "b_rick",
    name: "Rick Owens",
    tier: "luxury",
    origin: "Los Angeles, USA",
    known: "Drkshw, DRKSHDW, Brutalism",
    description: "Dark architectural womenswear and menswear from LA's outsider king",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_offwhite",
    name: "Off-White",
    tier: "luxury",
    origin: "Milan, Italy",
    known: "Quotation Marks, Arrows, Virgil Abloh",
    description: "Virgil Abloh's streetwear-luxury bridge that changed everything",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_balenciaga",
    name: "Balenciaga",
    tier: "luxury",
    origin: "Paris, France",
    known: "Triple S, Speed Trainer, Oversized Silhouettes",
    description: "Demna's subversive couture — high fashion with a street soul",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_jacquemus",
    name: "Jacquemus",
    tier: "luxury",
    origin: "Paris, France",
    known: "Le Chiquito, Micro Bags, Provence",
    description: "Sunny Provençal minimalism — joy in every oversized hat",
    categories: ["RTW", "Bags", "Accessories", "Shoes"],
  },
  {
    id: "b_acne",
    name: "Acne Studios",
    tier: "luxury",
    origin: "Stockholm, Sweden",
    known: "Face Patch, Scandi Cool, Denim",
    description: "Swedish cool kid — the intersection of art, culture, fashion",
    categories: ["RTW", "Denim", "Shoes", "Accessories"],
  },
  {
    id: "b_therow",
    name: "The Row",
    tier: "luxury",
    origin: "New York, USA",
    known: "Quiet Luxury, Cashmere, Perfection",
    description: "Mary-Kate and Ashley Olsen's ode to flawless, silent luxury",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_toteme",
    name: "Toteme",
    tier: "luxury",
    origin: "Stockholm, Sweden",
    known: "Scarf Coat, Clean Lines, Wardrobe Essentials",
    description: "The Swedish brand defining the minimal luxury wardrobe",
    categories: ["RTW", "Accessories", "Bags"],
  },
  {
    id: "b_amiri",
    name: "Amiri",
    tier: "luxury",
    origin: "Los Angeles, USA",
    known: "Destroyed Denim, Rock Star Luxe",
    description: "Hollywood rock star luxury — distressed premium denim and leather",
    categories: ["RTW", "Denim", "Shoes", "Accessories"],
  },
  {
    id: "b_palm",
    name: "Palm Angels",
    tier: "luxury",
    origin: "Milan, Italy",
    known: "Palm Tree Print, Ski Jacket",
    description: "LA skate culture filtered through Italian luxury craftsmanship",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_fear",
    name: "Fear of God",
    tier: "luxury",
    origin: "Los Angeles, USA",
    known: "Essentials, Fog, Jerry Lorenzo",
    description: "Jerry Lorenzo's luxe-casual revolution in American sportswear",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_stone",
    name: "Stone Island",
    tier: "luxury",
    origin: "Ravarino, Italy",
    known: "Compass Badge, Dyeing, Techwear",
    description: "Italian research-led outerwear beloved by fashion insiders",
    categories: ["Outerwear", "RTW", "Accessories"],
  },
  {
    id: "b_maxmara",
    name: "Max Mara",
    tier: "luxury",
    origin: "Reggio Emilia, Italy",
    known: "The Coat, 101801 Coat",
    description: "The definitive Italian coat — cashmere perfection since 1951",
    categories: ["Outerwear", "RTW", "Accessories"],
  },
  {
    id: "b_isabel",
    name: "Isabel Marant",
    tier: "luxury",
    origin: "Paris, France",
    known: "Étoile Line, Boho-Luxe, Wedge Sneaker",
    description: "Effortless Parisian boho luxury with a rock edge",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_stella",
    name: "Stella McCartney",
    tier: "luxury",
    origin: "London, UK",
    known: "Falabella Bag, Sustainability",
    description: "Luxury without compromise — vegan, sustainable, powerful",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_jilsander",
    name: "Jil Sander",
    tier: "luxury",
    origin: "Hamburg, Germany",
    known: "Radical Minimalism, Pure Silhouettes",
    description: "The Queen of Less — precision minimalism at the highest level",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_acronym",
    name: "Acronym",
    tier: "luxury",
    origin: "Munich, Germany",
    known: "GORE-TEX, Technical Garments",
    description: "The cult techwear label that makes Gore-Tex a luxury object",
    categories: ["Outerwear", "RTW", "Accessories"],
  },
  {
    id: "b_apc",
    name: "A.P.C.",
    tier: "luxury",
    origin: "Paris, France",
    known: "Raw Denim, French Basics",
    description: "Understated French basics that age beautifully",
    categories: ["RTW", "Denim", "Bags", "Accessories"],
  },
  {
    id: "b_moschino",
    name: "Moschino",
    tier: "luxury",
    origin: "Milan, Italy",
    known: "Irony, Pop Culture, Capsule Collections",
    description: "Fashion's great satirist — luxury with a wink and a laugh",
    categories: ["RTW", "Bags", "Accessories", "Shoes"],
  },

  // ── Premium / Contemporary ─────────────────────────────────────────
  {
    id: "b_ralph",
    name: "Ralph Lauren",
    tier: "premium",
    origin: "New York, USA",
    known: "Polo, Purple Label, American Dream",
    description: "The quintessential American lifestyle brand across all tiers",
    categories: ["RTW", "Shoes", "Bags", "Accessories", "Home"],
  },
  {
    id: "b_coach",
    name: "Coach",
    tier: "premium",
    origin: "New York, USA",
    known: "Tabby Bag, American Leather Craft",
    description: "New York leather craft — approachable American luxury",
    categories: ["Bags", "Shoes", "Accessories", "RTW"],
  },
  {
    id: "b_michaelkors",
    name: "Michael Kors",
    tier: "premium",
    origin: "New York, USA",
    known: "Jet Set, Mercer Bag",
    description: "Accessible luxury for the globally-minded modern woman",
    categories: ["Bags", "Shoes", "RTW", "Accessories", "Watches"],
  },
  {
    id: "b_tory",
    name: "Tory Burch",
    tier: "premium",
    origin: "New York, USA",
    known: "Miller Sandal, Reva Ballet Flat, TB Logo",
    description: "Prep-meets-boho American sportswear with global appeal",
    categories: ["Bags", "Shoes", "RTW", "Accessories"],
  },
  {
    id: "b_kors_versace",
    name: "Versace Jeans Couture",
    tier: "premium",
    origin: "Milan, Italy",
    known: "Baroque, Medusa Accessories, Accessible Versace",
    description: "The accessible arm of Versace — bold without the couture price",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_hugo",
    name: "Hugo Boss",
    tier: "premium",
    origin: "Metzingen, Germany",
    known: "Suiting, Hugo Line, Business Casual",
    description: "German precision suiting for the modern professional",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_ted",
    name: "Ted Baker",
    tier: "premium",
    origin: "London, UK",
    known: "Floral Prints, British Eccentricity",
    description: "Quirky British style with impeccable finish",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_reiss",
    name: "Reiss",
    tier: "premium",
    origin: "London, UK",
    known: "Clean Tailoring, Modern British",
    description: "Sharp British tailoring at an accessible premium price point",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_sandro",
    name: "Sandro",
    tier: "premium",
    origin: "Paris, France",
    known: "Parisian Chic, SMCP Group",
    description: "Effortlessly chic Parisian ready-to-wear",
    categories: ["RTW", "Bags", "Shoes", "Accessories"],
  },
  {
    id: "b_maje",
    name: "Maje",
    tier: "premium",
    origin: "Paris, France",
    known: "French Girl Style, SMCP Group",
    description: "Parisian femininity — flirtatious, modern, wearable",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_bcbg",
    name: "BCBG Max Azria",
    tier: "premium",
    origin: "Los Angeles, USA",
    known: "Evening Wear, Accessible Glamour",
    description: "Refined Parisian-influenced American glamour",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_rag",
    name: "Rag & Bone",
    tier: "premium",
    origin: "New York, USA",
    known: "Moto Boots, British-Inspired, Denim",
    description: "British workwear heritage refined for the modern New Yorker",
    categories: ["RTW", "Shoes", "Bags", "Accessories", "Denim"],
  },
  {
    id: "b_vince",
    name: "Vince",
    tier: "premium",
    origin: "Los Angeles, USA",
    known: "Cashmere Basics, California Minimal",
    description: "West Coast luxury basics — effortless, soft, elevated",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_ba_sh",
    name: "Ba&sh",
    tier: "premium",
    origin: "Paris, France",
    known: "Feminine French Boho",
    description: "Light, romantic French femininity for every occasion",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_equipment",
    name: "Equipment",
    tier: "premium",
    origin: "Paris, France",
    known: "Signature Silk Blouses, French-American",
    description: "The definitive silk blouse — French-designed, globally adored",
    categories: ["RTW", "Accessories"],
  },
  {
    id: "b_reformation",
    name: "Reformation",
    tier: "premium",
    origin: "Los Angeles, USA",
    known: "Sustainable Fashion, Slip Dresses, #RefScale",
    description: "Sustainable luxury for the modern woman who has a conscience",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_agolde",
    name: "Agolde",
    tier: "premium",
    origin: "Los Angeles, USA",
    known: "90s Pinch Waist, Raw Hem Denim",
    description: "The premium denim brand defining the Y2K revival",
    categories: ["Denim", "RTW"],
  },
  {
    id: "b_allsaints",
    name: "AllSaints",
    tier: "premium",
    origin: "London, UK",
    known: "Leather Jackets, Rock Edge, Biker",
    description: "British rock-inspired leather and knitwear for the bold",
    categories: ["RTW", "Outerwear", "Shoes", "Accessories"],
  },
  {
    id: "b_ganni",
    name: "Ganni",
    tier: "premium",
    origin: "Copenhagen, Denmark",
    known: "Smocked Dresses, Checkerboard, Scandi Fun",
    description: "Copenhagen's most-wanted brand — fun, Scandinavian, responsible",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_dries",
    name: "Dries Van Noten",
    tier: "premium",
    origin: "Antwerp, Belgium",
    known: "Prints, Colour, Antwerp Six",
    description: "Belgian artistry — rich prints and global textile heritage",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_lacoste",
    name: "Lacoste",
    tier: "premium",
    origin: "Paris, France",
    known: "Petit Piqué Polo, Crocodile Logo",
    description: "The original premium polo — sport, style, and the crocodile",
    categories: ["RTW", "Shoes", "Accessories", "Bags"],
  },
  {
    id: "b_theory",
    name: "Theory",
    tier: "premium",
    origin: "New York, USA",
    known: "Clean Business Casual, Precision Cuts",
    description: "Minimalist American precision suiting for city professionals",
    categories: ["RTW", "Accessories"],
  },
  {
    id: "b_cos",
    name: "COS",
    tier: "premium",
    origin: "London, UK",
    known: "Architectural Minimal, H&M Group Premium",
    description: "Architecture-inspired fashion — clean, thoughtful, enduring",
    categories: ["RTW", "Shoes", "Accessories", "Home"],
  },

  // ── Contemporary / Mid-Market ──────────────────────────────────────
  {
    id: "b_zara",
    name: "Zara",
    tier: "contemporary",
    origin: "Arteixo, Spain",
    known: "Fast Runway, Inditex, Trend Cycle",
    description: "The world's most powerful high street chain — runway to rail in 2 weeks",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_hm",
    name: "H&M",
    tier: "contemporary",
    origin: "Stockholm, Sweden",
    known: "Designer Collabs, Affordable Fashion",
    description: "Global fashion democracy — designer collaborations for all",
    categories: ["RTW", "Shoes", "Bags", "Accessories", "Home"],
  },
  {
    id: "b_mango",
    name: "Mango",
    tier: "contemporary",
    origin: "Barcelona, Spain",
    known: "Mediterranean Style, Affordable Chic",
    description: "Spanish style confidence at accessible prices",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_massimo",
    name: "Massimo Dutti",
    tier: "contemporary",
    origin: "Arteixo, Spain",
    known: "Smart Casual, Inditex Premium",
    description: "Inditex's quality play — smart, classic, and elegant",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_uniqlo",
    name: "Uniqlo",
    tier: "contemporary",
    origin: "Yamaguchi, Japan",
    known: "Heattech, LifeWear, Essentials",
    description: "Japanese LifeWear philosophy — the ultimate functional basics",
    categories: ["RTW", "Accessories", "Innerwear"],
  },
  {
    id: "b_asos",
    name: "ASOS",
    tier: "contemporary",
    origin: "London, UK",
    known: "800+ Brands, Inclusive Sizing, Online",
    description: "The world's leading online fashion destination — everything, for everyone",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_anthropologie",
    name: "Anthropologie",
    tier: "contemporary",
    origin: "Philadelphia, USA",
    known: "Boho Aesthetic, Print Dresses, Lifestyle",
    description: "Artisan-inspired bohemian lifestyle brand for the free spirit",
    categories: ["RTW", "Shoes", "Accessories", "Home"],
  },
  {
    id: "b_fp",
    name: "Free People",
    tier: "contemporary",
    origin: "Philadelphia, USA",
    known: "Boho, Festival Style, Movement",
    description: "Bohemian activewear and lifestyle brand for the wandering spirit",
    categories: ["RTW", "Activewear", "Shoes", "Accessories"],
  },
  {
    id: "b_jcrew",
    name: "J.Crew",
    tier: "contemporary",
    origin: "New York, USA",
    known: "Preppy American, Collaboration, Classic",
    description: "Preppy American classics reimagined for the modern wardrobe",
    categories: ["RTW", "Shoes", "Accessories", "Bags"],
  },
  {
    id: "b_banana",
    name: "Banana Republic",
    tier: "contemporary",
    origin: "San Francisco, USA",
    known: "Elevated Basics, Work Wear",
    description: "Gap's elevated sibling — sophisticated work and weekend wear",
    categories: ["RTW", "Shoes", "Accessories", "Bags"],
  },
  {
    id: "b_clubmonaco",
    name: "Club Monaco",
    tier: "contemporary",
    origin: "Toronto, Canada",
    known: "Modern Classic, Tailored Minimalism",
    description: "Refined minimalism for the modern urban professional",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_topshop",
    name: "Topshop",
    tier: "contemporary",
    origin: "London, UK",
    known: "Joni Jeans, British High Street, Celebrity Collabs",
    description: "The iconic British high street brand now online via ASOS",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_french",
    name: "French Connection",
    tier: "contemporary",
    origin: "London, UK",
    known: "FCUK, Contemporary British",
    description: "British contemporary fashion with a cheeky confidence",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_express",
    name: "Express",
    tier: "contemporary",
    origin: "Columbus, USA",
    known: "Work to Weekend, American Casual",
    description: "American express dressing — polished looks from desk to drinks",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_lulus",
    name: "Lulus",
    tier: "contemporary",
    origin: "Chico, USA",
    known: "Occasion Dresses, Bridesmaid, Affordable Formal",
    description: "The go-to for affordable occasion dressing and bridesmaids",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_revolve",
    name: "Revolve",
    tier: "contemporary",
    origin: "Cerritos, USA",
    known: "Influencer Brand, Festival, Resort",
    description: "The influencer-beloved platform curating the festival-to-resort look",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_princess",
    name: "Princess Polly",
    tier: "contemporary",
    origin: "Gold Coast, Australia",
    known: "Gen Z Aesthetic, Australian, TikTok",
    description: "Australia's Gen Z darling — TikTok viral trends made affordable",
    categories: ["RTW", "Shoes", "Accessories"],
  },

  // ── Fast Fashion ───────────────────────────────────────────────────
  {
    id: "b_shein",
    name: "SHEIN",
    tier: "fast-fashion",
    origin: "Nanjing, China",
    known: "Ultra-Fast Fashion, Thousands of SKUs Daily",
    description: "The world's largest fast fashion platform — trends at warp speed",
    categories: ["RTW", "Shoes", "Bags", "Accessories", "Beauty"],
  },
  {
    id: "b_fashionnova",
    name: "Fashion Nova",
    tier: "fast-fashion",
    origin: "Los Angeles, USA",
    known: "Celebrity Collabs, Curve, Instagram Fashion",
    description: "LA's Instagram-born fast fashion king — body-positive and bold",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_plt",
    name: "PrettyLittleThing",
    tier: "fast-fashion",
    origin: "Manchester, UK",
    known: "Boohoo Group, Party Wear, Inclusive Sizing",
    description: "UK fast fashion giant — party looks at unbeatable prices",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_boohoo",
    name: "Boohoo",
    tier: "fast-fashion",
    origin: "Manchester, UK",
    known: "Boohoo Group, Affordable UK Fashion",
    description: "Manchester-born fast fashion powerhouse for the budget-conscious",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_nastygal",
    name: "Nasty Gal",
    tier: "fast-fashion",
    origin: "Los Angeles, USA",
    known: "Sophia Amoruso, Rock Chick, #GIRLBOSS",
    description: "The original bad-girl fashion brand — rock, punk, and unapologetic",
    categories: ["RTW", "Shoes", "Bags", "Accessories"],
  },
  {
    id: "b_micas",
    name: "Micas",
    tier: "fast-fashion",
    origin: "Los Angeles, USA",
    known: "Trend-Led Dresses, Going-Out Sets, Affordable",
    description: "Trend-driven women's fashion — going-out looks and dresses at accessible prices",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_forever21",
    name: "Forever 21",
    tier: "fast-fashion",
    origin: "Los Angeles, USA",
    known: "Mall Staple, Y2K Aesthetic, Budget",
    description: "The American mall icon — on-trend basics at extreme value",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_iamgia",
    name: "I.AM.GIA",
    tier: "fast-fashion",
    origin: "Sydney, Australia",
    known: "Cobain Pant, Matrix Aesthetic, Model Off-Duty",
    description: "Sydney's Instagram-born brand — the model off-duty essentials",
    categories: ["RTW", "Accessories"],
  },
  {
    id: "b_romwe",
    name: "ROMWE",
    tier: "fast-fashion",
    origin: "Nanjing, China",
    known: "SHEIN Sister Brand, Ultra Cheap",
    description: "SHEIN's fashion-forward sister brand — maximalist looks for less",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_cider",
    name: "Cider",
    tier: "fast-fashion",
    origin: "Hong Kong, China",
    known: "TikTok Fashion, Gen Z, Y2K and Cottagecore",
    description: "Gen Z's TikTok-driven micro-trend specialist",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_newlook",
    name: "New Look",
    tier: "fast-fashion",
    origin: "London, UK",
    known: "British High Street, Value",
    description: "British high street staple — fashion-forward at everyday prices",
    categories: ["RTW", "Shoes", "Accessories"],
  },
  {
    id: "b_missguided",
    name: "Missguided",
    tier: "fast-fashion",
    origin: "Manchester, UK",
    known: "Club Wear, Bold, UK Fast Fashion",
    description: "UK fast fashion for the fearlessly dressed night-out queen",
    categories: ["RTW", "Shoes", "Accessories"],
  },

  // ── Department Stores ───────────────────────────────────────────────
  {
    id: "b_saks",
    name: "Saks Fifth Avenue",
    tier: "department-stores",
    origin: "New York, USA",
    known: "Designer Floors, 10022-SHOE, Personal Shopping",
    description: "The Fifth Avenue flagship of American luxury retail since 1924",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_neiman",
    name: "Neiman Marcus",
    tier: "department-stores",
    origin: "Dallas, USA",
    known: "Fantasy Gifts, Couture Salons, NM Awards",
    description: "Texas-born temple of couture and the American luxury fantasy",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_bergdorf",
    name: "Bergdorf Goodman",
    tier: "department-stores",
    origin: "New York, USA",
    known: "5th Ave Windows, Designer Salons, BG Restaurant",
    description: "Manhattan's most rarefied address for fashion at 58th & Fifth",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_nordstrom",
    name: "Nordstrom",
    tier: "department-stores",
    origin: "Seattle, USA",
    known: "Legendary Service, Designer + Contemporary Mix, Anniversary Sale",
    description: "The service-first American icon spanning designer to everyday",
    categories: ["RTW", "Bags", "Shoes", "Accessories", "Beauty"],
  },
  {
    id: "b_bloomingdales",
    name: "Bloomingdale's",
    tier: "department-stores",
    origin: "New York, USA",
    known: "Little Brown Bag, 59th Street Flagship",
    description: "New York's beloved big brown bag of designer discovery",
    categories: ["RTW", "Bags", "Shoes", "Accessories", "Beauty"],
  },
  {
    id: "b_macys",
    name: "Macy's",
    tier: "department-stores",
    origin: "New York, USA",
    known: "Herald Square, Thanksgiving Parade, Accessible Designer",
    description: "The Herald Square institution bringing fashion to everyone",
    categories: ["RTW", "Bags", "Shoes", "Accessories", "Beauty"],
  },
  {
    id: "b_harrods",
    name: "Harrods",
    tier: "department-stores",
    origin: "London, UK",
    known: "Knightsbridge, Food Halls, Superbrands Floor",
    description: "Knightsbridge's gilded landmark of world luxury retail",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_selfridges",
    name: "Selfridges",
    tier: "department-stores",
    origin: "London, UK",
    known: "Oxford Street, Corner Shop, The Wonder Room",
    description: "Oxford Street's theatre of retail and creative luxury",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_harveynichols",
    name: "Harvey Nichols",
    tier: "department-stores",
    origin: "London, UK",
    known: "Knightsbridge Fashion Floors, Fifth Floor Bar",
    description: "London's sharply curated edit of directional designer fashion",
    categories: ["RTW", "Bags", "Shoes", "Beauty"],
  },
  {
    id: "b_galerieslafayette",
    name: "Galeries Lafayette",
    tier: "department-stores",
    origin: "Paris, France",
    known: "Art Nouveau Dome, Boulevard Haussmann",
    description: "Paris's glass-domed grand magasin of French fashion",
    categories: ["RTW", "Bags", "Shoes", "Jewellery", "Beauty"],
  },
  {
    id: "b_bonmarche",
    name: "Le Bon Marché",
    tier: "department-stores",
    origin: "Paris, France",
    known: "Rive Gauche, LVMH Curation, La Grande Épicerie",
    description: "The Left Bank's original department store, curated by LVMH",
    categories: ["RTW", "Bags", "Shoes", "Beauty"],
  },
  {
    id: "b_holtrenfrew",
    name: "Holt Renfrew",
    tier: "department-stores",
    origin: "Toronto, Canada",
    known: "Bloor Street, Designer Boutiques, Holts Concierge",
    description: "Canada's home of designer luxury since 1837",
    categories: ["RTW", "Bags", "Shoes", "Beauty"],
  },
];

export const BRAND_TIERS: { id: BrandTier; label: string; description: string }[] = [
  {
    id: "ultra-luxury",
    label: "Ultra Luxury",
    description: "Chanel, Hermès, Louis Vuitton & the world's great houses",
  },
  {
    id: "luxury",
    label: "Luxury",
    description: "Balenciaga, Off-White, The Row & cult designer labels",
  },
  {
    id: "premium",
    label: "Premium",
    description: "Ralph Lauren, COS, Ganni & elevated contemporary brands",
  },
  {
    id: "contemporary",
    label: "Contemporary",
    description: "Zara, ASOS, Revolve & the modern high street",
  },
  {
    id: "fast-fashion",
    label: "Fast Fashion",
    description: "SHEIN, Fashion Nova, PLT & the ultra-accessible market",
  },
  {
    id: "department-stores",
    label: "Department Stores",
    description: "Saks, Neiman Marcus, Nordstrom, Harrods & the great fashion houses' homes",
  },
];

export function getBrandsByTier(tier: BrandTier): Brand[] {
  return BRANDS.filter((b) => b.tier === tier);
}

export function getBrandById(id: string): Brand | undefined {
  return BRANDS.find((b) => b.id === id);
}
