// Local celebrity photos (bundled assets)
const PHOTOS = {
  drake:       require("../assets/images/celebrities/drake.jpeg"),
  rihanna:     require("../assets/images/celebrities/rihanna.jpeg"),
  kanye:       require("../assets/images/celebrities/kanye.jpeg"),
  travis:      require("../assets/images/celebrities/travis_scott.jpeg"),
  fabolous:    require("../assets/images/celebrities/fabolous.jpeg"),
  denzel:      require("../assets/images/celebrities/denzel.jpeg"),
  snoop:       require("../assets/images/celebrities/snoop.jpeg"),
  jeezy:       require("../assets/images/celebrities/jeezy.jpg"),
  zendaya:     require("../assets/images/celebrities/zendaya.jpeg"),
  harry:       require("../assets/images/celebrities/harry_styles.jpeg"),
  pharrell:    require("../assets/images/celebrities/pharrell.jpeg"),
  audrey:      require("../assets/images/celebrities/audrey.webp"),
  marilyn:     require("../assets/images/celebrities/marilyn_monroe.jpeg"),
  ladygaga:    require("../assets/images/celebrities/lady_gaga.webp"),
  chloe:       require("../assets/images/celebrities/chloe_zhao.webp"),
  asap:        require("../assets/images/celebrities/asap_rocky.webp"),
  lewis:       require("../assets/images/celebrities/lewis_hamilton.webp"),
  sga:         require("../assets/images/celebrities/sga.webp"),
  nas:         require("../assets/images/celebrities/nas.jpg"),
  kim:         require("../assets/images/celebrities/kim_kardashian.jpeg"),
  maryjblige:  require("../assets/images/celebrities/mary_j_blige.png"),
  taylor:      require("../assets/images/celebrities/taylor_swift.jpeg"),
  cardiB:      require("../assets/images/celebrities/cardi_b.jpg"),
  kateHudson:  require("../assets/images/celebrities/kate_hudson.jpg"),
  kekePalmer:  require("../assets/images/celebrities/keke_palmer.jpg"),
  katyPerry:   require("../assets/images/celebrities/katy_perry.jpg"),
  kylieJenner: require("../assets/images/celebrities/kylie_jenner.jpg"),
  dakotaJohnson: require("../assets/images/celebrities/dakota_johnson.jpg"),
  milaKunis:   require("../assets/images/celebrities/mila_kunis.jpg"),
  demiMoore:   require("../assets/images/celebrities/demi_moore.jpg"),
  sza:         require("../assets/images/celebrities/sza.jpg"),
  heidiKlum:   require("../assets/images/celebrities/heidi_klum.jpg"),
  savannahJames: require("../assets/images/celebrities/savannah_james.jpg"),
  loriHarvey:  require("../assets/images/celebrities/lori_harvey.jpg"),
  future:      require("../assets/images/celebrities/future.jpg"),
  michaelBJordan: require("../assets/images/celebrities/michael_b_jordan.jpg"),
};

export interface CelebLook {
  name: string;
  pieces: { item: string; brand: string }[];
}

export interface CelebFull {
  id: string;
  name: string;
  title: string;
  style: string;
  description: string;
  image: any;
  accentColor: string;
  era: string;
  knownFor: string;
  signatureBrands: string[];
  keyPieces: string[];
  vibes: string[];
  looks: CelebLook[];
}

export const CELEBS: CelebFull[] = [
  {
    id: "drake",
    name: "Drake",
    title: "The Rap God of Quiet Luxury",
    style: "Toronto Luxe",
    description: "OVO aesthetic — understated logos, $10k outerwear in neutral tones, NBA courtside ready. Drake elevated the 'I don't have to try' school of luxury streetwear.",
    image: PHOTOS.drake,
    accentColor: "#C6A75E",
    era: "2010s–Present",
    knownFor: "OVO, Nocta, Hermès, courtside fits",
    signatureBrands: ["OVO", "Hermès", "Nike / Nocta", "Louis Vuitton", "Canada Goose"],
    keyPieces: ["Hermès belt", "Nike Air Monarch (ironic)", "Owl logo hoodie", "Stone Island down coat", "Rolex Patek Philippe"],
    vibes: ["Quiet Luxury", "Luxury Streetwear", "Old Money"],
    looks: [
      { name: "Courtside God", pieces: [{ item: "OVO Owl Hoodie", brand: "OVO" }, { item: "Slim Track Pant", brand: "Hermès" }, { item: "Air Max 90", brand: "Nike" }] },
      { name: "Champagne Papi", pieces: [{ item: "Camel Overcoat", brand: "Canada Goose" }, { item: "Cashmere Roll-neck", brand: "Brunello Cucinelli" }, { item: "Suede Chelsea Boot", brand: "Bottega Veneta" }] },
      { name: "OVO Tour", pieces: [{ item: "Stadium Tour Hoodie", brand: "OVO" }, { item: "Nike Track Pant", brand: "Nike" }, { item: "Air Jordan 4", brand: "Nike" }] },
      { name: "Toronto Winter", pieces: [{ item: "Down Parka", brand: "Stone Island" }, { item: "Cashmere Turtleneck", brand: "Hermès" }, { item: "6-Inch Boot", brand: "Timberland" }] },
      { name: "Certified Lover", pieces: [{ item: "Velvet DB Suit", brand: "Tom Ford" }, { item: "Satin Shirt", brand: "Brioni" }, { item: "Patent Loafer", brand: "Gucci" }] },
      { name: "Nocta Run", pieces: [{ item: "Fleece Track Jacket", brand: "Nike Nocta" }, { item: "Compression Tight", brand: "Nike Nocta" }, { item: "Air Max Scorpion", brand: "Nike" }] },
      { name: "Hermès Heavy", pieces: [{ item: "Cashmere Hoodie", brand: "Hermès" }, { item: "Slim Trouser", brand: "Hermès" }, { item: "Oran Sandal", brand: "Hermès" }] },
      { name: "Golden Hours", pieces: [{ item: "Linen Blazer", brand: "Loro Piana" }, { item: "White Oxford Shirt", brand: "Charvet" }, { item: "Driving Shoe", brand: "Berluti" }] },
      { name: "Club Ritz", pieces: [{ item: "Custom Bomber", brand: "1 of 1" }, { item: "Skinny Denim", brand: "Amiri" }, { item: "Jordan 1 Retro", brand: "Nike" }] },
      { name: "Yacht Diaries", pieces: [{ item: "Swim Short", brand: "Vilebrequin" }, { item: "Linen Camp Shirt", brand: "Loro Piana" }, { item: "Canvas Sneaker", brand: "Rivieras" }] },
      { name: "Grammy Night", pieces: [{ item: "Fur-Trim Tuxedo", brand: "Rick Owens" }, { item: "Black Roll-neck", brand: "Prada" }, { item: "Chelsea Boot", brand: "Bottega Veneta" }] },
      { name: "Press Tour", pieces: [{ item: "Cashmere Crewneck", brand: "Loro Piana" }, { item: "Relaxed Chino", brand: "Ralph Lauren Purple Label" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
    ],
  },
  {
    id: "rihanna",
    name: "Rihanna",
    title: "The Fashion Rule Breaker",
    style: "Avant-garde Power",
    description: "She wore a yellow Guo Pei gown to the Met and made it the most iconic fashion moment of the decade. Riri's wardrobe is fearless — couture to maternity streetwear, everything is intentional.",
    image: PHOTOS.rihanna,
    accentColor: "#E8C4C4",
    era: "2007–Present",
    knownFor: "Fenty, Dior Ambassador, Met Gala icon",
    signatureBrands: ["Fenty", "Christian Dior", "Puma x Fenty", "Manolo Blahnik", "Alaïa"],
    keyPieces: ["Oversized fur coat", "Latex bodysuit", "Thigh-high boots", "Crystal-embellished gown", "Fenty wide-leg suit"],
    vibes: ["Avant-garde", "Power Dressing", "Street Couture"],
    looks: [
      { name: "Fenty Power", pieces: [{ item: "Sculptural Bodysuit", brand: "Alaïa" }, { item: "Wide-Leg Leather Trouser", brand: "Fenty" }, { item: "Block Heel Boot", brand: "Manolo Blahnik" }] },
      { name: "Pregnant & Draped", pieces: [{ item: "Crystal Mini Dress", brand: "Valentino" }, { item: "Fur Cocoon Coat", brand: "Vetements" }, { item: "Pointed Mule", brand: "The Row" }] },
      { name: "Met Gala Yellow", pieces: [{ item: "Couture Cape Gown", brand: "Guo Pei" }, { item: "Diamond Crown", brand: "Harry Winston" }, { item: "Embellished Platform", brand: "Custom" }] },
      { name: "Barbados Carnival", pieces: [{ item: "Beaded Bikini Set", brand: "Custom" }, { item: "Feather Headdress", brand: "Custom" }, { item: "Platform Sneaker", brand: "Puma Fenty" }] },
      { name: "Super Bowl Queen", pieces: [{ item: "Silver Mesh Catsuit", brand: "Loewe" }, { item: "Thigh-High Boot", brand: "Stuart Weitzman" }, { item: "Diamond Cuff", brand: "Tiffany & Co" }] },
      { name: "Crystal Lady", pieces: [{ item: "Crystal Corset", brand: "Atelier Versace" }, { item: "Micro Mini Skirt", brand: "Versace" }, { item: "Strappy Heel", brand: "Amina Muaddi" }] },
      { name: "Vogue Paris", pieces: [{ item: "Chinchilla Coat", brand: "Dries Van Noten" }, { item: "Leather Bodysuit", brand: "Alaïa" }, { item: "Patent Thigh Boot", brand: "Louboutin" }] },
      { name: "Fenty Business", pieces: [{ item: "Power Blazer", brand: "Fenty" }, { item: "High-Waist Trouser", brand: "Fenty" }, { item: "Square-Toe Heel", brand: "The Row" }] },
      { name: "Street Couture", pieces: [{ item: "Oversized Bomber", brand: "Balenciaga" }, { item: "Biker Short", brand: "Fenty" }, { item: "Platform Sneaker", brand: "Raf Simons x Adidas" }] },
      { name: "Night Out", pieces: [{ item: "Draped Mini Dress", brand: "Saint Laurent" }, { item: "Fishnet Tight", brand: "Falke" }, { item: "Stiletto Ankle Strap", brand: "Louboutin" }] },
      { name: "Ivy Park Drop", pieces: [{ item: "Matching Tracksuit", brand: "Ivy Park x Adidas" }, { item: "Sneaker Wedge", brand: "Adidas" }, { item: "Gold Jewelry Stack", brand: "Custom" }] },
      { name: "Red Carpet Bad", pieces: [{ item: "Asymmetric Gown", brand: "Giambattista Valli" }, { item: "Statement Earring", brand: "Bulgari" }, { item: "Strappy Sandal", brand: "Jimmy Choo" }] },
    ],
  },
  {
    id: "kanye",
    name: "Kanye West",
    title: "The Godfather of Fashion Rap",
    style: "Yeezy Minimalism",
    description: "From Louis Vuitton Don to Yeezy Season, Kanye remapped how hip-hop interacts with high fashion. Earth tones, Gap hoodies, and $800 slides changed everything.",
    image: PHOTOS.kanye,
    accentColor: "#9E8878",
    era: "2004–Present",
    knownFor: "Yeezy, Balenciaga, Gap, Bottega",
    signatureBrands: ["Yeezy", "Balenciaga", "Bottega Veneta", "Gap", "Louis Vuitton"],
    keyPieces: ["Yeezy foam runner", "Oversized hoodie", "Earth-tone long coat", "Tactical vest", "Yeezy Boost 350"],
    vibes: ["Minimal Luxury", "Luxury Streetwear", "Avant-garde"],
    looks: [
      { name: "Yeezy Season", pieces: [{ item: "Distressed Hoodie", brand: "Yeezy Gap" }, { item: "Cargo Jogger", brand: "Yeezy" }, { item: "Foam Runner", brand: "Adidas Yeezy" }] },
      { name: "Saint Pablo", pieces: [{ item: "Teddy Coat", brand: "Balenciaga" }, { item: "Military Trousers", brand: "Yeezy" }, { item: "Chelsea Boot", brand: "Bottega Veneta" }] },
      { name: "Donda Era", pieces: [{ item: "Tactical Vest", brand: "Fear of God" }, { item: "Slim All-Black Pant", brand: "Yeezy" }, { item: "Yeezy 500 Utility", brand: "Adidas Yeezy" }] },
      { name: "Gap God", pieces: [{ item: "Yeezy Gap Round Jacket", brand: "Yeezy Gap" }, { item: "Basic Tee", brand: "Yeezy" }, { item: "Foam Runner", brand: "Adidas Yeezy" }] },
      { name: "Balenciaga Ye", pieces: [{ item: "Logo Tracksuit", brand: "Balenciaga" }, { item: "Oversized Hoodie", brand: "Balenciaga" }, { item: "Speed Trainer", brand: "Balenciaga" }] },
      { name: "Earth Tone", pieces: [{ item: "Neutral Trench Coat", brand: "Bottega Veneta" }, { item: "Earth-Tone Knit", brand: "Yeezy" }, { item: "Combat Boot", brand: "Yeezy" }] },
      { name: "LV Don Era", pieces: [{ item: "Monogram Suit", brand: "Louis Vuitton" }, { item: "Graphic Tee", brand: "Louis Vuitton" }, { item: "LV Sneaker", brand: "Louis Vuitton" }] },
      { name: "Ye Casual", pieces: [{ item: "Plain White Tee", brand: "Hanes" }, { item: "Cargo Pant", brand: "Yeezy" }, { item: "Yeezy Boost 350 V2", brand: "Adidas Yeezy" }] },
      { name: "Power Suit", pieces: [{ item: "Double-Breasted Suit", brand: "Balmain" }, { item: "Mock-Neck Knit", brand: "Zegna" }, { item: "Italian Leather Shoe", brand: "Berluti" }] },
      { name: "Minimal Noir", pieces: [{ item: "Long Black Coat", brand: "Rick Owens" }, { item: "Black Turtleneck", brand: "Rick Owens" }, { item: "DRKSHDW Boot", brand: "Rick Owens" }] },
      { name: "Stadium Tour", pieces: [{ item: "Shearling Jacket", brand: "Loro Piana" }, { item: "Distressed Denim", brand: "KSUBI" }, { item: "Jordan 1 Retro", brand: "Nike" }] },
      { name: "Wyoming Chapter", pieces: [{ item: "Flannel Shirt", brand: "L.L.Bean" }, { item: "Workwear Denim", brand: "Wrangler" }, { item: "Timberland Pro Boot", brand: "Timberland" }] },
    ],
  },
  {
    id: "travis",
    name: "Travis Scott",
    title: "Cactus Jack Couture",
    style: "Psychedelic Streetwear",
    description: "Travis turned Astroworld into a fashion universe. Cactus Jack collaborations with Nike, McDonald's, and Jordan made streetwear into cultural events.",
    image: PHOTOS.travis,
    accentColor: "#8B7355",
    era: "2016–Present",
    knownFor: "Cactus Jack x Jordan, Off-White, Raf Simons",
    signatureBrands: ["Cactus Jack", "Jordan Brand", "Off-White", "Helmut Lang", "Raf Simons"],
    keyPieces: ["Air Jordan 1 Retro Low", "Graphic tee", "Biker jacket", "Cargo trousers", "Camo elements"],
    vibes: ["Luxury Streetwear", "Psych", "Festival"],
    looks: [
      { name: "Astroworld Ready", pieces: [{ item: "Cactus Jack Graphic Tee", brand: "Cactus Jack" }, { item: "Distressed Denim", brand: "Helmut Lang" }, { item: "Jordan 1 Retro Low", brand: "Nike" }] },
      { name: "Stage King", pieces: [{ item: "Biker Jacket", brand: "Raf Simons" }, { item: "Cargo Trousers", brand: "Maharishi" }, { item: "Platform Boot", brand: "Rick Owens" }] },
      { name: "Cactus Jack Collab", pieces: [{ item: "Travis x Jordan 1", brand: "Nike" }, { item: "Fragment Tee", brand: "Fragment Design" }, { item: "Slim Denim", brand: "Helmut Lang" }] },
      { name: "McDonald's Drop", pieces: [{ item: "Cactus Jack Hoodie", brand: "Travis x McDonald's" }, { item: "Track Pant", brand: "Nike" }, { item: "Air Max 1", brand: "Nike" }] },
      { name: "Festival Rage", pieces: [{ item: "Camo Jacket", brand: "Maharishi" }, { item: "Graphic Tee", brand: "Cactus Jack" }, { item: "Cargo Short", brand: "Nike ACG" }] },
      { name: "La Flame Formal", pieces: [{ item: "Custom Dior Suit", brand: "Dior" }, { item: "Silk Shirt", brand: "Dior" }, { item: "Oxford", brand: "Berluti" }] },
      { name: "Studio Grind", pieces: [{ item: "Zip-Up Hoodie", brand: "Fear of God Essentials" }, { item: "Sweatpant", brand: "Fear of God" }, { item: "New Balance 990", brand: "New Balance" }] },
      { name: "Night Owl", pieces: [{ item: "Leather Biker", brand: "Saint Laurent" }, { item: "Black Skinny Denim", brand: "Amiri" }, { item: "Chelsea Boot", brand: "Rick Owens" }] },
      { name: "Utopia Mode", pieces: [{ item: "Distressed Knit", brand: "Helmut Lang" }, { item: "Cargo Trouser", brand: "Gramicci" }, { item: "Vintage Sneaker", brand: "Adidas" }] },
      { name: "SoHo Heat", pieces: [{ item: "Puffer Vest", brand: "Moncler" }, { item: "Heavyweight Crewneck", brand: "CPFM" }, { item: "Slim Denim", brand: "Nudie Jeans" }] },
      { name: "Backstage Boss", pieces: [{ item: "Vintage Track Jacket", brand: "Adidas" }, { item: "Bandana", brand: "Custom" }, { item: "Retro Basketball Shoe", brand: "Nike" }] },
      { name: "Psychedelic Floral", pieces: [{ item: "Floral Print Shirt", brand: "Prada" }, { item: "Wide-Leg Trouser", brand: "Needles" }, { item: "Platform Sneaker", brand: "Rick Owens" }] },
    ],
  },
  {
    id: "fabolous",
    name: "Fabolous",
    title: "Brooklyn's Best Dressed",
    style: "New York Uptown",
    description: "Fabolous turned Brooklyn hip-hop into a luxury fashion school. Fitted caps, Clarks Wallabees, and just the right amount of bling — effortlessly NY.",
    image: PHOTOS.fabolous,
    accentColor: "#A89070",
    era: "2001–Present",
    knownFor: "NY streetwear, fitted caps, designer denim",
    signatureBrands: ["Gucci", "Versace", "Ralph Lauren", "Clarks", "True Religion"],
    keyPieces: ["Designer denim", "Fitted cap", "Gold chain", "Clarks Desert Boot", "Varsity jacket"],
    vibes: ["NY Uptown", "Luxury Streetwear", "Classic Hip-hop"],
    looks: [
      { name: "Brooklyn Uptown", pieces: [{ item: "Fitted Cap", brand: "New Era" }, { item: "Slim-Fit Denim", brand: "True Religion" }, { item: "Desert Boot", brand: "Clarks" }] },
      { name: "NY Nights", pieces: [{ item: "Leather Jacket", brand: "Versace" }, { item: "Slim Chino", brand: "Gucci" }, { item: "Gold Rope Chain", brand: "Jacob & Co" }] },
      { name: "BK Fitted", pieces: [{ item: "Team Jersey", brand: "Mitchell & Ness" }, { item: "Fitted Cap", brand: "New Era" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Uptown Sunday", pieces: [{ item: "Polo Oxford Shirt", brand: "Ralph Lauren" }, { item: "Clean Denim", brand: "True Religion" }, { item: "Chelsea Boot", brand: "Timberland" }] },
      { name: "Gold Rope Heavy", pieces: [{ item: "Mink Coat", brand: "Custom Furrier" }, { item: "Gold Cuban Chain", brand: "Jacob & Co" }, { item: "Air Jordan 3", brand: "Nike" }] },
      { name: "Summer Cookout", pieces: [{ item: "Linen Polo", brand: "Ralph Lauren" }, { item: "Cargo Short", brand: "Polo Ralph Lauren" }, { item: "Huarache", brand: "Nike" }] },
      { name: "Bodega Run", pieces: [{ item: "Windbreaker", brand: "Tommy Hilfiger" }, { item: "Sweatpant", brand: "Champion" }, { item: "Air Max 95", brand: "Nike" }] },
      { name: "NY Fashion Week", pieces: [{ item: "Double-Breasted Suit", brand: "Tom Ford" }, { item: "Turtleneck", brand: "Zegna" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Court Ready", pieces: [{ item: "Basketball Shorts", brand: "Nike" }, { item: "Retro Polo", brand: "Polo Sport" }, { item: "Air Jordan 11", brand: "Nike" }] },
      { name: "Dinner at Nobu", pieces: [{ item: "Silk Shirt", brand: "Versace" }, { item: "Black Slacks", brand: "Tom Ford" }, { item: "Loafer", brand: "Prada" }] },
      { name: "Club Night", pieces: [{ item: "Balmain Blazer", brand: "Balmain" }, { item: "Black Skinny Jean", brand: "KSUBI" }, { item: "Chelsea Boot", brand: "Saint Laurent" }] },
      { name: "Park Slope Chill", pieces: [{ item: "Coach Jacket", brand: "Carhartt" }, { item: "White Tee", brand: "Hanes" }, { item: "New Balance 990", brand: "New Balance" }] },
    ],
  },
  {
    id: "denzel",
    name: "Denzel Washington",
    title: "Hollywood's Timeless Gentleman",
    style: "Classic American Elegance",
    description: "No trend, no gimmicks — just perfectly cut suits, Italian leather, and the quiet confidence of someone who has always known exactly who they are.",
    image: PHOTOS.denzel,
    accentColor: "#8899A0",
    era: "1980s–Present",
    knownFor: "Perfectly cut suits, understated elegance",
    signatureBrands: ["Tom Ford", "Giorgio Armani", "Brioni", "Zegna", "Gucci"],
    keyPieces: ["Perfectly-cut black suit", "White pocket square", "Oxford shirt", "Italian leather Oxford", "Understated watch"],
    vibes: ["Old Money", "Classic Elegance", "Power Dressing"],
    looks: [
      { name: "Hollywood Formal", pieces: [{ item: "Black Tuxedo", brand: "Tom Ford" }, { item: "French Cuff Shirt", brand: "Zegna" }, { item: "Patent Oxford", brand: "Gucci" }] },
      { name: "Press Day", pieces: [{ item: "Charcoal Suit", brand: "Giorgio Armani" }, { item: "Silk Tie", brand: "Brioni" }, { item: "Oxford Brogue", brand: "Edward Green" }] },
      { name: "Oscar Ceremony", pieces: [{ item: "White Tuxedo Jacket", brand: "Tom Ford" }, { item: "Black Trousers", brand: "Tom Ford" }, { item: "Patent Derby", brand: "Gucci" }] },
      { name: "Golden Globes", pieces: [{ item: "Navy Peaked-Lapel Suit", brand: "Brioni" }, { item: "Powder-Blue Tie", brand: "Charvet" }, { item: "Cap-Toe Oxford", brand: "John Lobb" }] },
      { name: "Premiere Night", pieces: [{ item: "Black Velvet Tuxedo", brand: "Giorgio Armani" }, { item: "White Tuxedo Shirt", brand: "Brioni" }, { item: "Velvet Loafer", brand: "Gucci" }] },
      { name: "Sunday Best", pieces: [{ item: "Grey Flannel Suit", brand: "Zegna" }, { item: "White Linen Shirt", brand: "Charvet" }, { item: "Suede Loafer", brand: "Edward Green" }] },
      { name: "Red Carpet Quiet", pieces: [{ item: "Midnight Navy Suit", brand: "Tom Ford" }, { item: "Knit Tie", brand: "The Row" }, { item: "Oxford Brogue", brand: "Berluti" }] },
      { name: "Press Junket", pieces: [{ item: "Camel Cashmere Overcoat", brand: "Loro Piana" }, { item: "Charcoal Suit", brand: "Armani" }, { item: "Leather Chelsea Boot", brand: "Gucci" }] },
      { name: "Gentleman Casual", pieces: [{ item: "Polo Shirt", brand: "Loro Piana" }, { item: "Slim Chino", brand: "Ralph Lauren Purple Label" }, { item: "Suede Loafer", brand: "Tod's" }] },
      { name: "Master Class", pieces: [{ item: "Tweed Sport Coat", brand: "Ralph Lauren" }, { item: "Roll-Neck Knit", brand: "Brunello Cucinelli" }, { item: "Oxford Trouser", brand: "Zegna" }] },
      { name: "Awards Season", pieces: [{ item: "Black Three-Piece Suit", brand: "Tom Ford" }, { item: "Silk Pocket Square", brand: "Hermès" }, { item: "Patent Oxford", brand: "Berluti" }] },
      { name: "Casual Friday", pieces: [{ item: "Cashmere Crewneck", brand: "Loro Piana" }, { item: "Slim Dark Denim", brand: "AG Jeans" }, { item: "Clean White Sneaker", brand: "Common Projects" }] },
    ],
  },
  {
    id: "snoop",
    name: "Snoop Dogg",
    title: "Long Beach's Most Stylish OG",
    style: "California Cool",
    description: "The OG of laid-back California luxury. Snoop evolved from Doggystyle Dickies to Gucci tracksuits — always relaxed, always dripping, always himself.",
    image: PHOTOS.snoop,
    accentColor: "#7A9E7E",
    era: "1992–Present",
    knownFor: "Tracksuits, braids, California 420 luxury",
    signatureBrands: ["Gucci", "Adidas", "Death Row", "Snoop Dogg x Skechers", "Coach"],
    keyPieces: ["Velour tracksuit", "G-funk cap", "Gucci loafer", "Gold rope", "Croc-skin accessories"],
    vibes: ["California Cool", "Old School Luxe", "Laid-back Hip-hop"],
    looks: [
      { name: "West Coast OG", pieces: [{ item: "Gucci Velour Tracksuit", brand: "Gucci" }, { item: "Bucket Hat", brand: "Kangol" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Gin & Juice Night", pieces: [{ item: "Silk Bowling Shirt", brand: "Dries Van Noten" }, { item: "Wide-leg Linen Trouser", brand: "The Row" }, { item: "Suede Loafer", brand: "Gucci" }] },
      { name: "420 Grateful", pieces: [{ item: "Tie-Dye Tee", brand: "Death Row Era" }, { item: "Dickies Pant", brand: "Dickies" }, { item: "Vans Old Skool", brand: "Vans" }] },
      { name: "Doggfather Luxe", pieces: [{ item: "Silk Gucci Tracksuit", brand: "Gucci" }, { item: "Bucket Hat", brand: "Kangol" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Long Beach Summer", pieces: [{ item: "Hawaiian Shirt", brand: "Reyn Spooner" }, { item: "Linen Pant", brand: "Loro Piana" }, { item: "Loafer", brand: "Gucci" }] },
      { name: "Super Bowl Half", pieces: [{ item: "Black Tracksuit", brand: "Adidas" }, { item: "White Trainers", brand: "Adidas" }, { item: "Kufi Cap", brand: "Custom" }] },
      { name: "California Dreamin", pieces: [{ item: "Logo Hoodie", brand: "Death Row Records" }, { item: "Slim Jogger", brand: "Adidas" }, { item: "Cortez", brand: "Nike" }] },
      { name: "Coach Snoop", pieces: [{ item: "Sports Polo", brand: "Adidas" }, { item: "Coaching Short", brand: "Adidas" }, { item: "New Balance 574", brand: "New Balance" }] },
      { name: "BET Awards", pieces: [{ item: "Purple Velvet Blazer", brand: "Saint Laurent" }, { item: "Black Turtleneck", brand: "Amiri" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Smoke & Mirrors", pieces: [{ item: "Shaggy Fur Coat", brand: "Custom" }, { item: "Black Leather Trouser", brand: "The Row" }, { item: "Patent Loafer", brand: "Gucci" }] },
      { name: "Cali Gold", pieces: [{ item: "White Linen Set", brand: "Loro Piana" }, { item: "Gold Chain", brand: "Jacob & Co" }, { item: "Espadrille", brand: "Rivieras" }] },
      { name: "Snoopzilla Funk", pieces: [{ item: "Sequin Jacket", brand: "Custom" }, { item: "Platform Boot", brand: "Sergio Rossi" }, { item: "Gold Medallion", brand: "Custom" }] },
    ],
  },
  {
    id: "jeezy",
    name: "Young Jeezy",
    title: "Atlanta Trap Royalty",
    style: "ATL Trap Luxe",
    description: "Jeezy turned Atlanta streets into a fashion statement. He brought the white tee movement to its peak and proved that trap music and luxury fashion were never mutually exclusive.",
    image: PHOTOS.jeezy,
    accentColor: "#A0A0A0",
    era: "2005–Present",
    knownFor: "Snowflake era, designer belts, ATL drip",
    signatureBrands: ["Versace", "Balenciaga", "Balmain", "Moncler", "Iceberg"],
    keyPieces: ["Moncler puffer", "Versace belt", "White tee", "Nike Air Force 1", "Gold Cuban chain"],
    vibes: ["Trap Luxe", "Luxury Streetwear", "ATL"],
    looks: [
      { name: "Snowman Season", pieces: [{ item: "Moncler Down Puffer", brand: "Moncler" }, { item: "Designer Denim", brand: "True Religion" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Corporate Thuggin", pieces: [{ item: "Versace Blazer", brand: "Versace" }, { item: "Balmain Jeans", brand: "Balmain" }, { item: "Luxury Boot", brand: "Giuseppe Zanotti" }] },
      { name: "ATL All-Star", pieces: [{ item: "White Air Force 1", brand: "Nike" }, { item: "White Tee", brand: "Fruit of the Loom" }, { item: "Designer Denim", brand: "Evisu" }] },
      { name: "Trap or Die", pieces: [{ item: "Moncler Vest", brand: "Moncler" }, { item: "Champion Hoodie", brand: "Champion" }, { item: "Air Jordan 11", brand: "Nike" }] },
      { name: "Certified Gansta", pieces: [{ item: "Iceberg Sweater", brand: "Iceberg" }, { item: "Dark Denim", brand: "True Religion" }, { item: "Timberland Boot", brand: "Timberland" }] },
      { name: "Business of Rap", pieces: [{ item: "Double-Breasted Suit", brand: "Tom Ford" }, { item: "White Spread Collar Shirt", brand: "Brioni" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Versace Everything", pieces: [{ item: "Baroque Shirt", brand: "Versace" }, { item: "Black Slim Pant", brand: "Gucci" }, { item: "Chelsea Boot", brand: "Versace" }] },
      { name: "Gold Standard", pieces: [{ item: "Mink Coat", brand: "Custom" }, { item: "Cuban Link Chain", brand: "Jacob & Co" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Snowflake Era", pieces: [{ item: "White Moncler Puffer", brand: "Moncler" }, { item: "White Tee", brand: "Hanes" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "ATL Uptown", pieces: [{ item: "Polo Oxford", brand: "Ralph Lauren" }, { item: "Straight Denim", brand: "True Religion" }, { item: "Boat Shoe", brand: "Timberland" }] },
      { name: "Label Boss", pieces: [{ item: "Pinstripe Suit", brand: "Brioni" }, { item: "Silk Tie", brand: "Hermès" }, { item: "Italian Loafer", brand: "Berluti" }] },
      { name: "Street General", pieces: [{ item: "Army-Green Camo Jacket", brand: "G-Star" }, { item: "Heavyweight Hoodie", brand: "Acne Studios" }, { item: "Cargo Pant", brand: "Carhartt" }] },
    ],
  },
  {
    id: "zendaya",
    name: "Zendaya",
    title: "Fashion's Reigning Queen",
    style: "Avant-garde Theatre",
    description: "From spider-web Valentino to robotic Mugler at the Met — Zendaya's stylist Law Roach transformed her into fashion's greatest theatrical act. Every look tells a story.",
    image: PHOTOS.zendaya,
    accentColor: "#D4A8B0",
    era: "2014–Present",
    knownFor: "Law Roach styling, Valentino, Met Gala moments",
    signatureBrands: ["Valentino", "Mugler", "Versace", "Louis Vuitton", "Armani"],
    keyPieces: ["Sculptural gown", "Spider-web heels", "Chainmail dress", "Romantic corset", "Statement jewelry"],
    vibes: ["Avant-garde", "Theatrical", "High Fashion"],
    looks: [
      { name: "Dune Premiere", pieces: [{ item: "Column Gown", brand: "Valentino" }, { item: "Statement Earrings", brand: "Bulgari" }, { item: "Strappy Heel", brand: "Roger Vivier" }] },
      { name: "Challengers", pieces: [{ item: "Colourblock Polo Dress", brand: "Louis Vuitton" }, { item: "Visor", brand: "Nike" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Spider-Man Edit", pieces: [{ item: "Chainmail Mini Dress", brand: "Valentino" }, { item: "Web-Detail Stiletto", brand: "Custom" }, { item: "Drop Earring", brand: "Tiffany & Co" }] },
      { name: "Euphoria Glam", pieces: [{ item: "Crystal Crop Top", brand: "Mugler" }, { item: "High-Waist Wide Leg", brand: "Tom Ford" }, { item: "Strappy Sandal", brand: "Amina Muaddi" }] },
      { name: "Valentino Roma", pieces: [{ item: "Hot-Pink Couture Gown", brand: "Valentino Haute Couture" }, { item: "Long White Glove", brand: "Custom" }, { item: "Crystal Heel", brand: "Valentino" }] },
      { name: "Met Gala Robot", pieces: [{ item: "Silver Robot Suit", brand: "Mugler Archive" }, { item: "Glove Boot", brand: "Mugler" }, { item: "Crystal Crown", brand: "Custom" }] },
      { name: "Joan of Arc", pieces: [{ item: "Armour-Inspired Gown", brand: "Versace" }, { item: "Chainmail Veil", brand: "Custom" }, { item: "Flat Thong Sandal", brand: "Valentino" }] },
      { name: "Tennis Princess", pieces: [{ item: "Pleated Mini Dress", brand: "Louis Vuitton" }, { item: "Knit Sock", brand: "Falke" }, { item: "Platform Tennis Shoe", brand: "Nike" }] },
      { name: "Old Hollywood Z", pieces: [{ item: "Black Column Gown", brand: "The Row" }, { item: "Opera Gloves", brand: "Fownes" }, { item: "Strappy Heel", brand: "Roger Vivier" }] },
      { name: "Retro Action", pieces: [{ item: "70s Floral Jumpsuit", brand: "Etro" }, { item: "Platform Sandal", brand: "Saint Laurent" }, { item: "Gold Hoop Earring", brand: "Jennifer Fisher" }] },
      { name: "Z By Day", pieces: [{ item: "Wide-Leg Denim", brand: "Agolde" }, { item: "Cropped Blazer", brand: "Toteme" }, { item: "Kitten-Heel Loafer", brand: "The Row" }] },
      { name: "Mugler Muse", pieces: [{ item: "Spirale Gown", brand: "Mugler" }, { item: "Pointed Stiletto", brand: "Louboutin" }, { item: "Sculptural Cuff", brand: "Bottega Veneta" }] },
    ],
  },
  {
    id: "harry",
    name: "Harry Styles",
    title: "The Gender-Fluid Rock God",
    style: "Vintage Eclectic Glamour",
    description: "Harry proved that pearl necklaces, feather boas, and Gucci jumpsuits belong on everyone. A vintage eclectic spirit that's part Elton John, part Mick Jagger, part utterly himself.",
    image: PHOTOS.harry,
    accentColor: "#C4A8C4",
    era: "2017–Present",
    knownFor: "Gucci muse, gender-fluid, vintage, feather boa",
    signatureBrands: ["Gucci", "Vivienne Westwood", "Palomo Spain", "JW Anderson", "Pleasing"],
    keyPieces: ["Flared trouser", "Feather boa", "Pearl necklace", "Platform Chelsea boot", "Colourful suit"],
    vibes: ["Eclectic", "Gender-Fluid", "Vintage Glam", "70s Revival"],
    looks: [
      { name: "Golden Hour", pieces: [{ item: "Colourblock Suit", brand: "Gucci" }, { item: "Ruffled Blouse", brand: "JW Anderson" }, { item: "Platform Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Fine Line Era", pieces: [{ item: "Pearl Necklace", brand: "Mikimoto" }, { item: "High-Waist Flare", brand: "Palomo Spain" }, { item: "Feather Jacket", brand: "Gucci" }] },
      { name: "Watermelon Sugar", pieces: [{ item: "Fishnet Vest", brand: "JW Anderson" }, { item: "Vintage Flare Trouser", brand: "Levi's Vintage" }, { item: "Platform Wedge", brand: "Stella McCartney" }] },
      { name: "Spheres Tour", pieces: [{ item: "Crystal Jumpsuit", brand: "Gucci" }, { item: "Elton-Era Glasses", brand: "Custom" }, { item: "Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Coachella King", pieces: [{ item: "Sheer Floral Blouse", brand: "Gucci" }, { item: "High-Waist Linen Short", brand: "Palomo Spain" }, { item: "Cowboy Boot", brand: "Vintage" }] },
      { name: "SNL Boa", pieces: [{ item: "Sequin Blazer", brand: "Gucci" }, { item: "Feather Boa", brand: "Custom" }, { item: "Velvet Flare", brand: "Gucci" }] },
      { name: "Gucci House", pieces: [{ item: "Gucci Cardigan Suit", brand: "Gucci" }, { item: "White Tee", brand: "Sunspel" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
      { name: "Harry's House", pieces: [{ item: "Patchwork Blazer", brand: "JW Anderson" }, { item: "Wide-Leg Trouser", brand: "Palomo Spain" }, { item: "Flatform Boot", brand: "Vivienne Westwood" }] },
      { name: "Tokyo Vintage", pieces: [{ item: "Vintage Leather Jacket", brand: "Vintage" }, { item: "Graphic Tee", brand: "Vintage" }, { item: "Straight Crop Trouser", brand: "Gucci" }] },
      { name: "Night Glitter", pieces: [{ item: "Full-Sequin Suit", brand: "Gucci" }, { item: "Sheer Blouse", brand: "Palomo Spain" }, { item: "Platform Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Garden Party", pieces: [{ item: "Floral Tea-Length Dress", brand: "Gucci Custom" }, { item: "Platform Mary Jane", brand: "Vivienne Westwood" }, { item: "Floral Crown", brand: "Custom" }] },
      { name: "Airport Departure", pieces: [{ item: "Oversized Shearling", brand: "Gucci" }, { item: "Wide-Leg Trouser", brand: "Toteme" }, { item: "Chelsea Boot", brand: "Vivienne Westwood" }] },
    ],
  },
  {
    id: "pharrell",
    name: "Pharrell Williams",
    title: "The Eternal Skater Visionary",
    style: "Eclectic Luxury Supreme",
    description: "Pharrell invented the massive Vivienne Westwood hat moment and now runs Louis Vuitton Men's. His style is an art installation — Chanel, skateboarding, Billionaire Boys Club, and the brain of a genius.",
    image: PHOTOS.pharrell,
    accentColor: "#C6A75E",
    era: "1999–Present",
    knownFor: "BBC Ice Cream, LV Men's Director, hat collector",
    signatureBrands: ["Louis Vuitton", "Chanel", "Billionaire Boys Club", "adidas", "Vivienne Westwood"],
    keyPieces: ["Giant western hat", "BBC logo tee", "Adidas Human Race", "Chanel accessories", "Custom LV sneaker"],
    vibes: ["Eclectic Luxury", "Skate Culture", "Art World"],
    looks: [
      { name: "LV Creative Director", pieces: [{ item: "Custom LV Suit", brand: "Louis Vuitton" }, { item: "Platform Sneaker", brand: "LV" }, { item: "Diamond Earring", brand: "Jacob & Co" }] },
      { name: "BBC OG", pieces: [{ item: "BBC Logo Tee", brand: "Billionaire Boys Club" }, { item: "Slim Jogger", brand: "Adidas" }, { item: "Human Race Sneaker", brand: "Adidas" }] },
      { name: "Vivienne Hat", pieces: [{ item: "Massive Tartan Hat", brand: "Vivienne Westwood" }, { item: "Tweed Jacket", brand: "Chanel" }, { item: "White Jeans", brand: "A.P.C." }] },
      { name: "Human Race Launch", pieces: [{ item: "Human Race Sneaker", brand: "Adidas x Pharrell" }, { item: "Graphic Tee", brand: "NERD" }, { item: "Slim Jogger", brand: "Adidas" }] },
      { name: "Skateboard P", pieces: [{ item: "Logo Hoodie", brand: "BBC Ice Cream" }, { item: "Skate Pant", brand: "Dickies" }, { item: "Skate Shoe", brand: "Vans" }] },
      { name: "Grammy Cowboy", pieces: [{ item: "Western Hat", brand: "Vivienne Westwood" }, { item: "Denim Jacket", brand: "Vintage Levi's" }, { item: "Cowboy Boot", brand: "Custom" }] },
      { name: "Chanel Bro", pieces: [{ item: "Tweed Jacket", brand: "Chanel" }, { item: "Chain Detail Pant", brand: "Chanel" }, { item: "Logo Sneaker", brand: "Chanel" }] },
      { name: "LV Men's FW", pieces: [{ item: "Tailored Coat", brand: "Louis Vuitton" }, { item: "Printed Shirt", brand: "Louis Vuitton" }, { item: "LV Sneaker", brand: "Louis Vuitton" }] },
      { name: "Art Basel", pieces: [{ item: "Colourblock Jacket", brand: "Kenzo" }, { item: "Wide-Leg Corduroy", brand: "Needles" }, { item: "Platform Sneaker", brand: "Sacai x Nike" }] },
      { name: "N.E.R.D. Rock", pieces: [{ item: "Vintage Band Tee", brand: "NERD Vintage" }, { item: "Slim Denim", brand: "Nudie" }, { item: "Vintage Sneaker", brand: "Adidas" }] },
      { name: "Neptune Fresh", pieces: [{ item: "Pastel Linen Set", brand: "Loro Piana" }, { item: "Massive Straw Hat", brand: "Vivienne Westwood" }, { item: "Platform Loafer", brand: "Louis Vuitton" }] },
      { name: "Happy Days", pieces: [{ item: "White Linen Suit", brand: "Loro Piana" }, { item: "Gucci Scarf", brand: "Gucci" }, { item: "Moccasin", brand: "Gucci" }] },
    ],
  },
  {
    id: "audrey",
    name: "Audrey Hepburn",
    title: "Hollywood's Eternal Muse",
    style: "Classic Hollywood Elegance",
    description: "The little black dress, the Givenchy trench, the Breakfast at Tiffany's neckline. Audrey's wardrobe defined Hollywood glamour without ever trying to compete — it simply arrived and stayed.",
    image: PHOTOS.audrey,
    accentColor: "#C0B090",
    era: "1950s–1960s",
    knownFor: "Givenchy muse, the LBD, Holly Golightly aesthetic",
    signatureBrands: ["Givenchy", "Balenciaga", "Ferragamo", "Valentino", "Tiffany & Co"],
    keyPieces: ["The little black dress", "White gloves", "Cigarette trouser", "Ballet flat", "Cat-eye sunglasses"],
    vibes: ["Classic Elegance", "Old Money", "Timeless"],
    looks: [
      { name: "Breakfast at Tiffany's", pieces: [{ item: "Black Sheath Dress", brand: "Givenchy" }, { item: "Long White Gloves", brand: "Fownes" }, { item: "Pearl Drop Earrings", brand: "Tiffany & Co" }] },
      { name: "Roman Holiday", pieces: [{ item: "Cigarette Trouser", brand: "Givenchy" }, { item: "Striped Blouse", brand: "Givenchy" }, { item: "Capri Ballet Flat", brand: "Ferragamo" }] },
      { name: "Sabrina Chic", pieces: [{ item: "Strapless Organza Gown", brand: "Givenchy" }, { item: "Elbow-Length Glove", brand: "Dents" }, { item: "Kitten Heel", brand: "Ferragamo" }] },
      { name: "War & Peace", pieces: [{ item: "Cashmere Twinset", brand: "Givenchy" }, { item: "Cigarette Trouser", brand: "Givenchy" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Paris Enchantment", pieces: [{ item: "Apple-Green Empire Gown", brand: "Givenchy Haute Couture" }, { item: "Long White Glove", brand: "Custom" }, { item: "Strappy Heel", brand: "Givenchy" }] },
      { name: "Funny Face", pieces: [{ item: "Red Trapeze Coat", brand: "Balenciaga" }, { item: "Black Roll-Neck", brand: "Givenchy" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Garden Tea", pieces: [{ item: "Broderie Anglaise Sundress", brand: "Givenchy" }, { item: "Wide-Brim Straw Hat", brand: "Custom" }, { item: "Espadrille Wedge", brand: "Ferragamo" }] },
      { name: "Charade Style", pieces: [{ item: "Red Plaid Suit Jacket", brand: "Givenchy" }, { item: "Slim Trouser", brand: "Givenchy" }, { item: "Oxford Pump", brand: "Ferragamo" }] },
      { name: "Simple Elegance", pieces: [{ item: "White Boat-Neck Top", brand: "Givenchy" }, { item: "Slim Black Trouser", brand: "Givenchy" }, { item: "Pearl Necklace", brand: "Tiffany & Co" }] },
      { name: "Princess Charity", pieces: [{ item: "Blush A-Line Gown", brand: "Valentino" }, { item: "Opera Glove", brand: "Fownes" }, { item: "Slingback Heel", brand: "Ferragamo" }] },
      { name: "Audrey At Work", pieces: [{ item: "White Wrap Blouse", brand: "Givenchy" }, { item: "Cropped Trouser", brand: "Givenchy" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Tiffany's Window", pieces: [{ item: "LBD", brand: "Givenchy" }, { item: "Cat-Eye Sunglasses", brand: "Oliver Goldsmith" }, { item: "Block Heel Pump", brand: "Ferragamo" }] },
    ],
  },
  {
    id: "marilyn",
    name: "Marilyn Monroe",
    title: "The Original Icon",
    style: "Old Hollywood Glamour",
    description: "She wore nothing but Chanel No. 5 and a smile, then wore the most famous dress in American history. Marilyn's sensuality was couture — calibrated, conscious, and entirely her own.",
    image: PHOTOS.marilyn,
    accentColor: "#F0D8C8",
    era: "1950s–1960s",
    knownFor: "Happy Birthday Mr. President gown, the white dress, Chanel",
    signatureBrands: ["Jean Louis", "Travilla", "Chanel", "Norman Norell", "Emilio Pucci"],
    keyPieces: ["Sequined column gown", "Red lips", "White halter dress", "Mink stole", "Diamond choker"],
    vibes: ["Old Hollywood", "Glamour", "Sensual Luxury"],
    looks: [
      { name: "Happy Birthday, Mr. President", pieces: [{ item: "Nude Sequined Column Gown", brand: "Jean Louis" }, { item: "Diamond Bracelet", brand: "Harry Winston" }, { item: "Barely-There Heel", brand: "Custom" }] },
      { name: "Manhattan Blonde", pieces: [{ item: "White Halter Dress", brand: "Travilla" }, { item: "Red Lip (Revlon)", brand: "Revlon" }, { item: "Block Heel Mule", brand: "Ferragamo" }] },
      { name: "Some Like It Hot", pieces: [{ item: "White Strapless Gown", brand: "Jean Louis" }, { item: "Diamond Drop Earring", brand: "Harry Winston" }, { item: "White Mule Heel", brand: "Custom" }] },
      { name: "Gentlemen Prefer", pieces: [{ item: "Pink Satin Strapless Gown", brand: "Travilla" }, { item: "Fur Stole", brand: "Custom" }, { item: "Platform Sandal", brand: "Custom" }] },
      { name: "Bus Stop Dream", pieces: [{ item: "Polka-Dot Sundress", brand: "Custom" }, { item: "Wide-Brim Sun Hat", brand: "Custom" }, { item: "Flat Espadrille", brand: "Custom" }] },
      { name: "Misfits", pieces: [{ item: "Pencil Skirt", brand: "Custom" }, { item: "Black Turtleneck", brand: "Custom" }, { item: "Kitten Heel", brand: "Ferragamo" }] },
      { name: "Diamond Girl", pieces: [{ item: "Hot-Pink Strapless Gown", brand: "Travilla" }, { item: "Long Gloves", brand: "Custom" }, { item: "Diamond Drop Earring", brand: "Harry Winston" }] },
      { name: "Marilyn at the Beach", pieces: [{ item: "Gold Lamé Bikini", brand: "Custom" }, { item: "White Linen Shirt", brand: "Custom" }, { item: "Flat Sandal", brand: "Custom" }] },
      { name: "Studio Portrait", pieces: [{ item: "Black Cocktail Dress", brand: "Norman Norell" }, { item: "Mink Stole", brand: "Custom" }, { item: "Stiletto", brand: "Ferragamo" }] },
      { name: "Norma Jean Casual", pieces: [{ item: "Cropped Sweater", brand: "Custom" }, { item: "High-Waist Trouser", brand: "Custom" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Korea Pinup", pieces: [{ item: "Military Parka", brand: "Custom" }, { item: "High-Waist Jean Short", brand: "Custom" }, { item: "Ankle Boot", brand: "Custom" }] },
      { name: "Red Carpet Marilyn", pieces: [{ item: "Cream Pleated Halter", brand: "Travilla" }, { item: "Diamond Choker", brand: "Harry Winston" }, { item: "Open-Toe Slingback", brand: "Ferragamo" }] },
    ],
  },
  {
    id: "ladygaga",
    name: "Lady Gaga",
    title: "Fashion's Greatest Provocateur",
    style: "Theatrical Avant-garde",
    description: "Meat dresses, nine-inch armadillo shoes, Alexander McQueen bubbles — Gaga turned fashion into performance art and performance into fashion. The boundary doesn't exist for her.",
    image: PHOTOS.ladygaga,
    accentColor: "#B0A0C8",
    era: "2008–Present",
    knownFor: "McQueen Armadillo shoes, Haus of Gaga, Met Gala theatrics",
    signatureBrands: ["Alexander McQueen", "Versace", "Valentino", "Atelier Versace", "Schiaparelli"],
    keyPieces: ["Armadillo shoe (McQueen)", "Platinum wig", "Crystal bodysuit", "Architectural headpiece", "Avant-garde gloves"],
    vibes: ["Avant-garde", "Theatrical", "Provocation"],
    looks: [
      { name: "Bad Romance", pieces: [{ item: "Ivory Architectural Gown", brand: "Schiaparelli" }, { item: "Crystal Headpiece", brand: "Custom" }, { item: "Platform Heel", brand: "Alexander McQueen" }] },
      { name: "Joanne Tour", pieces: [{ item: "Pink Cowboy Hat", brand: "Haus of Gaga" }, { item: "Rhinestone Bodysuit", brand: "Atelier Versace" }, { item: "Thigh-High Boot", brand: "Versace" }] },
      { name: "Applause Era", pieces: [{ item: "Sculptural Black Bodysuit", brand: "Versace" }, { item: "Architectural Headpiece", brand: "Custom" }, { item: "Platform Heel", brand: "Alexander McQueen" }] },
      { name: "ARTPOP Launch", pieces: [{ item: "Botticelli-Inspired Gown", brand: "Atelier Versace" }, { item: "Crystal Tiara", brand: "Swarovski" }, { item: "Embellished Heel", brand: "Custom" }] },
      { name: "A Star Is Born", pieces: [{ item: "Sequin Long Gown", brand: "Custom" }, { item: "Teardrop Earrings", brand: "Custom" }, { item: "Stiletto", brand: "Louboutin" }] },
      { name: "Chromatica Ball", pieces: [{ item: "Pink Latex Bodysuit", brand: "Haus Labs x Mugler" }, { item: "Pink Platform Boot", brand: "Custom" }, { item: "Crystal Armor Glove", brand: "Custom" }] },
      { name: "Super Bowl XLVII", pieces: [{ item: "Red Spiked Bodysuit", brand: "Custom" }, { item: "Thigh-High Red Boot", brand: "Custom" }, { item: "Diamond Cuff", brand: "Harry Winston" }] },
      { name: "Met Gala Camp", pieces: [{ item: "Architectural Gown", brand: "Brandon Maxwell" }, { item: "Custom Headpiece", brand: "Brandon Maxwell" }, { item: "Clear Platform Heel", brand: "Custom" }] },
      { name: "Oscars Glamour", pieces: [{ item: "Periwinkle Satin Ball Gown", brand: "Alexander McQueen" }, { item: "Diamond Jewelry", brand: "Tiffany & Co" }, { item: "Strappy Heel", brand: "Custom" }] },
      { name: "Joker Night", pieces: [{ item: "Purple Long-Sleeve Gown", brand: "Valentino" }, { item: "Statement Red Lip", brand: "Haus Labs" }, { item: "Metallic Stiletto", brand: "Louboutin" }] },
      { name: "VMA Meat Dress", pieces: [{ item: "Meat-Sculpted Gown", brand: "Franc Fernandez" }, { item: "Meat Platform Heel", brand: "Franc Fernandez" }, { item: "Meat Hat (Archive)", brand: "Franc Fernandez" }] },
      { name: "Street Gaga", pieces: [{ item: "Sequin Minidress", brand: "Versace" }, { item: "Oversize Shades", brand: "GCDS" }, { item: "Platform Sneaker", brand: "Versace" }] },
    ],
  },
  {
    id: "chloe",
    name: "Chloé Zhao",
    title: "Hollywood's Quiet Revolutionary",
    style: "Understated Nomadic",
    description: "The Oscar-winning director who wore jeans to the Academy Awards. Chloé's style is deliberate minimalism — the anti-Hollywood statement that said more than any couture gown.",
    image: PHOTOS.chloe,
    accentColor: "#8A9E8A",
    era: "2018–Present",
    knownFor: "Nomadic minimalism, jeans at the Oscars, quiet statement",
    signatureBrands: ["The Row", "Lemaire", "Toteme", "COS", "Acne Studios"],
    keyPieces: ["Relaxed denim", "Cashmere knit", "Simple leather boot", "Linen trouser", "Minimal jewellery"],
    vibes: ["Quiet Luxury", "Minimalism", "Nomadic"],
    looks: [
      { name: "Oscar Night Rebel", pieces: [{ item: "High-Rise Denim", brand: "Agolde" }, { item: "Cashmere Knit", brand: "The Row" }, { item: "Chelsea Boot", brand: "The Row" }] },
      { name: "Eternals Press", pieces: [{ item: "Wide-Leg Linen Trouser", brand: "Toteme" }, { item: "Silk Blouse", brand: "Equipment" }, { item: "Leather Mule", brand: "Lemaire" }] },
      { name: "Sundance Quiet", pieces: [{ item: "Camel Parka", brand: "Acne Studios" }, { item: "Slim Denim", brand: "Agolde" }, { item: "Suede Boot", brand: "The Row" }] },
      { name: "BAFTA Minimalist", pieces: [{ item: "Black Wide-Leg Trouser", brand: "The Row" }, { item: "Black Cashmere Turtleneck", brand: "The Row" }, { item: "Ballet Flat", brand: "The Row" }] },
      { name: "Nomadland Spirit", pieces: [{ item: "Indigo Chambray Shirt", brand: "Lemaire" }, { item: "Relaxed Canvas Trouser", brand: "Lemaire" }, { item: "Desert Boot", brand: "Clarks" }] },
      { name: "Cannes Nature", pieces: [{ item: "Linen Wrap Dress", brand: "Toteme" }, { item: "Flat Sandal", brand: "Birkenstock" }, { item: "Minimal Gold Ring", brand: "Sophie Buhai" }] },
      { name: "LA Producer", pieces: [{ item: "Tailored Blazer", brand: "COS" }, { item: "White Tee", brand: "Sunspel" }, { item: "Simple Sneaker", brand: "Common Projects" }] },
      { name: "Brooklyn Loft", pieces: [{ item: "Knit Cardigan", brand: "Acne Studios" }, { item: "Wide-Leg Trouser", brand: "Lemaire" }, { item: "Chelsea Boot", brand: "Acne Studios" }] },
      { name: "Festival Circuit", pieces: [{ item: "Shearling Jacket", brand: "Ganni" }, { item: "Slim Denim", brand: "A.P.C." }, { item: "Sneaker", brand: "Veja" }] },
      { name: "Academy Member", pieces: [{ item: "Ivory Silk Blouse", brand: "Tibi" }, { item: "High-Rise Trouser", brand: "Toteme" }, { item: "Pointed Flat", brand: "The Row" }] },
      { name: "Behind Camera", pieces: [{ item: "Field Jacket", brand: "Filson" }, { item: "Military Trouser", brand: "Acne Studios" }, { item: "Work Boot", brand: "Red Wing" }] },
      { name: "Golden Globe", pieces: [{ item: "Stone-Grey Wrap Coat", brand: "Lemaire" }, { item: "Slim Trouser", brand: "The Row" }, { item: "Ankle Boot", brand: "Acne Studios" }] },
    ],
  },
  {
    id: "asap",
    name: "A$AP Rocky",
    title: "Fashion's Crown Prince",
    style: "Luxury Art-world Streetwear",
    description: "He wore Raf Simons before anyone knew the name. Rocky became the rapper-as-fashion-editor archetype — his Met Gala quilted vest and avant-garde layering blurred fashion and art.",
    image: PHOTOS.asap,
    accentColor: "#9898A8",
    era: "2011–Present",
    knownFor: "Raf Simons OG, fashion week front-row king, art-world meets hip-hop",
    signatureBrands: ["Raf Simons", "Gucci", "Calvin Klein", "Rick Owens", "Dior Homme"],
    keyPieces: ["Printed scarf", "Quilted vest", "Chunky brogues", "Kilt / wrap skirt", "Layered chains"],
    vibes: ["Luxury Streetwear", "Art World", "Avant-garde"],
    looks: [
      { name: "Raf Era", pieces: [{ item: "Printed Knit Sweater", brand: "Raf Simons" }, { item: "Slim Denim", brand: "Raf Simons" }, { item: "Chunky Brogue", brand: "Raf Simons" }] },
      { name: "Gucci Head", pieces: [{ item: "Print Silk Shirt", brand: "Gucci" }, { item: "Vintage Denim", brand: "Levi's Vintage" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
      { name: "Dior Homme", pieces: [{ item: "Fitted Suit", brand: "Dior Homme" }, { item: "Slim Tie", brand: "Dior" }, { item: "Oxford Shoe", brand: "Dior" }] },
      { name: "Calvin Klein", pieces: [{ item: "Minimalist White Tee", brand: "Calvin Klein" }, { item: "Slim Denim", brand: "Calvin Klein" }, { item: "White Sneaker", brand: "Calvin Klein" }] },
      { name: "Met Gala Quilt", pieces: [{ item: "Quilted Patchwork Vest", brand: "Custom" }, { item: "Slim Trouser", brand: "Prada" }, { item: "Chelsea Boot", brand: "Raf Simons" }] },
      { name: "Flower Boy", pieces: [{ item: "Floral Shirt", brand: "Gucci" }, { item: "Wide-Leg Cream Trouser", brand: "Prada" }, { item: "Chunky Sandal", brand: "Marni" }] },
      { name: "Art Basel Miami", pieces: [{ item: "Graphic Tee", brand: "Supreme x CDG" }, { item: "Layered Gold Chain", brand: "Custom" }, { item: "Baggy Trouser", brand: "ERL" }] },
      { name: "Harlem Prep", pieces: [{ item: "Navy Blazer", brand: "Ralph Lauren" }, { item: "Plaid Shirt", brand: "Ralph Lauren" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
      { name: "Fashion Forward", pieces: [{ item: "Deconstructed Jacket", brand: "Maison Margiela" }, { item: "Layered Kilt", brand: "Vivienne Westwood" }, { item: "Boot", brand: "Margiela" }] },
      { name: "Rick World", pieces: [{ item: "Long Leather Coat", brand: "Rick Owens" }, { item: "Black Turtleneck", brand: "Rick Owens" }, { item: "DRKSHDW Sneaker", brand: "Rick Owens" }] },
      { name: "Brooklyn Finest", pieces: [{ item: "Stone Island Jacket", brand: "Stone Island" }, { item: "Cargo Trouser", brand: "Maharishi" }, { item: "Retro Sneaker", brand: "New Balance" }] },
      { name: "Fenty Flame", pieces: [{ item: "Leather Jacket", brand: "Amiri" }, { item: "Slim Denim", brand: "Amiri" }, { item: "Leather Sneaker", brand: "Amiri" }] },
    ],
  },
  {
    id: "lewis",
    name: "Lewis Hamilton",
    title: "Formula One's Fashion Rebel",
    style: "Race-day Luxury",
    description: "Lewis broke F1's stuffy dress code and never looked back. Custom Tommy Hilfiger, Burberry editorial shoots, and front-row fashion week appearances made him the sport's first true fashion icon.",
    image: PHOTOS.lewis,
    accentColor: "#9898A8",
    era: "2009–Present",
    knownFor: "Tommy Hilfiger collab, Burberry, Valentino, fashion week regular",
    signatureBrands: ["Tommy Hilfiger x Lewis", "Valentino", "Burberry", "Mercedes-AMG gear", "Chrome Hearts"],
    keyPieces: ["Custom race suit", "Chrome Hearts sunglasses", "Statement coat", "Custom sneakers", "Gold chain"],
    vibes: ["Race-day Luxe", "Power Dressing", "Street Couture"],
    looks: [
      { name: "Paddock Ready", pieces: [{ item: "Custom Embroidered Jacket", brand: "Tommy x Lewis" }, { item: "Wide-leg Cargo", brand: "Valentino" }, { item: "Platform Sneaker", brand: "Valentino" }] },
      { name: "Fashion Week Front Row", pieces: [{ item: "Statement Fur Coat", brand: "Burberry" }, { item: "Leather Trouser", brand: "Valentino" }, { item: "Chrome Hearts Sunglasses", brand: "Chrome Hearts" }] },
      { name: "Monaco Pit", pieces: [{ item: "Custom F1 Race Suit", brand: "Mercedes-AMG Petronas" }, { item: "Chrome Hearts Helmet Wrap", brand: "Chrome Hearts" }, { item: "Racing Boot", brand: "Puma" }] },
      { name: "Valentino Red", pieces: [{ item: "Red Suit", brand: "Valentino" }, { item: "Black Poloneck", brand: "Valentino" }, { item: "Garavani Sneaker", brand: "Valentino" }] },
      { name: "Tokyo Fashion", pieces: [{ item: "Patchwork Jacket", brand: "NIGO x LV" }, { item: "Wide Trouser", brand: "Sacai" }, { item: "High-Top Sneaker", brand: "Nike x Sacai" }] },
      { name: "F1 Media Day", pieces: [{ item: "Gold Embroidered Jacket", brand: "Tom Ford" }, { item: "Black Trouser", brand: "Tom Ford" }, { item: "Chelsea Boot", brand: "Tom Ford" }] },
      { name: "Hollywood Hills", pieces: [{ item: "Relaxed Blazer", brand: "Saint Laurent" }, { item: "White Shirt", brand: "Sunspel" }, { item: "Loafer", brand: "Berluti" }] },
      { name: "Burberry Campaign", pieces: [{ item: "Heritage Trench", brand: "Burberry" }, { item: "Slim Denim", brand: "Acne Studios" }, { item: "Chelsea Boot", brand: "Burberry" }] },
      { name: "Grammy Scene", pieces: [{ item: "Metallic Silver Suit", brand: "Valentino" }, { item: "Black Turtleneck", brand: "Prada" }, { item: "Platform Shoe", brand: "Valentino" }] },
      { name: "London Season", pieces: [{ item: "Tailored Overcoat", brand: "Alexander McQueen" }, { item: "Roll-Neck Knit", brand: "Raf Simons" }, { item: "Oxford", brand: "Berluti" }] },
      { name: "Spa Weekend", pieces: [{ item: "Cashmere Jogger", brand: "Loro Piana" }, { item: "Logo Tee", brand: "Chrome Hearts" }, { item: "Runner", brand: "New Balance" }] },
      { name: "Victory Podium", pieces: [{ item: "Custom Team Jacket", brand: "Mercedes Custom" }, { item: "Champion Shorts", brand: "Mercedes Custom" }, { item: "Race Boot", brand: "Puma" }] },
    ],
  },
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    title: "The NBA's Most Original Dresser",
    style: "Unique NBA Editorial",
    description: "SGA doesn't follow trends — he sets them. Quiet luxury, unique Japanese brands, odd-ratio silhouettes, and editorial styling that belongs in a magazine, not just a locker room.",
    image: PHOTOS.sga,
    accentColor: "#8E9EAB",
    era: "2020–Present",
    knownFor: "Arena tunnel fits, editorial styling, quiet luxury NBA",
    signatureBrands: ["The Row", "Toteme", "Comme des Garçons", "Yohji Yamamoto", "New Balance"],
    keyPieces: ["Oversized trench coat", "Relaxed wide-leg trousers", "Plain white tee", "Minimalist sneaker", "Stack of rings"],
    vibes: ["Quiet Luxury", "NBA Tunnel", "Editorial Minimal"],
    looks: [
      { name: "Tunnel Walk", pieces: [{ item: "Oversized Trench", brand: "The Row" }, { item: "Wide-Leg Trouser", brand: "Toteme" }, { item: "Minimalist Sneaker", brand: "New Balance" }] },
      { name: "OKC Quiet", pieces: [{ item: "CDG Knit Polo", brand: "Comme des Garçons" }, { item: "Relaxed Trouser", brand: "Yohji Yamamoto" }, { item: "Simple Loafer", brand: "Lemaire" }] },
      { name: "Pre-Game Quiet", pieces: [{ item: "Oversized Knit Coat", brand: "Comme des Garçons" }, { item: "Wide Linen Trouser", brand: "Lemaire" }, { item: "Derby Shoe", brand: "Common Projects" }] },
      { name: "Media Day", pieces: [{ item: "Structured Blazer", brand: "The Row" }, { item: "Black Turtleneck", brand: "The Row" }, { item: "Chelsea Boot", brand: "The Row" }] },
      { name: "Japanese Edit", pieces: [{ item: "Deconstructed Suit", brand: "Yohji Yamamoto" }, { item: "Asymmetric Shirt", brand: "Issey Miyake" }, { item: "Clean Sneaker", brand: "New Balance" }] },
      { name: "OKC Royalty", pieces: [{ item: "Thunder-Blue Suit", brand: "Brioni Custom" }, { item: "White Dress Shirt", brand: "Charvet" }, { item: "Oxford", brand: "Berluti" }] },
      { name: "Off-Day Chill", pieces: [{ item: "Relaxed Linen Set", brand: "Lemaire" }, { item: "Simple Tee", brand: "Sunspel" }, { item: "Minimalist Sneaker", brand: "Veja" }] },
      { name: "All-Star Weekend", pieces: [{ item: "Velvet Blazer", brand: "Loro Piana" }, { item: "Slim Trouser", brand: "Toteme" }, { item: "Platform Loafer", brand: "Marni" }] },
      { name: "Travel Day", pieces: [{ item: "Camel Cashmere Overcoat", brand: "The Row" }, { item: "Wide Cropped Trouser", brand: "Toteme" }, { item: "Sock Boot", brand: "Common Projects" }] },
      { name: "Archive Dig", pieces: [{ item: "Vintage Cargo Trouser", brand: "Helmut Lang Archive" }, { item: "Graphic Tee", brand: "Comme des Garçons" }, { item: "Archive Sneaker", brand: "New Balance" }] },
      { name: "Silent Statement", pieces: [{ item: "All-White Linen Suit", brand: "The Row" }, { item: "White Sneaker", brand: "Common Projects" }, { item: "Minimal Ring Stack", brand: "Tom Wood" }] },
      { name: "Tunnel Vision", pieces: [{ item: "Asymmetric Coat", brand: "Issey Miyake Pleats" }, { item: "Wide Trouser", brand: "Yohji Yamamoto" }, { item: "Avant-Garde Sneaker", brand: "Salehe x New Balance" }] },
    ],
  },
  {
    id: "nas",
    name: "Nas",
    title: "Queens Bridge's Eternal Style King",
    style: "Classic New York",
    description: "Nas dressed like money before money talked the way it does now. Timeless NY — Timberlands, leather bubble coats, and just enough gold. He proved that classic never ages.",
    image: PHOTOS.nas,
    accentColor: "#B8A888",
    era: "1994–Present",
    knownFor: "Timberlands, classic NY hip-hop, bubble coat era",
    signatureBrands: ["Timberland", "Phat Farm", "Ralph Lauren", "Hermès", "Tom Ford"],
    keyPieces: ["Timberland boot", "Bubble goose coat", "Gold chains", "Fitted baseball cap", "Luxury watch"],
    vibes: ["NY Classic", "Old School Hip-hop", "Quiet Luxury"],
    looks: [
      { name: "Illmatic Era", pieces: [{ item: "Bubble Goose Coat", brand: "Northface" }, { item: "Timberland 6-Inch Boot", brand: "Timberland" }, { item: "Fitted Cap", brand: "New Era" }] },
      { name: "Kings Disease", pieces: [{ item: "Tom Ford Suit", brand: "Tom Ford" }, { item: "Hermès Belt", brand: "Hermès" }, { item: "Oxford Boot", brand: "Berluti" }] },
      { name: "QB Finest", pieces: [{ item: "Coogi Sweater", brand: "Coogi" }, { item: "Dark Denim", brand: "Polo Jeans" }, { item: "Air Jordan 3", brand: "Nike" }] },
      { name: "It Was Written", pieces: [{ item: "Leather Jacket", brand: "Custom" }, { item: "Gold Rope Chain", brand: "Jacob & Co" }, { item: "Timberland Boot", brand: "Timberland" }] },
      { name: "Street's Disciple", pieces: [{ item: "Linen Suit", brand: "Custom" }, { item: "Cuban Link Chain", brand: "Jacob & Co" }, { item: "Gucci Loafer", brand: "Gucci" }] },
      { name: "Nas x Harvard", pieces: [{ item: "Navy Blazer", brand: "Ralph Lauren" }, { item: "Oxford Shirt", brand: "Polo Ralph Lauren" }, { item: "Oxford Brogue", brand: "Allen Edmonds" }] },
      { name: "Stillmatic Season", pieces: [{ item: "Sheepskin Coat", brand: "Custom" }, { item: "Ski Goggles", brand: "Oakley" }, { item: "Timberland Boot", brand: "Timberland" }] },
      { name: "NY State of Mind", pieces: [{ item: "Polo Down Jacket", brand: "Ralph Lauren" }, { item: "Fitted Cap", brand: "New Era" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Queens King", pieces: [{ item: "Zegna Suit", brand: "Zegna" }, { item: "Hermès Tie", brand: "Hermès" }, { item: "Patent Loafer", brand: "Gucci" }] },
      { name: "Life Is Good", pieces: [{ item: "Camp Collar Shirt", brand: "Loro Piana" }, { item: "Linen Trouser", brand: "Loro Piana" }, { item: "Canvas Sneaker", brand: "Rivieras" }] },
      { name: "Bourbon & Verse", pieces: [{ item: "Cashmere Turtleneck", brand: "Brunello Cucinelli" }, { item: "Slim Dark Trouser", brand: "Tom Ford" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Vintage Nas", pieces: [{ item: "Starter Jacket", brand: "Starter" }, { item: "Classic Denim", brand: "Levi's 501" }, { item: "Air Max 95", brand: "Nike" }] },
    ],
  },
  {
    id: "kim",
    name: "Kim Kardashian",
    title: "The Sculptural Mogul",
    style: "Sculptural Minimalism",
    description: "From Balenciaga muse to SKIMS billionaire — Kim turned shapewear into an empire and the red carpet into sculpture. Nude tones, second-skin silhouettes, and couture moments engineered down to the millimeter.",
    image: PHOTOS.kim,
    accentColor: "#B8A99A",
    era: "2007–Present",
    knownFor: "SKIMS, Balenciaga, Met Gala sculpture",
    signatureBrands: ["SKIMS", "Balenciaga", "Mugler", "Dolce & Gabbana", "The Row"],
    keyPieces: ["Second-skin bodysuit", "Sculptural corset gown", "Tonal sunglasses", "Square-toe mule", "Bandage dress"],
    vibes: ["Sculptural Minimal", "Power Dressing", "Avant-garde"],
    looks: [
      { name: "Met Gala Mugler", pieces: [{ item: "Crystal Mesh Gown", brand: "Mugler" }, { item: "Opera Glove", brand: "Wing & Weft" }, { item: "Crystal Sandal", brand: "Mugler" }] },
      { name: "Balenciaga Muse", pieces: [{ item: "Hooded Catsuit", brand: "Balenciaga" }, { item: "Knife Boot", brand: "Balenciaga" }, { item: "Tonal Sunglasses", brand: "Balenciaga" }] },
      { name: "SKIMS Mogul", pieces: [{ item: "Second-Skin Bodysuit", brand: "SKIMS" }, { item: "Tailored Trouser", brand: "The Row" }, { item: "Pointed Pump", brand: "Manolo Blahnik" }] },
      { name: "Monochrome Nude", pieces: [{ item: "Bandage Midi Dress", brand: "Balmain" }, { item: "Camel Trench", brand: "Max Mara" }, { item: "Square-Toe Mule", brand: "The Row" }] },
      { name: "Paris Couture", pieces: [{ item: "Sculptural Corset Gown", brand: "Schiaparelli" }, { item: "Statement Earring", brand: "Lorraine Schwartz" }, { item: "Stiletto", brand: "Christian Louboutin" }] },
      { name: "Off-Duty Mogul", pieces: [{ item: "Compression Catsuit", brand: "SKIMS" }, { item: "Oversized Blazer", brand: "Balenciaga" }, { item: "Heeled Boot", brand: "Bottega Veneta" }] },
      { name: "Wyoming Calm", pieces: [{ item: "Cashmere Knit", brand: "The Row" }, { item: "Wide-Leg Trouser", brand: "Khaite" }, { item: "Leather Mule", brand: "Bottega Veneta" }] },
      { name: "Carpet Siren", pieces: [{ item: "Liquid Silver Gown", brand: "Atelier Versace" }, { item: "Diamond Choker", brand: "Messika" }, { item: "Metallic Heel", brand: "Gianvito Rossi" }] },
      { name: "Latex Hour", pieces: [{ item: "Latex Midi Dress", brand: "Maison Margiela" }, { item: "Long Glove", brand: "Wing & Weft" }, { item: "Strappy Pump", brand: "Femme LA" }] },
      { name: "Power Lunch", pieces: [{ item: "Tonal Suit", brand: "Dolce & Gabbana" }, { item: "Silk Camisole", brand: "La Perla" }, { item: "Slingback", brand: "Prada" }] },
      { name: "Vegas Lights", pieces: [{ item: "Crystal Fringe Mini", brand: "David Koma" }, { item: "Diamond Cuff", brand: "Cartier" }, { item: "Ankle-Strap Heel", brand: "Amina Muaddi" }] },
      { name: "Champagne Siren", pieces: [{ item: "Beaded Column Gown", brand: "Jean Louis Archive" }, { item: "Crystal Drop Earring", brand: "Lorraine Schwartz" }, { item: "Strappy Sandal", brand: "Gianvito Rossi" }] },
    ],
  },
  {
    id: "maryjblige",
    name: "Mary J. Blige",
    title: "Queen of Hip-Hop Soul",
    style: "Hip-Hop Soul Glamour",
    description: "The Queen of Hip-Hop Soul who fused uptown glamour with street grit. Thigh-high boots, blonde waves, and oversized shades — Mary J. Blige made survival look like couture.",
    image: PHOTOS.maryjblige,
    accentColor: "#7E5A9B",
    era: "1992–Present",
    knownFor: "Thigh-high boots, shades, soul glamour",
    signatureBrands: ["Versace", "Roberto Cavalli", "Dolce & Gabbana", "Saint Laurent", "Gucci"],
    keyPieces: ["Thigh-high boots", "Oversized sunglasses", "Sequin gown", "Fur coat", "Bodysuit"],
    vibes: ["Glamour", "Power Dressing", "Luxury Streetwear"],
    looks: [
      { name: "Queen of Hip-Hop Soul", pieces: [{ item: "Embellished Gown", brand: "Versace" }, { item: "Oversized Sunglasses", brand: "Versace" }, { item: "Thigh-High Boot", brand: "Versace" }] },
      { name: "Strength of a Woman", pieces: [{ item: "Sequin Blazer", brand: "Saint Laurent" }, { item: "Bodysuit", brand: "Wolford" }, { item: "Thigh-High Boot", brand: "Stuart Weitzman" }] },
      { name: "BET Honors", pieces: [{ item: "Beaded Gown", brand: "Roberto Cavalli" }, { item: "Statement Earring", brand: "Chopard" }, { item: "Strappy Sandal", brand: "Jimmy Choo" }] },
      { name: "Uptown Glam", pieces: [{ item: "Leather Trench", brand: "Gucci" }, { item: "Turtleneck Bodysuit", brand: "Wolford" }, { item: "Knee Boot", brand: "Gianvito Rossi" }] },
      { name: "No More Drama", pieces: [{ item: "Fur Coat", brand: "Dennis Basso" }, { item: "Slip Dress", brand: "Galvan" }, { item: "Pointed Pump", brand: "Christian Louboutin" }] },
      { name: "Real Love", pieces: [{ item: "Denim Jacket", brand: "Roberto Cavalli" }, { item: "Silk Tank", brand: "La Perla" }, { item: "Platform Sandal", brand: "Versace" }] },
      { name: "Grammy Night", pieces: [{ item: "Liquid Gold Gown", brand: "Atelier Versace" }, { item: "Diamond Cuff", brand: "Cartier" }, { item: "Metallic Heel", brand: "Jimmy Choo" }] },
      { name: "Soul Soiree", pieces: [{ item: "Tailored Pantsuit", brand: "Dolce & Gabbana" }, { item: "Silk Blouse", brand: "Tom Ford" }, { item: "Patent Pump", brand: "Saint Laurent" }] },
      { name: "Family Affair", pieces: [{ item: "Sequin Mini Dress", brand: "Balmain" }, { item: "Hoop Earring", brand: "Jennifer Fisher" }, { item: "Strappy Heel", brand: "Aquazzura" }] },
      { name: "Hollywood Premiere", pieces: [{ item: "Velvet Cape Gown", brand: "Elie Saab" }, { item: "Crystal Clutch", brand: "Judith Leiber" }, { item: "Stiletto", brand: "Stuart Weitzman" }] },
      { name: "Just Fine", pieces: [{ item: "Cropped Leather Jacket", brand: "Saint Laurent" }, { item: "Wide-Leg Trouser", brand: "The Row" }, { item: "Block-Heel Boot", brand: "Bottega Veneta" }] },
      { name: "Diva Carpet", pieces: [{ item: "Plunging Column Gown", brand: "Roberto Cavalli" }, { item: "Statement Necklace", brand: "Bulgari" }, { item: "Ankle-Strap Sandal", brand: "Giuseppe Zanotti" }] },
    ],
  },
  {
    id: "taylor",
    name: "Taylor Swift",
    title: "The Era-Defining Style Chameleon",
    style: "Romantic Reinvention",
    description: "Every album is a new wardrobe. From cottagecore knits to sequinned Eras Tour bodysuits, Taylor rebuilds her aesthetic era by era — vintage-inspired dresses, sharp tailoring, and glitter that reads as narrative, not decoration.",
    image: PHOTOS.taylor,
    accentColor: "#C9B8D8",
    era: "2006–Present",
    knownFor: "The Eras Tour, red-carpet reinvention, vintage romance",
    signatureBrands: ["Reformation", "Oscar de la Renta", "Roberto Cavalli", "Christian Louboutin", "Etro"],
    keyPieces: ["Sequinned bodysuit", "Vintage tea dress", "High-waist short suit", "Cardigan knit", "Red lip statement heel"],
    vibes: ["Romantic", "Vintage Glamour", "Sparkle"],
    looks: [
      { name: "Eras Opening", pieces: [{ item: "Crystal Fringe Bodysuit", brand: "Roberto Cavalli" }, { item: "Fishnet Tight", brand: "Wolford" }, { item: "Sparkle Ankle Boot", brand: "Christian Louboutin" }] },
      { name: "Lover House", pieces: [{ item: "Pastel Sequin Blazer", brand: "Etro" }, { item: "High-Waist Short", brand: "Zimmermann" }, { item: "Platform Sandal", brand: "Aquazzura" }] },
      { name: "Folklore Cottage", pieces: [{ item: "Chunky Cable Cardigan", brand: "Reformation" }, { item: "Prairie Midi Dress", brand: "Doen" }, { item: "Suede Ankle Boot", brand: "Isabel Marant" }] },
      { name: "Red Scarf", pieces: [{ item: "Wool Overcoat", brand: "Max Mara" }, { item: "Fair Isle Knit", brand: "Ralph Lauren" }, { item: "Riding Boot", brand: "Stuart Weitzman" }] },
      { name: "Midnights Muse", pieces: [{ item: "Midnight-Blue Slip Gown", brand: "Oscar de la Renta" }, { item: "Crystal Drop Earring", brand: "Lorraine Schwartz" }, { item: "Satin Stiletto", brand: "Jimmy Choo" }] },
      { name: "1989 Polaroid", pieces: [{ item: "Crop Top & Skirt Set", brand: "Reformation" }, { item: "Structured Mini Skirt", brand: "Self-Portrait" }, { item: "Pointed Pump", brand: "Manolo Blahnik" }] },
      { name: "Reputation Noir", pieces: [{ item: "Black Sequin Bodysuit", brand: "Balmain" }, { item: "Sheer Tight", brand: "Falke" }, { item: "Thigh-High Boot", brand: "Christian Louboutin" }] },
      { name: "Grammy Romance", pieces: [{ item: "Floral Column Gown", brand: "Oscar de la Renta" }, { item: "Statement Earring", brand: "Ana Khouri" }, { item: "Crystal Sandal", brand: "Aquazzura" }] },
      { name: "Speak Now Violet", pieces: [{ item: "Lilac Tulle Gown", brand: "Etro" }, { item: "Opera Glove", brand: "Fownes" }, { item: "Embellished Heel", brand: "René Caovilla" }] },
      { name: "City Off-Duty", pieces: [{ item: "Cropped Tweed Jacket", brand: "Sandro" }, { item: "High-Waist Trouser", brand: "Toteme" }, { item: "Kitten-Heel Pump", brand: "The Row" }] },
      { name: "Evermore Woods", pieces: [{ item: "Plaid Wool Cape", brand: "Burberry" }, { item: "Ribbed Turtleneck", brand: "Reformation" }, { item: "Lace-Up Boot", brand: "Isabel Marant" }] },
      { name: "Red Carpet Sparkle", pieces: [{ item: "Sequin Mini Dress", brand: "Zuhair Murad" }, { item: "Crystal Clutch", brand: "Judith Leiber" }, { item: "Ankle-Strap Sandal", brand: "Christian Louboutin" }] },
    ],
  },
  {
    id: "cardi-b",
    name: "Cardi B",
    title: "The Couture Showstopper",
    style: "Maximalist Couture",
    description: "Cardi B treats every entrance like a headline. Her story runs from Bronx street style to archival couture, pairing fearless color, sculptural silhouettes, and major jewelry with a sense of humor that makes high fashion feel alive.",
    image: PHOTOS.cardiB,
    accentColor: "#D84A63",
    era: "2017–Present",
    knownFor: "Archival couture, dramatic silhouettes, fearless red-carpet reveals",
    signatureBrands: ["Mugler", "Schiaparelli", "Richard Quinn", "Balenciaga", "Christian Louboutin"],
    keyPieces: ["Sculptural couture gown", "Opera glove", "Crystal catsuit", "Statement headpiece", "Platform pump"],
    vibes: ["Maximalist", "Couture Drama", "Power Glamour"],
    looks: [
      { name: "Couture Entrance", pieces: [{ item: "Sculptural Gown", brand: "Schiaparelli" }, { item: "Opera Glove", brand: "Cornelia James" }, { item: "Platform Pump", brand: "Christian Louboutin" }] },
      { name: "Bronx to Paris", pieces: [{ item: "Feathered Coat", brand: "Richard Quinn" }, { item: "Crystal Bodysuit", brand: "Mugler" }, { item: "Satin Stiletto", brand: "Amina Muaddi" }] },
      { name: "Red Carpet Armor", pieces: [{ item: "Metallic Corset Gown", brand: "Gaurav Gupta" }, { item: "Diamond Cuff", brand: "Messika" }, { item: "Embellished Sandal", brand: "Jimmy Choo" }] },
      { name: "Front Row Flash", pieces: [{ item: "Oversized Faux-Fur Coat", brand: "Balenciaga" }, { item: "Second-Skin Dress", brand: "Mugler" }, { item: "Knife Boot", brand: "Balenciaga" }] },
    ],
  },
  {
    id: "kate-hudson",
    name: "Kate Hudson",
    title: "The Golden California Free Spirit",
    style: "Bohemian Red-Carpet Ease",
    description: "Kate Hudson blends sunlit California ease with polished Hollywood glamour. Fluid dresses, warm metallics, playful tailoring, and relaxed resort pieces keep her style optimistic, feminine, and effortlessly event-ready.",
    image: PHOTOS.kateHudson,
    accentColor: "#D7B56D",
    era: "2000s–Present",
    knownFor: "Golden gowns, relaxed bohemian dresses, modern Hollywood glamour",
    signatureBrands: ["Michael Kors", "Valentino", "Versace", "Stella McCartney", "Jimmy Choo"],
    keyPieces: ["Liquid-metallic gown", "Bohemian maxi dress", "White trouser suit", "Silk camisole", "Strappy sandal"],
    vibes: ["California Glamour", "Bohemian", "Effortless"],
    looks: [
      { name: "Golden Hour Gala", pieces: [{ item: "Metallic Column Gown", brand: "Michael Kors" }, { item: "Diamond Drop Earring", brand: "Bulgari" }, { item: "Strappy Sandal", brand: "Jimmy Choo" }] },
      { name: "Malibu Weekend", pieces: [{ item: "Printed Maxi Dress", brand: "Zimmermann" }, { item: "Woven Tote", brand: "Loewe" }, { item: "Leather Slide", brand: "Khaite" }] },
      { name: "Studio Premiere", pieces: [{ item: "White Tuxedo Blazer", brand: "Stella McCartney" }, { item: "Silk Camisole", brand: "Nili Lotan" }, { item: "Wide-Leg Trouser", brand: "Stella McCartney" }] },
      { name: "Festival Romance", pieces: [{ item: "Embroidered Blouse", brand: "Chloé" }, { item: "Fluid Midi Skirt", brand: "Ulla Johnson" }, { item: "Suede Ankle Boot", brand: "Isabel Marant" }] },
    ],
  },
  {
    id: "keke-palmer",
    name: "Keke Palmer",
    title: "The Joyful Fashion Chameleon",
    style: "Playful Power Dressing",
    description: "Keke Palmer moves between sharp tailoring, bright monochrome, old-Hollywood gowns, and directional streetwear with total confidence. Her style story is rooted in performance: expressive, polished, and never afraid of color.",
    image: PHOTOS.kekePalmer,
    accentColor: "#C85B9B",
    era: "2004–Present",
    knownFor: "Bold color, sculpted tailoring, glamorous press-tour fashion",
    signatureBrands: ["Sergio Hudson", "Marc Jacobs", "Robert Wun", "Valentino", "Christian Louboutin"],
    keyPieces: ["Color-block suit", "Corseted gown", "Platform heel", "Sculpted blazer", "Statement earring"],
    vibes: ["Joyful Glamour", "Power Dressing", "Fashion Chameleon"],
    looks: [
      { name: "Press Tour Power", pieces: [{ item: "Sculpted Blazer", brand: "Sergio Hudson" }, { item: "High-Waist Trouser", brand: "Sergio Hudson" }, { item: "Patent Pump", brand: "Christian Louboutin" }] },
      { name: "Premiere Drama", pieces: [{ item: "Corseted Column Gown", brand: "Robert Wun" }, { item: "Diamond Earring", brand: "Bulgari" }, { item: "Satin Sandal", brand: "Aquazzura" }] },
      { name: "Color Story", pieces: [{ item: "Vivid Mini Dress", brand: "Valentino" }, { item: "Sculptural Clutch", brand: "Cult Gaia" }, { item: "Platform Pump", brand: "Marc Jacobs" }] },
      { name: "Downtown Keke", pieces: [{ item: "Cropped Leather Jacket", brand: "Khaite" }, { item: "Wide-Leg Denim", brand: "The Attico" }, { item: "Retro Sneaker", brand: "New Balance" }] },
    ],
  },
  {
    id: "katy-perry",
    name: "Katy Perry",
    title: "The Pop-Surrealist Showgirl",
    style: "Playful Pop Couture",
    description: "Katy Perry turns pop fantasy into wearable theater. Candy-colored couture, retro pin-up shapes, surreal accessories, and sleek futuristic gowns chart a style story built on spectacle and constant reinvention.",
    image: PHOTOS.katyPerry,
    accentColor: "#E76F9D",
    era: "2008–Present",
    knownFor: "Camp couture, pin-up silhouettes, futuristic stage fashion",
    signatureBrands: ["Moschino", "Schiaparelli", "Vivienne Westwood", "Balenciaga", "Giuseppe Zanotti"],
    keyPieces: ["Corseted mini dress", "Sculptural gown", "Novelty accessory", "Latex column dress", "Platform heel"],
    vibes: ["Pop Art", "Camp", "Retro Futurism"],
    looks: [
      { name: "Candy Couture", pieces: [{ item: "Sculpted Mini Dress", brand: "Moschino" }, { item: "Novelty Clutch", brand: "Judith Leiber" }, { item: "Platform Pump", brand: "Giuseppe Zanotti" }] },
      { name: "Space-Age Pop", pieces: [{ item: "Metallic Column Gown", brand: "Balenciaga" }, { item: "Sculptural Earring", brand: "Schiaparelli" }, { item: "Chrome Sandal", brand: "Jimmy Choo" }] },
      { name: "Pin-Up Revival", pieces: [{ item: "Corseted Midi Dress", brand: "Vivienne Westwood" }, { item: "Top-Handle Bag", brand: "Dolce & Gabbana" }, { item: "Patent Pump", brand: "Christian Louboutin" }] },
      { name: "Pop Star Noir", pieces: [{ item: "Draped Black Gown", brand: "Rick Owens" }, { item: "Gold Statement Cuff", brand: "Schiaparelli" }, { item: "Sharp-Toe Boot", brand: "Saint Laurent" }] },
    ],
  },
  {
    id: "kylie-jenner",
    name: "Kylie Jenner",
    title: "The Modern Beauty Mogul",
    style: "Body-Con Minimalism",
    description: "Kylie Jenner's fashion story grew from high-impact social style into a refined mix of second-skin dresses, oversized leather, precise neutrals, and vintage couture. The result is controlled glamour with a sharp editorial edge.",
    image: PHOTOS.kylieJenner,
    accentColor: "#B89A91",
    era: "2014–Present",
    knownFor: "Sculpted silhouettes, neutral palettes, vintage couture moments",
    signatureBrands: ["Alaïa", "Schiaparelli", "Mugler", "Jean Paul Gaultier", "The Row"],
    keyPieces: ["Second-skin midi dress", "Oversized leather coat", "Sculptural heel", "Micro bag", "Vintage couture gown"],
    vibes: ["Controlled Glamour", "Body-Con", "Modern Minimal"],
    looks: [
      { name: "Beauty Mogul", pieces: [{ item: "Second-Skin Midi Dress", brand: "Alaïa" }, { item: "Micro Top-Handle Bag", brand: "Hermès" }, { item: "Sculptural Pump", brand: "Amina Muaddi" }] },
      { name: "Paris After Dark", pieces: [{ item: "Oversized Leather Coat", brand: "The Row" }, { item: "Sheer Column Dress", brand: "Mugler" }, { item: "Sharp-Toe Boot", brand: "Saint Laurent" }] },
      { name: "Couture Archive", pieces: [{ item: "Vintage Corset Gown", brand: "Jean Paul Gaultier" }, { item: "Gold Drop Earring", brand: "Schiaparelli" }, { item: "Satin Sandal", brand: "Manolo Blahnik" }] },
      { name: "Quiet Neutral", pieces: [{ item: "Cashmere Coat", brand: "Khaite" }, { item: "Ribbed Knit Dress", brand: "Toteme" }, { item: "Minimal Mule", brand: "The Row" }] },
    ],
  },
  {
    id: "dakota-johnson",
    name: "Dakota Johnson",
    title: "The Understated Indie Muse",
    style: "Bohemian Minimalism",
    description: "Dakota Johnson makes quiet dressing memorable through impeccable proportion: fluid tailoring, sheer evening gowns, soft suede, vintage denim, and a signature fringe. Her style feels intelligent, sensual, and deliberately unforced.",
    image: PHOTOS.dakotaJohnson,
    accentColor: "#708C82",
    era: "2010s–Present",
    knownFor: "Gucci gowns, relaxed tailoring, polished bohemian off-duty style",
    signatureBrands: ["Gucci", "Khaite", "The Row", "Bottega Veneta", "Saint Laurent"],
    keyPieces: ["Sheer embellished gown", "Relaxed blazer", "Straight-leg denim", "Suede loafer", "Minimal shoulder bag"],
    vibes: ["Indie Muse", "Bohemian Minimal", "Quiet Sensuality"],
    looks: [
      { name: "Gucci Premiere", pieces: [{ item: "Sheer Embellished Gown", brand: "Gucci" }, { item: "Diamond Drop Earring", brand: "Bulgari" }, { item: "Velvet Sandal", brand: "Gucci" }] },
      { name: "SoHo Off-Duty", pieces: [{ item: "Relaxed Blazer", brand: "Khaite" }, { item: "Straight-Leg Denim", brand: "Citizens of Humanity" }, { item: "Suede Loafer", brand: "Bottega Veneta" }] },
      { name: "Indie Screening", pieces: [{ item: "Silk Slip Dress", brand: "The Row" }, { item: "Leather Shoulder Bag", brand: "Gucci" }, { item: "Kitten-Heel Mule", brand: "Toteme" }] },
      { name: "Autumn Bookshop", pieces: [{ item: "Suede Trench Coat", brand: "Saint Laurent" }, { item: "Fine-Knit Turtleneck", brand: "Khaite" }, { item: "Tailored Trouser", brand: "The Row" }] },
    ],
  },
  {
    id: "mila-kunis",
    name: "Mila Kunis",
    title: "The Effortless Hollywood Minimalist",
    style: "Relaxed Modern Glamour",
    description: "Mila Kunis keeps glamour grounded. She favors clean black tailoring, jewel-toned gowns, polished knits, and understated accessories, creating a wardrobe that moves naturally from low-key Los Angeles days to the red carpet.",
    image: PHOTOS.milaKunis,
    accentColor: "#7B6A8E",
    era: "1998–Present",
    knownFor: "Jewel-tone gowns, clean tailoring, relaxed Los Angeles basics",
    signatureBrands: ["Carolina Herrera", "Atelier Versace", "Brunello Cucinelli", "Christian Dior", "Jimmy Choo"],
    keyPieces: ["Jewel-tone gown", "Black trouser suit", "Cashmere crewneck", "Straight-leg jean", "Classic pump"],
    vibes: ["Effortless", "Modern Classic", "Low-Key Glamour"],
    looks: [
      { name: "Jewel-Tone Premiere", pieces: [{ item: "Emerald Column Gown", brand: "Atelier Versace" }, { item: "Diamond Stud", brand: "Cartier" }, { item: "Satin Sandal", brand: "Jimmy Choo" }] },
      { name: "Hollywood Minimal", pieces: [{ item: "Black Tuxedo Blazer", brand: "Christian Dior" }, { item: "Silk Camisole", brand: "Nili Lotan" }, { item: "Tailored Trouser", brand: "The Row" }] },
      { name: "LA Weekend", pieces: [{ item: "Cashmere Crewneck", brand: "Brunello Cucinelli" }, { item: "Straight-Leg Denim", brand: "AG Jeans" }, { item: "Leather Sneaker", brand: "Common Projects" }] },
      { name: "Awards Classic", pieces: [{ item: "Draped Burgundy Gown", brand: "Carolina Herrera" }, { item: "Crystal Clutch", brand: "Judith Leiber" }, { item: "Pointed Pump", brand: "Manolo Blahnik" }] },
    ],
  },
  {
    id: "demi-moore",
    name: "Demi Moore",
    title: "The Enduring Red-Carpet Minimalist",
    style: "Sculptural Sophistication",
    description: "Demi Moore's style story is one of precision and longevity. Sleek tailoring, architectural gowns, monochrome dressing, and exceptional jewelry create a polished silhouette that feels timeless without ever looking cautious.",
    image: PHOTOS.demiMoore,
    accentColor: "#AFA7A0",
    era: "1980s–Present",
    knownFor: "Architectural gowns, monochrome tailoring, timeless red-carpet polish",
    signatureBrands: ["Schiaparelli", "Fendi", "Dior", "Saint Laurent", "Cartier"],
    keyPieces: ["Architectural column gown", "Longline tuxedo", "Silk blouse", "Diamond necklace", "Sharp stiletto"],
    vibes: ["Timeless", "Sculptural", "Monochrome Glamour"],
    looks: [
      { name: "Cannes Sculpture", pieces: [{ item: "Architectural Column Gown", brand: "Schiaparelli" }, { item: "Diamond Necklace", brand: "Cartier" }, { item: "Satin Sandal", brand: "Jimmy Choo" }] },
      { name: "Modern Icon", pieces: [{ item: "Longline Tuxedo", brand: "Saint Laurent" }, { item: "Silk Blouse", brand: "The Row" }, { item: "Sharp Stiletto", brand: "Christian Louboutin" }] },
      { name: "Monochrome Fendi", pieces: [{ item: "Draped Midi Dress", brand: "Fendi" }, { item: "Sculptural Clutch", brand: "Fendi" }, { item: "Leather Pump", brand: "Dior" }] },
      { name: "After-Party Noir", pieces: [{ item: "Velvet Column Dress", brand: "Tom Ford" }, { item: "Crystal Drop Earring", brand: "Bulgari" }, { item: "Patent Sandal", brand: "Saint Laurent" }] },
    ],
  },
  {
    id: "sza",
    name: "SZA",
    title: "The Ethereal R&B Individualist",
    style: "Dreamy Y2K Bohemia",
    description: "SZA's style is as emotionally layered as her music: earthy bohemian textures, nostalgic Y2K pieces, oversized streetwear, and otherworldly couture. She turns softness, experimentation, and individuality into a visual language all her own.",
    image: PHOTOS.sza,
    accentColor: "#87946B",
    era: "2012–Present",
    knownFor: "Dreamy stagewear, Y2K references, relaxed street style",
    signatureBrands: ["Vivienne Westwood", "Jean Paul Gaultier", "Mugler", "Marc Jacobs", "Rick Owens"],
    keyPieces: ["Corseted gown", "Oversized graphic jersey", "Low-rise cargo pant", "Sheer layered dress", "Platform boot"],
    vibes: ["Ethereal", "Y2K", "Bohemian Streetwear"],
    looks: [
      { name: "SOS Ethereal", pieces: [{ item: "Sheer Layered Dress", brand: "Jean Paul Gaultier" }, { item: "Sculptural Earring", brand: "Mugler" }, { item: "Platform Boot", brand: "Rick Owens" }] },
      { name: "Festival Dream", pieces: [{ item: "Crochet Halter Top", brand: "Chloé" }, { item: "Low-Rise Cargo Pant", brand: "Diesel" }, { item: "Retro Sneaker", brand: "Salomon" }] },
      { name: "Grammy Garden", pieces: [{ item: "Corseted Floral Gown", brand: "Vivienne Westwood" }, { item: "Diamond Drop Earring", brand: "Bulgari" }, { item: "Satin Sandal", brand: "Jimmy Choo" }] },
      { name: "Studio SZA", pieces: [{ item: "Oversized Graphic Jersey", brand: "Marc Jacobs" }, { item: "Relaxed Denim", brand: "Acne Studios" }, { item: "Platform Sneaker", brand: "New Balance" }] },
    ],
  },
  {
    id: "heidi-klum",
    name: "Heidi Klum",
    title: "The Fearless Supermodel Showstopper",
    style: "High-Voltage Glamour",
    description: "Heidi Klum approaches fashion with the confidence of a lifelong supermodel and the joy of a born entertainer. Body-skimming gowns, saturated color, daring cutouts, and theatrical costume moments keep her wardrobe energetic and unapologetic.",
    image: PHOTOS.heidiKlum,
    accentColor: "#D7A458",
    era: "1990s–Present",
    knownFor: "Supermodel glamour, dramatic gowns, legendary costume transformations",
    signatureBrands: ["Mugler", "Versace", "Zuhair Murad", "Moschino", "Christian Louboutin"],
    keyPieces: ["Cutout column gown", "Crystal mini dress", "Sculptural costume", "Metallic sandal", "Statement earring"],
    vibes: ["Supermodel Glamour", "Bold", "Theatrical"],
    looks: [
      { name: "Runway Legend", pieces: [{ item: "Cutout Column Gown", brand: "Mugler" }, { item: "Diamond Earring", brand: "Lorraine Schwartz" }, { item: "Metallic Sandal", brand: "Christian Louboutin" }] },
      { name: "Golden Buzzer", pieces: [{ item: "Crystal Mini Dress", brand: "Zuhair Murad" }, { item: "Sculptural Clutch", brand: "Judith Leiber" }, { item: "Platform Pump", brand: "Versace" }] },
      { name: "Cannes Voltage", pieces: [{ item: "Saturated Silk Gown", brand: "Georges Hobeika" }, { item: "Statement Necklace", brand: "Bulgari" }, { item: "Satin Stiletto", brand: "Jimmy Choo" }] },
      { name: "Model Off-Duty", pieces: [{ item: "Leather Moto Jacket", brand: "Saint Laurent" }, { item: "Straight-Leg Denim", brand: "Frame" }, { item: "Leather Ankle Boot", brand: "Khaite" }] },
    ],
  },
  {
    id: "savannah-james",
    name: "Savannah James",
    title: "The Refined Courtside Powerhouse",
    style: "Polished Modern Luxury",
    description: "Savannah James has developed a poised fashion identity built on precise tailoring, confident monochrome, and high-impact couture. From courtside appearances to Paris shows, her looks balance modern glamour with an assured, understated presence.",
    image: PHOTOS.savannahJames,
    accentColor: "#B98B65",
    era: "2010s–Present",
    knownFor: "Monochrome tailoring, polished family style, Paris couture moments",
    signatureBrands: ["Schiaparelli", "Dolce & Gabbana", "Alexander McQueen", "Gucci", "Christian Louboutin"],
    keyPieces: ["Sculpted trouser suit", "Corseted gown", "Longline coat", "Top-handle bag", "Pointed pump"],
    vibes: ["Polished Luxury", "Power Dressing", "Modern Glamour"],
    looks: [
      { name: "Paris Couture", pieces: [{ item: "Sculptural Jacket", brand: "Schiaparelli" }, { item: "Tailored Trouser", brand: "Schiaparelli" }, { item: "Gold-Toe Pump", brand: "Christian Louboutin" }] },
      { name: "Courtside Poise", pieces: [{ item: "Longline Leather Coat", brand: "Alexander McQueen" }, { item: "Fine-Knit Midi Dress", brand: "Khaite" }, { item: "Top-Handle Bag", brand: "Gucci" }] },
      { name: "Premiere Family", pieces: [{ item: "Corseted Column Gown", brand: "Dolce & Gabbana" }, { item: "Diamond Earring", brand: "Tiffany & Co." }, { item: "Satin Sandal", brand: "Jimmy Choo" }] },
      { name: "Monochrome Moment", pieces: [{ item: "Double-Breasted Blazer", brand: "Max Mara" }, { item: "Wide-Leg Trouser", brand: "Max Mara" }, { item: "Pointed Pump", brand: "Saint Laurent" }] },
    ],
  },
  {
    id: "lori-harvey",
    name: "Lori Harvey",
    title: "The New Guard Minimalist",
    style: "Sleek It-Girl Glamour",
    description: "Lori Harvey represents a new generation of polished celebrity style. Clean body-conscious silhouettes, luxe neutrals, sharp tailoring, and impeccably selected accessories give her wardrobe a sleek confidence from daytime events to the Met Gala.",
    image: PHOTOS.loriHarvey,
    accentColor: "#9C776A",
    era: "2017–Present",
    knownFor: "Sleek minimalism, sculpted eveningwear, elevated neutral dressing",
    signatureBrands: ["Michael Kors", "Burberry", "Saint Laurent", "LaQuan Smith", "Bottega Veneta"],
    keyPieces: ["Sculpted evening gown", "Cropped blazer", "Body-con midi dress", "Mini top-handle bag", "Strappy heel"],
    vibes: ["It-Girl", "Sleek Minimal", "Modern Glamour"],
    looks: [
      { name: "Met Gala Ease", pieces: [{ item: "Sculpted Evening Gown", brand: "Michael Kors" }, { item: "Diamond Drop Earring", brand: "Messika" }, { item: "Strappy Sandal", brand: "Jimmy Choo" }] },
      { name: "After-Party Sleek", pieces: [{ item: "Cutout Midi Dress", brand: "LaQuan Smith" }, { item: "Mini Pouch", brand: "Bottega Veneta" }, { item: "Satin Mule", brand: "Amina Muaddi" }] },
      { name: "Fashion Week Neutral", pieces: [{ item: "Cropped Blazer", brand: "Saint Laurent" }, { item: "High-Waist Trouser", brand: "The Row" }, { item: "Sharp-Toe Pump", brand: "Khaite" }] },
      { name: "London Front Row", pieces: [{ item: "Tailored Trench Coat", brand: "Burberry" }, { item: "Ribbed Knit Dress", brand: "Toteme" }, { item: "Leather Knee Boot", brand: "Bottega Veneta" }] },
    ],
  },
  {
    id: "future",
    name: "Future",
    title: "The Atlanta High-Fashion Maverick",
    style: "Trap-Luxe Avant-Garde",
    description: "Future helped define the visual language of modern Atlanta rap: dark luxury, statement outerwear, rare sneakers, stacked jewelry, and unexpected couture. His wardrobe moves between technical streetwear and European runway pieces with effortless confidence.",
    image: PHOTOS.future,
    accentColor: "#7D8B71",
    era: "2011–Present",
    knownFor: "Designer streetwear, dramatic coats, sunglasses, layered jewelry",
    signatureBrands: ["Lanvin", "Amiri", "Rick Owens", "Louis Vuitton", "Bottega Veneta"],
    keyPieces: ["Statement fur coat", "Leather trouser", "Oversized sunglasses", "Rare sneaker", "Diamond chain"],
    vibes: ["Trap Luxe", "Avant-garde", "Luxury Streetwear"],
    looks: [
      { name: "Pluto After Dark", pieces: [{ item: "Long Leather Coat", brand: "Rick Owens" }, { item: "Slim Leather Trouser", brand: "Amiri" }, { item: "Geobasket Sneaker", brand: "Rick Owens" }] },
      { name: "Atlanta Front Row", pieces: [{ item: "Oversized Tailored Jacket", brand: "Louis Vuitton" }, { item: "Silk Camp Shirt", brand: "Lanvin" }, { item: "Puddle Boot", brand: "Bottega Veneta" }] },
      { name: "DS2 Luxe", pieces: [{ item: "Statement Fur Coat", brand: "Amiri" }, { item: "Black Cashmere Knit", brand: "Loro Piana" }, { item: "Crystal-Trim Sneaker", brand: "Lanvin" }] },
      { name: "Studio Run", pieces: [{ item: "Technical Bomber", brand: "1017 ALYX 9SM" }, { item: "Utility Cargo Pant", brand: "Stone Island" }, { item: "Runner Sneaker", brand: "Balenciaga" }] },
    ],
  },
  {
    id: "michael-b-jordan",
    name: "Michael B. Jordan",
    title: "The Modern Leading Man",
    style: "Precision Tailoring",
    description: "Michael B. Jordan brings athletic presence and modern restraint to menswear. Immaculate suits, rich monochrome, knit polos, and carefully chosen jewelry give his red-carpet style the authority of classic Hollywood without feeling traditional.",
    image: PHOTOS.michaelBJordan,
    accentColor: "#8D6A53",
    era: "2010s–Present",
    knownFor: "Impeccable tailoring, tonal suits, modern leading-man polish",
    signatureBrands: ["Louis Vuitton", "Prada", "Tom Ford", "Berluti", "David Yurman"],
    keyPieces: ["Tonal double-breasted suit", "Fine-knit polo", "Long wool coat", "Luxury watch", "Leather loafer"],
    vibes: ["Modern Classic", "Power Dressing", "Leading Man"],
    looks: [
      { name: "Premiere Precision", pieces: [{ item: "Tonal Double-Breasted Suit", brand: "Louis Vuitton" }, { item: "Fine-Knit Polo", brand: "Prada" }, { item: "Leather Loafer", brand: "Berluti" }] },
      { name: "Creed Tailoring", pieces: [{ item: "Structured Wool Coat", brand: "Tom Ford" }, { item: "Cashmere Roll-Neck", brand: "Zegna" }, { item: "Tailored Trouser", brand: "Tom Ford" }] },
      { name: "Awards Season", pieces: [{ item: "Velvet Dinner Jacket", brand: "Prada" }, { item: "Silk Evening Shirt", brand: "Saint Laurent" }, { item: "Patent Derby", brand: "Berluti" }] },
      { name: "Off-Duty Lead", pieces: [{ item: "Suede Bomber Jacket", brand: "Brunello Cucinelli" }, { item: "Merino Crewneck", brand: "Loro Piana" }, { item: "Minimal Sneaker", brand: "Common Projects" }] },
    ],
  },
];
