// Local celebrity photos (bundled assets)
const PHOTOS = {
  drake:       require("../assets/images/celebrities/drake.jpeg"),
  rihanna:     require("../assets/images/celebrities/rihanna.jpeg"),
  kanye:       { uri: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=480&h=560&fit=crop&auto=format&q=80" },
  travis:      { uri: "https://images.unsplash.com/photo-1553514029-1318de880eea?w=480&h=560&fit=crop&auto=format&q=80" },
  fabolous:    require("../assets/images/celebrities/fabolous.jpeg"),
  denzel:      require("../assets/images/celebrities/denzel.jpeg"),
  snoop:       require("../assets/images/celebrities/snoop.jpeg"),
  jeezy:       require("../assets/images/celebrities/jeezy.jpg"),
  zendaya:     require("../assets/images/celebrities/zendaya.jpeg"),
  harry:       require("../assets/images/celebrities/harry_styles.jpeg"),
  pharrell:    require("../assets/images/celebrities/pharrell.jpeg"),
  audrey:      require("../assets/images/celebrities/audrey.webp"),
  marilyn:     require("../assets/images/celebrities/marilyn_monroe.jpeg"),
  ladygaga:    require("../assets/images/celebrities/lady_gaga.webp"),
  chloe:       require("../assets/images/celebrities/chloe_zhao.webp"),
  asap:        require("../assets/images/celebrities/asap_rocky.webp"),
  lewis:       require("../assets/images/celebrities/lewis_hamilton.webp"),
  sga:         require("../assets/images/celebrities/sga.webp"),
  nas:         require("../assets/images/celebrities/nas.jpg"),
};

export interface CelebLook {
  name: string;
  pieces: { item: string; brand: string }[];
}

export interface CelebFull {
  id: string;
  name: string;
  title: string;
  style: string;
  description: string;
  image: any;
  accentColor: string;
  era: string;
  knownFor: string;
  signatureBrands: string[];
  keyPieces: string[];
  vibes: string[];
  looks: CelebLook[];
}

export const CELEBS: CelebFull[] = [
  {
    id: "drake",
    name: "Drake",
    title: "The Rap God of Quiet Luxury",
    style: "Toronto Luxe",
    description: "OVO aesthetic — understated logos, $10k outerwear in neutral tones, NBA courtside ready. Drake elevated the 'I don't have to try' school of luxury streetwear.",
    image: PHOTOS.drake,
    accentColor: "#C6A75E",
    era: "2010s–Present",
    knownFor: "OVO, Nocta, Hermès, courtside fits",
    signatureBrands: ["OVO", "Hermès", "Nike / Nocta", "Louis Vuitton", "Canada Goose"],
    keyPieces: ["Hermès belt", "Nike Air Monarch (ironic)", "Owl logo hoodie", "Stone Island down coat", "Rolex Patek Philippe"],
    vibes: ["Quiet Luxury", "Luxury Streetwear", "Old Money"],
    looks: [
      { name: "Courtside God", pieces: [{ item: "OVO Owl Hoodie", brand: "OVO" }, { item: "Slim Track Pant", brand: "Hermès" }, { item: "Air Max 90", brand: "Nike" }] },
      { name: "Champagne Papi", pieces: [{ item: "Camel Overcoat", brand: "Canada Goose" }, { item: "Cashmere Roll-neck", brand: "Brunello Cucinelli" }, { item: "Suede Chelsea Boot", brand: "Bottega Veneta" }] },
    ],
  },
  {
    id: "rihanna",
    name: "Rihanna",
    title: "The Fashion Rule Breaker",
    style: "Avant-garde Power",
    description: "She wore a yellow Guo Pei gown to the Met and made it the most iconic fashion moment of the decade. Riri's wardrobe is fearless — couture to maternity streetwear, everything is intentional.",
    image: PHOTOS.rihanna,
    accentColor: "#E8C4C4",
    era: "2007–Present",
    knownFor: "Fenty, Dior Ambassador, Met Gala icon",
    signatureBrands: ["Fenty", "Christian Dior", "Puma x Fenty", "Manolo Blahnik", "Alaïa"],
    keyPieces: ["Oversized fur coat", "Latex bodysuit", "Thigh-high boots", "Crystal-embellished gown", "Fenty wide-leg suit"],
    vibes: ["Avant-garde", "Power Dressing", "Street Couture"],
    looks: [
      { name: "Fenty Power", pieces: [{ item: "Sculptural Bodysuit", brand: "Alaïa" }, { item: "Wide-Leg Leather Trouser", brand: "Fenty" }, { item: "Block Heel Boot", brand: "Manolo Blahnik" }] },
      { name: "Pregnant & Draped", pieces: [{ item: "Crystal Mini Dress", brand: "Valentino" }, { item: "Fur Cocoon Coat", brand: "Vetements" }, { item: "Pointed Mule", brand: "The Row" }] },
    ],
  },
  {
    id: "kanye",
    name: "Kanye West",
    title: "The Godfather of Fashion Rap",
    style: "Yeezy Minimalism",
    description: "From Louis Vuitton Don to Yeezy Season, Kanye remapped how hip-hop interacts with high fashion. Earth tones, Gap hoodies, and $800 slides changed everything.",
    image: PHOTOS.kanye,
    accentColor: "#9E8878",
    era: "2004–Present",
    knownFor: "Yeezy, Balenciaga, Gap, Bottega",
    signatureBrands: ["Yeezy", "Balenciaga", "Bottega Veneta", "Gap", "Louis Vuitton"],
    keyPieces: ["Yeezy foam runner", "Oversized hoodie", "Earth-tone long coat", "Tactical vest", "Yeezy Boost 350"],
    vibes: ["Minimal Luxury", "Luxury Streetwear", "Avant-garde"],
    looks: [
      { name: "Yeezy Season", pieces: [{ item: "Distressed Hoodie", brand: "Yeezy Gap" }, { item: "Cargo Jogger", brand: "Yeezy" }, { item: "Foam Runner", brand: "Adidas Yeezy" }] },
      { name: "Saint Pablo", pieces: [{ item: "Teddy Coat", brand: "Balenciaga" }, { item: "Military Trousers", brand: "Yeezy" }, { item: "Chelsea Boot", brand: "Bottega Veneta" }] },
    ],
  },
  {
    id: "travis",
    name: "Travis Scott",
    title: "Cactus Jack Couture",
    style: "Psychedelic Streetwear",
    description: "Travis turned Astroworld into a fashion universe. Cactus Jack collaborations with Nike, McDonald's, and Jordan made streetwear into cultural events.",
    image: PHOTOS.travis,
    accentColor: "#8B7355",
    era: "2016–Present",
    knownFor: "Cactus Jack x Jordan, Off-White, Raf Simons",
    signatureBrands: ["Cactus Jack", "Jordan Brand", "Off-White", "Helmut Lang", "Raf Simons"],
    keyPieces: ["Air Jordan 1 Retro Low", "Graphic tee", "Biker jacket", "Cargo trousers", "Camo elements"],
    vibes: ["Luxury Streetwear", "Psych", "Festival"],
    looks: [
      { name: "Astroworld Ready", pieces: [{ item: "Cactus Jack Graphic Tee", brand: "Cactus Jack" }, { item: "Distressed Denim", brand: "Helmut Lang" }, { item: "Jordan 1 Retro Low", brand: "Nike" }] },
      { name: "Stage King", pieces: [{ item: "Biker Jacket", brand: "Raf Simons" }, { item: "Cargo Trousers", brand: "Maharishi" }, { item: "Platform Boot", brand: "Rick Owens" }] },
    ],
  },
  {
    id: "fabolous",
    name: "Fabolous",
    title: "Brooklyn's Best Dressed",
    style: "New York Uptown",
    description: "Fabolous turned Brooklyn hip-hop into a luxury fashion school. Fitted caps, Clarks Wallabees, and just the right amount of bling — effortlessly NY.",
    image: PHOTOS.fabolous,
    accentColor: "#A89070",
    era: "2001–Present",
    knownFor: "NY streetwear, fitted caps, designer denim",
    signatureBrands: ["Gucci", "Versace", "Ralph Lauren", "Clarks", "True Religion"],
    keyPieces: ["Designer denim", "Fitted cap", "Gold chain", "Clarks Desert Boot", "Varsity jacket"],
    vibes: ["NY Uptown", "Luxury Streetwear", "Classic Hip-hop"],
    looks: [
      { name: "Brooklyn Uptown", pieces: [{ item: "Fitted Cap", brand: "New Era" }, { item: "Slim-Fit Denim", brand: "True Religion" }, { item: "Desert Boot", brand: "Clarks" }] },
      { name: "NY Nights", pieces: [{ item: "Leather Jacket", brand: "Versace" }, { item: "Slim Chino", brand: "Gucci" }, { item: "Gold Rope Chain", brand: "Jacob & Co" }] },
    ],
  },
  {
    id: "denzel",
    name: "Denzel Washington",
    title: "Hollywood's Timeless Gentleman",
    style: "Classic American Elegance",
    description: "No trend, no gimmicks — just perfectly cut suits, Italian leather, and the quiet confidence of someone who has always known exactly who they are.",
    image: PHOTOS.denzel,
    accentColor: "#8899A0",
    era: "1980s–Present",
    knownFor: "Perfectly cut suits, understated elegance",
    signatureBrands: ["Tom Ford", "Giorgio Armani", "Brioni", "Zegna", "Gucci"],
    keyPieces: ["Perfectly-cut black suit", "White pocket square", "Oxford shirt", "Italian leather Oxford", "Understated watch"],
    vibes: ["Old Money", "Classic Elegance", "Power Dressing"],
    looks: [
      { name: "Hollywood Formal", pieces: [{ item: "Black Tuxedo", brand: "Tom Ford" }, { item: "French Cuff Shirt", brand: "Zegna" }, { item: "Patent Oxford", brand: "Gucci" }] },
      { name: "Press Day", pieces: [{ item: "Charcoal Suit", brand: "Giorgio Armani" }, { item: "Silk Tie", brand: "Brioni" }, { item: "Oxford Brogue", brand: "Edward Green" }] },
    ],
  },
  {
    id: "snoop",
    name: "Snoop Dogg",
    title: "Long Beach's Most Stylish OG",
    style: "California Cool",
    description: "The OG of laid-back California luxury. Snoop evolved from Doggystyle Dickies to Gucci tracksuits — always relaxed, always dripping, always himself.",
    image: PHOTOS.snoop,
    accentColor: "#7A9E7E",
    era: "1992–Present",
    knownFor: "Tracksuits, braids, California 420 luxury",
    signatureBrands: ["Gucci", "Adidas", "Death Row", "Snoop Dogg x Skechers", "Coach"],
    keyPieces: ["Velour tracksuit", "G-funk cap", "Gucci loafer", "Gold rope", "Croc-skin accessories"],
    vibes: ["California Cool", "Old School Luxe", "Laid-back Hip-hop"],
    looks: [
      { name: "West Coast OG", pieces: [{ item: "Gucci Velour Tracksuit", brand: "Gucci" }, { item: "Bucket Hat", brand: "Kangol" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Gin & Juice Night", pieces: [{ item: "Silk Bowling Shirt", brand: "Dries Van Noten" }, { item: "Wide-leg Linen Trouser", brand: "The Row" }, { item: "Suede Loafer", brand: "Gucci" }] },
    ],
  },
  {
    id: "jeezy",
    name: "Young Jeezy",
    title: "Atlanta Trap Royalty",
    style: "ATL Trap Luxe",
    description: "Jeezy turned Atlanta streets into a fashion statement. He brought the white tee movement to its peak and proved that trap music and luxury fashion were never mutually exclusive.",
    image: PHOTOS.jeezy,
    accentColor: "#A0A0A0",
    era: "2005–Present",
    knownFor: "Snowflake era, designer belts, ATL drip",
    signatureBrands: ["Versace", "Balenciaga", "Balmain", "Moncler", "Iceberg"],
    keyPieces: ["Moncler puffer", "Versace belt", "White tee", "Nike Air Force 1", "Gold Cuban chain"],
    vibes: ["Trap Luxe", "Luxury Streetwear", "ATL"],
    looks: [
      { name: "Snowman Season", pieces: [{ item: "Moncler Down Puffer", brand: "Moncler" }, { item: "Designer Denim", brand: "True Religion" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Corporate Thuggin", pieces: [{ item: "Versace Blazer", brand: "Versace" }, { item: "Balmain Jeans", brand: "Balmain" }, { item: "Luxury Boot", brand: "Giuseppe Zanotti" }] },
    ],
  },
  {
    id: "zendaya",
    name: "Zendaya",
    title: "Fashion's Reigning Queen",
    style: "Avant-garde Theatre",
    description: "From spider-web Valentino to robotic Mugler at the Met — Zendaya's stylist Law Roach transformed her into fashion's greatest theatrical act. Every look tells a story.",
    image: PHOTOS.zendaya,
    accentColor: "#D4A8B0",
    era: "2014–Present",
    knownFor: "Law Roach styling, Valentino, Met Gala moments",
    signatureBrands: ["Valentino", "Mugler", "Versace", "Louis Vuitton", "Armani"],
    keyPieces: ["Sculptural gown", "Spider-web heels", "Chainmail dress", "Romantic corset", "Statement jewelry"],
    vibes: ["Avant-garde", "Theatrical", "High Fashion"],
    looks: [
      { name: "Dune Premiere", pieces: [{ item: "Column Gown", brand: "Valentino" }, { item: "Statement Earrings", brand: "Bulgari" }, { item: "Strappy Heel", brand: "Roger Vivier" }] },
      { name: "Challengers", pieces: [{ item: "Colourblock Polo Dress", brand: "Louis Vuitton" }, { item: "Visor", brand: "Nike" }, { item: "Platform Sneaker", brand: "Adidas" }] },
    ],
  },
  {
    id: "harry",
    name: "Harry Styles",
    title: "The Gender-Fluid Rock God",
    style: "Vintage Eclectic Glamour",
    description: "Harry proved that pearl necklaces, feather boas, and Gucci jumpsuits belong on everyone. A vintage eclectic spirit that's part Elton John, part Mick Jagger, part utterly himself.",
    image: PHOTOS.harry,
    accentColor: "#C4A8C4",
    era: "2017–Present",
    knownFor: "Gucci muse, gender-fluid, vintage, feather boa",
    signatureBrands: ["Gucci", "Vivienne Westwood", "Palomo Spain", "JW Anderson", "Pleasing"],
    keyPieces: ["Flared trouser", "Feather boa", "Pearl necklace", "Platform Chelsea boot", "Colourful suit"],
    vibes: ["Eclectic", "Gender-Fluid", "Vintage Glam", "70s Revival"],
    looks: [
      { name: "Golden Hour", pieces: [{ item: "Colourblock Suit", brand: "Gucci" }, { item: "Ruffled Blouse", brand: "JW Anderson" }, { item: "Platform Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Fine Line Era", pieces: [{ item: "Pearl Necklace", brand: "Mikimoto" }, { item: "High-Waist Flare", brand: "Palomo Spain" }, { item: "Feather Jacket", brand: "Gucci" }] },
    ],
  },
  {
    id: "pharrell",
    name: "Pharrell Williams",
    title: "The Eternal Skater Visionary",
    style: "Eclectic Luxury Supreme",
    description: "Pharrell invented the massive Vivienne Westwood hat moment and now runs Louis Vuitton Men's. His style is an art installation — Chanel, skateboarding, Billionaire Boys Club, and the brain of a genius.",
    image: PHOTOS.pharrell,
    accentColor: "#C6A75E",
    era: "1999–Present",
    knownFor: "BBC Ice Cream, LV Men's Director, hat collector",
    signatureBrands: ["Louis Vuitton", "Chanel", "Billionaire Boys Club", "adidas", "Vivienne Westwood"],
    keyPieces: ["Giant western hat", "BBC logo tee", "Adidas Human Race", "Chanel accessories", "Custom LV sneaker"],
    vibes: ["Eclectic Luxury", "Skate Culture", "Art World"],
    looks: [
      { name: "LV Creative Director", pieces: [{ item: "Custom LV Suit", brand: "Louis Vuitton" }, { item: "Platform Sneaker", brand: "LV" }, { item: "Diamond Earring", brand: "Jacob & Co" }] },
      { name: "BBC OG", pieces: [{ item: "BBC Logo Tee", brand: "Billionaire Boys Club" }, { item: "Slim Jogger", brand: "Adidas" }, { item: "Human Race Sneaker", brand: "Adidas" }] },
    ],
  },
  {
    id: "audrey",
    name: "Audrey Hepburn",
    title: "Hollywood's Eternal Muse",
    style: "Classic Hollywood Elegance",
    description: "The little black dress, the Givenchy trench, the Breakfast at Tiffany's neckline. Audrey's wardrobe defined Hollywood glamour without ever trying to compete — it simply arrived and stayed.",
    image: PHOTOS.audrey,
    accentColor: "#C0B090",
    era: "1950s–1960s",
    knownFor: "Givenchy muse, the LBD, Holly Golightly aesthetic",
    signatureBrands: ["Givenchy", "Balenciaga", "Ferragamo", "Valentino", "Tiffany & Co"],
    keyPieces: ["The little black dress", "White gloves", "Cigarette trouser", "Ballet flat", "Cat-eye sunglasses"],
    vibes: ["Classic Elegance", "Old Money", "Timeless"],
    looks: [
      { name: "Breakfast at Tiffany's", pieces: [{ item: "Black Sheath Dress", brand: "Givenchy" }, { item: "Long White Gloves", brand: "Fownes" }, { item: "Pearl Drop Earrings", brand: "Tiffany & Co" }] },
      { name: "Roman Holiday", pieces: [{ item: "Cigarette Trouser", brand: "Givenchy" }, { item: "Striped Blouse", brand: "Givenchy" }, { item: "Capri Ballet Flat", brand: "Ferragamo" }] },
    ],
  },
  {
    id: "marilyn",
    name: "Marilyn Monroe",
    title: "The Original Icon",
    style: "Old Hollywood Glamour",
    description: "She wore nothing but Chanel No. 5 and a smile, then wore the most famous dress in American history. Marilyn's sensuality was couture — calibrated, conscious, and entirely her own.",
    image: PHOTOS.marilyn,
    accentColor: "#F0D8C8",
    era: "1950s–1960s",
    knownFor: "Happy Birthday Mr. President gown, the white dress, Chanel",
    signatureBrands: ["Jean Louis", "Travilla", "Chanel", "Norman Norell", "Emilio Pucci"],
    keyPieces: ["Sequined column gown", "Red lips", "White halter dress", "Mink stole", "Diamond choker"],
    vibes: ["Old Hollywood", "Glamour", "Sensual Luxury"],
    looks: [
      { name: "Happy Birthday, Mr. President", pieces: [{ item: "Nude Sequined Column Gown", brand: "Jean Louis" }, { item: "Diamond Bracelet", brand: "Harry Winston" }, { item: "Barely-There Heel", brand: "Custom" }] },
      { name: "Manhattan Blonde", pieces: [{ item: "White Halter Dress", brand: "Travilla" }, { item: "Red Lip (Revlon)", brand: "Revlon" }, { item: "Block Heel Mule", brand: "Ferragamo" }] },
    ],
  },
  {
    id: "ladygaga",
    name: "Lady Gaga",
    title: "Fashion's Greatest Provocateur",
    style: "Theatrical Avant-garde",
    description: "Meat dresses, nine-inch armadillo shoes, Alexander McQueen bubbles — Gaga turned fashion into performance art and performance into fashion. The boundary doesn't exist for her.",
    image: PHOTOS.ladygaga,
    accentColor: "#B0A0C8",
    era: "2008–Present",
    knownFor: "McQueen Armadillo shoes, Haus of Gaga, Met Gala theatrics",
    signatureBrands: ["Alexander McQueen", "Versace", "Valentino", "Atelier Versace", "Schiaparelli"],
    keyPieces: ["Armadillo shoe (McQueen)", "Platinum wig", "Crystal bodysuit", "Architectural headpiece", "Avant-garde gloves"],
    vibes: ["Avant-garde", "Theatrical", "Provocation"],
    looks: [
      { name: "Bad Romance", pieces: [{ item: "Ivory Architectural Gown", brand: "Schiaparelli" }, { item: "Crystal Headpiece", brand: "Custom" }, { item: "Platform Heel", brand: "Alexander McQueen" }] },
      { name: "Joanne Tour", pieces: [{ item: "Pink Cowboy Hat", brand: "Haus of Gaga" }, { item: "Rhinestone Bodysuit", brand: "Atelier Versace" }, { item: "Thigh-High Boot", brand: "Versace" }] },
    ],
  },
  {
    id: "chloe",
    name: "Chloé Zhao",
    title: "Hollywood's Quiet Revolutionary",
    style: "Understated Nomadic",
    description: "The Oscar-winning director who wore jeans to the Academy Awards. Chloé's style is deliberate minimalism — the anti-Hollywood statement that said more than any couture gown.",
    image: PHOTOS.chloe,
    accentColor: "#8A9E8A",
    era: "2018–Present",
    knownFor: "Nomadic minimalism, jeans at the Oscars, quiet statement",
    signatureBrands: ["The Row", "Lemaire", "Toteme", "COS", "Acne Studios"],
    keyPieces: ["Relaxed denim", "Cashmere knit", "Simple leather boot", "Linen trouser", "Minimal jewellery"],
    vibes: ["Quiet Luxury", "Minimalism", "Nomadic"],
    looks: [
      { name: "Oscar Night Rebel", pieces: [{ item: "High-Rise Denim", brand: "Agolde" }, { item: "Cashmere Knit", brand: "The Row" }, { item: "Chelsea Boot", brand: "The Row" }] },
      { name: "Eternals Press", pieces: [{ item: "Wide-Leg Linen Trouser", brand: "Toteme" }, { item: "Silk Blouse", brand: "Equipment" }, { item: "Leather Mule", brand: "Lemaire" }] },
    ],
  },
  {
    id: "asap",
    name: "A$AP Rocky",
    title: "Fashion's Crown Prince",
    style: "Luxury Art-world Streetwear",
    description: "He wore Raf Simons before anyone knew the name. Rocky became the rapper-as-fashion-editor archetype — his Met Gala quilted vest and avant-garde layering blurred fashion and art.",
    image: PHOTOS.asap,
    accentColor: "#9898A8",
    era: "2011–Present",
    knownFor: "Raf Simons OG, fashion week front-row king, art-world meets hip-hop",
    signatureBrands: ["Raf Simons", "Gucci", "Calvin Klein", "Rick Owens", "Dior Homme"],
    keyPieces: ["Printed scarf", "Quilted vest", "Chunky brogues", "Kilt / wrap skirt", "Layered chains"],
    vibes: ["Luxury Streetwear", "Art World", "Avant-garde"],
    looks: [
      { name: "Raf Era", pieces: [{ item: "Printed Knit Sweater", brand: "Raf Simons" }, { item: "Slim Denim", brand: "Raf Simons" }, { item: "Chunky Brogue", brand: "Raf Simons" }] },
      { name: "Gucci Head", pieces: [{ item: "Print Silk Shirt", brand: "Gucci" }, { item: "Vintage Denim", brand: "Levi's Vintage" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
    ],
  },
  {
    id: "lewis",
    name: "Lewis Hamilton",
    title: "Formula One's Fashion Rebel",
    style: "Race-day Luxury",
    description: "Lewis broke F1's stuffy dress code and never looked back. Custom Tommy Hilfiger, Burberry editorial shoots, and front-row fashion week appearances made him the sport's first true fashion icon.",
    image: PHOTOS.lewis,
    accentColor: "#9898A8",
    era: "2009–Present",
    knownFor: "Tommy Hilfiger collab, Burberry, Valentino, fashion week regular",
    signatureBrands: ["Tommy Hilfiger x Lewis", "Valentino", "Burberry", "Mercedes-AMG gear", "Chrome Hearts"],
    keyPieces: ["Custom race suit", "Chrome Hearts sunglasses", "Statement coat", "Custom sneakers", "Gold chain"],
    vibes: ["Race-day Luxe", "Power Dressing", "Street Couture"],
    looks: [
      { name: "Paddock Ready", pieces: [{ item: "Custom Embroidered Jacket", brand: "Tommy x Lewis" }, { item: "Wide-leg Cargo", brand: "Valentino" }, { item: "Platform Sneaker", brand: "Valentino" }] },
      { name: "Fashion Week Front Row", pieces: [{ item: "Statement Fur Coat", brand: "Burberry" }, { item: "Leather Trouser", brand: "Valentino" }, { item: "Chrome Hearts Sunglasses", brand: "Chrome Hearts" }] },
    ],
  },
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    title: "The NBA's Most Original Dresser",
    style: "Unique NBA Editorial",
    description: "SGA doesn't follow trends — he sets them. Quiet luxury, unique Japanese brands, odd-ratio silhouettes, and editorial styling that belongs in a magazine, not just a locker room.",
    image: PHOTOS.sga,
    accentColor: "#8E9EAB",
    era: "2020–Present",
    knownFor: "Arena tunnel fits, editorial styling, quiet luxury NBA",
    signatureBrands: ["The Row", "Toteme", "Comme des Garçons", "Yohji Yamamoto", "New Balance"],
    keyPieces: ["Oversized trench coat", "Relaxed wide-leg trousers", "Plain white tee", "Minimalist sneaker", "Stack of rings"],
    vibes: ["Quiet Luxury", "NBA Tunnel", "Editorial Minimal"],
    looks: [
      { name: "Tunnel Walk", pieces: [{ item: "Oversized Trench", brand: "The Row" }, { item: "Wide-Leg Trouser", brand: "Toteme" }, { item: "Minimalist Sneaker", brand: "New Balance" }] },
      { name: "OKC Quiet", pieces: [{ item: "CDG Knit Polo", brand: "Comme des Garçons" }, { item: "Relaxed Trouser", brand: "Yohji Yamamoto" }, { item: "Simple Loafer", brand: "Lemaire" }] },
    ],
  },
  {
    id: "nas",
    name: "Nas",
    title: "Queens Bridge's Eternal Style King",
    style: "Classic New York",
    description: "Nas dressed like money before money talked the way it does now. Timeless NY — Timberlands, leather bubble coats, and just enough gold. He proved that classic never ages.",
    image: PHOTOS.nas,
    accentColor: "#B8A888",
    era: "1994–Present",
    knownFor: "Timberlands, classic NY hip-hop, bubble coat era",
    signatureBrands: ["Timberland", "Phat Farm", "Ralph Lauren", "Hermès", "Tom Ford"],
    keyPieces: ["Timberland boot", "Bubble goose coat", "Gold chains", "Fitted baseball cap", "Luxury watch"],
    vibes: ["NY Classic", "Old School Hip-hop", "Quiet Luxury"],
    looks: [
      { name: "Illmatic Era", pieces: [{ item: "Bubble Goose Coat", brand: "Northface" }, { item: "Timberland 6-Inch Boot", brand: "Timberland" }, { item: "Fitted Cap", brand: "New Era" }] },
      { name: "Kings Disease", pieces: [{ item: "Tom Ford Suit", brand: "Tom Ford" }, { item: "Hermès Belt", brand: "Hermès" }, { item: "Oxford Boot", brand: "Berluti" }] },
    ],
  },
];
