// Local celebrity photos (bundled assets)
const PHOTOS = {
  drake:       require("../assets/images/celebrities/drake.jpeg"),
  rihanna:     require("../assets/images/celebrities/rihanna.jpeg"),
  kanye:       require("../assets/images/celebrities/kanye.jpeg"),
  travis:      { uri: "https://images.unsplash.com/photo-1553514029-1318de880eea?w=480&h=560&fit=crop&auto=format&q=80" },
  fabolous:    require("../assets/images/celebrities/fabolous.jpeg"),
  denzel:      require("../assets/images/celebrities/denzel.jpeg"),
  snoop:       require("../assets/images/celebrities/snoop.jpeg"),
  jeezy:       require("../assets/images/celebrities/jeezy.jpg"),
  zendaya:     require("../assets/images/celebrities/zendaya.jpeg"),
  harry:       require("../assets/images/celebrities/harry_styles.jpeg"),
  pharrell:    require("../assets/images/celebrities/pharrell.jpeg"),
  audrey:      require("../assets/images/celebrities/audrey.webp"),
  marilyn:     require("../assets/images/celebrities/marilyn_monroe.jpeg"),
  ladygaga:    require("../assets/images/celebrities/lady_gaga.webp"),
  chloe:       require("../assets/images/celebrities/chloe_zhao.webp"),
  asap:        require("../assets/images/celebrities/asap_rocky.webp"),
  lewis:       require("../assets/images/celebrities/lewis_hamilton.webp"),
  sga:         require("../assets/images/celebrities/sga.webp"),
  nas:         require("../assets/images/celebrities/nas.jpg"),
};

export interface CelebLook {
  name: string;
  pieces: { item: string; brand: string }[];
}

export interface CelebFull {
  id: string;
  name: string;
  title: string;
  style: string;
  description: string;
  image: any;
  accentColor: string;
  era: string;
  knownFor: string;
  signatureBrands: string[];
  keyPieces: string[];
  vibes: string[];
  looks: CelebLook[];
}

export const CELEBS: CelebFull[] = [
  {
    id: "drake",
    name: "Drake",
    title: "The Rap God of Quiet Luxury",
    style: "Toronto Luxe",
    description: "OVO aesthetic — understated logos, $10k outerwear in neutral tones, NBA courtside ready. Drake elevated the 'I don't have to try' school of luxury streetwear.",
    image: PHOTOS.drake,
    accentColor: "#C6A75E",
    era: "2010s–Present",
    knownFor: "OVO, Nocta, Hermès, courtside fits",
    signatureBrands: ["OVO", "Hermès", "Nike / Nocta", "Louis Vuitton", "Canada Goose"],
    keyPieces: ["Hermès belt", "Nike Air Monarch (ironic)", "Owl logo hoodie", "Stone Island down coat", "Rolex Patek Philippe"],
    vibes: ["Quiet Luxury", "Luxury Streetwear", "Old Money"],
    looks: [
      { name: "Courtside God", pieces: [{ item: "OVO Owl Hoodie", brand: "OVO" }, { item: "Slim Track Pant", brand: "Hermès" }, { item: "Air Max 90", brand: "Nike" }] },
      { name: "Champagne Papi", pieces: [{ item: "Camel Overcoat", brand: "Canada Goose" }, { item: "Cashmere Roll-neck", brand: "Brunello Cucinelli" }, { item: "Suede Chelsea Boot", brand: "Bottega Veneta" }] },
      { name: "OVO Tour", pieces: [{ item: "Stadium Tour Hoodie", brand: "OVO" }, { item: "Nike Track Pant", brand: "Nike" }, { item: "Air Jordan 4", brand: "Nike" }] },
      { name: "Toronto Winter", pieces: [{ item: "Down Parka", brand: "Stone Island" }, { item: "Cashmere Turtleneck", brand: "Hermès" }, { item: "6-Inch Boot", brand: "Timberland" }] },
      { name: "Certified Lover", pieces: [{ item: "Velvet DB Suit", brand: "Tom Ford" }, { item: "Satin Shirt", brand: "Brioni" }, { item: "Patent Loafer", brand: "Gucci" }] },
      { name: "Nocta Run", pieces: [{ item: "Fleece Track Jacket", brand: "Nike Nocta" }, { item: "Compression Tight", brand: "Nike Nocta" }, { item: "Air Max Scorpion", brand: "Nike" }] },
      { name: "Hermès Heavy", pieces: [{ item: "Cashmere Hoodie", brand: "Hermès" }, { item: "Slim Trouser", brand: "Hermès" }, { item: "Oran Sandal", brand: "Hermès" }] },
      { name: "Golden Hours", pieces: [{ item: "Linen Blazer", brand: "Loro Piana" }, { item: "White Oxford Shirt", brand: "Charvet" }, { item: "Driving Shoe", brand: "Berluti" }] },
      { name: "Club Ritz", pieces: [{ item: "Custom Bomber", brand: "1 of 1" }, { item: "Skinny Denim", brand: "Amiri" }, { item: "Jordan 1 Retro", brand: "Nike" }] },
      { name: "Yacht Diaries", pieces: [{ item: "Swim Short", brand: "Vilebrequin" }, { item: "Linen Camp Shirt", brand: "Loro Piana" }, { item: "Canvas Sneaker", brand: "Rivieras" }] },
      { name: "Grammy Night", pieces: [{ item: "Fur-Trim Tuxedo", brand: "Rick Owens" }, { item: "Black Roll-neck", brand: "Prada" }, { item: "Chelsea Boot", brand: "Bottega Veneta" }] },
      { name: "Press Tour", pieces: [{ item: "Cashmere Crewneck", brand: "Loro Piana" }, { item: "Relaxed Chino", brand: "Ralph Lauren Purple Label" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
    ],
  },
  {
    id: "rihanna",
    name: "Rihanna",
    title: "The Fashion Rule Breaker",
    style: "Avant-garde Power",
    description: "She wore a yellow Guo Pei gown to the Met and made it the most iconic fashion moment of the decade. Riri's wardrobe is fearless — couture to maternity streetwear, everything is intentional.",
    image: PHOTOS.rihanna,
    accentColor: "#E8C4C4",
    era: "2007–Present",
    knownFor: "Fenty, Dior Ambassador, Met Gala icon",
    signatureBrands: ["Fenty", "Christian Dior", "Puma x Fenty", "Manolo Blahnik", "Alaïa"],
    keyPieces: ["Oversized fur coat", "Latex bodysuit", "Thigh-high boots", "Crystal-embellished gown", "Fenty wide-leg suit"],
    vibes: ["Avant-garde", "Power Dressing", "Street Couture"],
    looks: [
      { name: "Fenty Power", pieces: [{ item: "Sculptural Bodysuit", brand: "Alaïa" }, { item: "Wide-Leg Leather Trouser", brand: "Fenty" }, { item: "Block Heel Boot", brand: "Manolo Blahnik" }] },
      { name: "Pregnant & Draped", pieces: [{ item: "Crystal Mini Dress", brand: "Valentino" }, { item: "Fur Cocoon Coat", brand: "Vetements" }, { item: "Pointed Mule", brand: "The Row" }] },
      { name: "Met Gala Yellow", pieces: [{ item: "Couture Cape Gown", brand: "Guo Pei" }, { item: "Diamond Crown", brand: "Harry Winston" }, { item: "Embellished Platform", brand: "Custom" }] },
      { name: "Barbados Carnival", pieces: [{ item: "Beaded Bikini Set", brand: "Custom" }, { item: "Feather Headdress", brand: "Custom" }, { item: "Platform Sneaker", brand: "Puma Fenty" }] },
      { name: "Super Bowl Queen", pieces: [{ item: "Silver Mesh Catsuit", brand: "Loewe" }, { item: "Thigh-High Boot", brand: "Stuart Weitzman" }, { item: "Diamond Cuff", brand: "Tiffany & Co" }] },
      { name: "Crystal Lady", pieces: [{ item: "Crystal Corset", brand: "Atelier Versace" }, { item: "Micro Mini Skirt", brand: "Versace" }, { item: "Strappy Heel", brand: "Amina Muaddi" }] },
      { name: "Vogue Paris", pieces: [{ item: "Chinchilla Coat", brand: "Dries Van Noten" }, { item: "Leather Bodysuit", brand: "Alaïa" }, { item: "Patent Thigh Boot", brand: "Louboutin" }] },
      { name: "Fenty Business", pieces: [{ item: "Power Blazer", brand: "Fenty" }, { item: "High-Waist Trouser", brand: "Fenty" }, { item: "Square-Toe Heel", brand: "The Row" }] },
      { name: "Street Couture", pieces: [{ item: "Oversized Bomber", brand: "Balenciaga" }, { item: "Biker Short", brand: "Fenty" }, { item: "Platform Sneaker", brand: "Raf Simons x Adidas" }] },
      { name: "Night Out", pieces: [{ item: "Draped Mini Dress", brand: "Saint Laurent" }, { item: "Fishnet Tight", brand: "Falke" }, { item: "Stiletto Ankle Strap", brand: "Louboutin" }] },
      { name: "Ivy Park Drop", pieces: [{ item: "Matching Tracksuit", brand: "Ivy Park x Adidas" }, { item: "Sneaker Wedge", brand: "Adidas" }, { item: "Gold Jewelry Stack", brand: "Custom" }] },
      { name: "Red Carpet Bad", pieces: [{ item: "Asymmetric Gown", brand: "Giambattista Valli" }, { item: "Statement Earring", brand: "Bulgari" }, { item: "Strappy Sandal", brand: "Jimmy Choo" }] },
    ],
  },
  {
    id: "kanye",
    name: "Kanye West",
    title: "The Godfather of Fashion Rap",
    style: "Yeezy Minimalism",
    description: "From Louis Vuitton Don to Yeezy Season, Kanye remapped how hip-hop interacts with high fashion. Earth tones, Gap hoodies, and $800 slides changed everything.",
    image: PHOTOS.kanye,
    accentColor: "#9E8878",
    era: "2004–Present",
    knownFor: "Yeezy, Balenciaga, Gap, Bottega",
    signatureBrands: ["Yeezy", "Balenciaga", "Bottega Veneta", "Gap", "Louis Vuitton"],
    keyPieces: ["Yeezy foam runner", "Oversized hoodie", "Earth-tone long coat", "Tactical vest", "Yeezy Boost 350"],
    vibes: ["Minimal Luxury", "Luxury Streetwear", "Avant-garde"],
    looks: [
      { name: "Yeezy Season", pieces: [{ item: "Distressed Hoodie", brand: "Yeezy Gap" }, { item: "Cargo Jogger", brand: "Yeezy" }, { item: "Foam Runner", brand: "Adidas Yeezy" }] },
      { name: "Saint Pablo", pieces: [{ item: "Teddy Coat", brand: "Balenciaga" }, { item: "Military Trousers", brand: "Yeezy" }, { item: "Chelsea Boot", brand: "Bottega Veneta" }] },
      { name: "Donda Era", pieces: [{ item: "Tactical Vest", brand: "Fear of God" }, { item: "Slim All-Black Pant", brand: "Yeezy" }, { item: "Yeezy 500 Utility", brand: "Adidas Yeezy" }] },
      { name: "Gap God", pieces: [{ item: "Yeezy Gap Round Jacket", brand: "Yeezy Gap" }, { item: "Basic Tee", brand: "Yeezy" }, { item: "Foam Runner", brand: "Adidas Yeezy" }] },
      { name: "Balenciaga Ye", pieces: [{ item: "Logo Tracksuit", brand: "Balenciaga" }, { item: "Oversized Hoodie", brand: "Balenciaga" }, { item: "Speed Trainer", brand: "Balenciaga" }] },
      { name: "Earth Tone", pieces: [{ item: "Neutral Trench Coat", brand: "Bottega Veneta" }, { item: "Earth-Tone Knit", brand: "Yeezy" }, { item: "Combat Boot", brand: "Yeezy" }] },
      { name: "LV Don Era", pieces: [{ item: "Monogram Suit", brand: "Louis Vuitton" }, { item: "Graphic Tee", brand: "Louis Vuitton" }, { item: "LV Sneaker", brand: "Louis Vuitton" }] },
      { name: "Ye Casual", pieces: [{ item: "Plain White Tee", brand: "Hanes" }, { item: "Cargo Pant", brand: "Yeezy" }, { item: "Yeezy Boost 350 V2", brand: "Adidas Yeezy" }] },
      { name: "Power Suit", pieces: [{ item: "Double-Breasted Suit", brand: "Balmain" }, { item: "Mock-Neck Knit", brand: "Zegna" }, { item: "Italian Leather Shoe", brand: "Berluti" }] },
      { name: "Minimal Noir", pieces: [{ item: "Long Black Coat", brand: "Rick Owens" }, { item: "Black Turtleneck", brand: "Rick Owens" }, { item: "DRKSHDW Boot", brand: "Rick Owens" }] },
      { name: "Stadium Tour", pieces: [{ item: "Shearling Jacket", brand: "Loro Piana" }, { item: "Distressed Denim", brand: "KSUBI" }, { item: "Jordan 1 Retro", brand: "Nike" }] },
      { name: "Wyoming Chapter", pieces: [{ item: "Flannel Shirt", brand: "L.L.Bean" }, { item: "Workwear Denim", brand: "Wrangler" }, { item: "Timberland Pro Boot", brand: "Timberland" }] },
    ],
  },
  {
    id: "travis",
    name: "Travis Scott",
    title: "Cactus Jack Couture",
    style: "Psychedelic Streetwear",
    description: "Travis turned Astroworld into a fashion universe. Cactus Jack collaborations with Nike, McDonald's, and Jordan made streetwear into cultural events.",
    image: PHOTOS.travis,
    accentColor: "#8B7355",
    era: "2016–Present",
    knownFor: "Cactus Jack x Jordan, Off-White, Raf Simons",
    signatureBrands: ["Cactus Jack", "Jordan Brand", "Off-White", "Helmut Lang", "Raf Simons"],
    keyPieces: ["Air Jordan 1 Retro Low", "Graphic tee", "Biker jacket", "Cargo trousers", "Camo elements"],
    vibes: ["Luxury Streetwear", "Psych", "Festival"],
    looks: [
      { name: "Astroworld Ready", pieces: [{ item: "Cactus Jack Graphic Tee", brand: "Cactus Jack" }, { item: "Distressed Denim", brand: "Helmut Lang" }, { item: "Jordan 1 Retro Low", brand: "Nike" }] },
      { name: "Stage King", pieces: [{ item: "Biker Jacket", brand: "Raf Simons" }, { item: "Cargo Trousers", brand: "Maharishi" }, { item: "Platform Boot", brand: "Rick Owens" }] },
      { name: "Cactus Jack Collab", pieces: [{ item: "Travis x Jordan 1", brand: "Nike" }, { item: "Fragment Tee", brand: "Fragment Design" }, { item: "Slim Denim", brand: "Helmut Lang" }] },
      { name: "McDonald's Drop", pieces: [{ item: "Cactus Jack Hoodie", brand: "Travis x McDonald's" }, { item: "Track Pant", brand: "Nike" }, { item: "Air Max 1", brand: "Nike" }] },
      { name: "Festival Rage", pieces: [{ item: "Camo Jacket", brand: "Maharishi" }, { item: "Graphic Tee", brand: "Cactus Jack" }, { item: "Cargo Short", brand: "Nike ACG" }] },
      { name: "La Flame Formal", pieces: [{ item: "Custom Dior Suit", brand: "Dior" }, { item: "Silk Shirt", brand: "Dior" }, { item: "Oxford", brand: "Berluti" }] },
      { name: "Studio Grind", pieces: [{ item: "Zip-Up Hoodie", brand: "Fear of God Essentials" }, { item: "Sweatpant", brand: "Fear of God" }, { item: "New Balance 990", brand: "New Balance" }] },
      { name: "Night Owl", pieces: [{ item: "Leather Biker", brand: "Saint Laurent" }, { item: "Black Skinny Denim", brand: "Amiri" }, { item: "Chelsea Boot", brand: "Rick Owens" }] },
      { name: "Utopia Mode", pieces: [{ item: "Distressed Knit", brand: "Helmut Lang" }, { item: "Cargo Trouser", brand: "Gramicci" }, { item: "Vintage Sneaker", brand: "Adidas" }] },
      { name: "SoHo Heat", pieces: [{ item: "Puffer Vest", brand: "Moncler" }, { item: "Heavyweight Crewneck", brand: "CPFM" }, { item: "Slim Denim", brand: "Nudie Jeans" }] },
      { name: "Backstage Boss", pieces: [{ item: "Vintage Track Jacket", brand: "Adidas" }, { item: "Bandana", brand: "Custom" }, { item: "Retro Basketball Shoe", brand: "Nike" }] },
      { name: "Psychedelic Floral", pieces: [{ item: "Floral Print Shirt", brand: "Prada" }, { item: "Wide-Leg Trouser", brand: "Needles" }, { item: "Platform Sneaker", brand: "Rick Owens" }] },
    ],
  },
  {
    id: "fabolous",
    name: "Fabolous",
    title: "Brooklyn's Best Dressed",
    style: "New York Uptown",
    description: "Fabolous turned Brooklyn hip-hop into a luxury fashion school. Fitted caps, Clarks Wallabees, and just the right amount of bling — effortlessly NY.",
    image: PHOTOS.fabolous,
    accentColor: "#A89070",
    era: "2001–Present",
    knownFor: "NY streetwear, fitted caps, designer denim",
    signatureBrands: ["Gucci", "Versace", "Ralph Lauren", "Clarks", "True Religion"],
    keyPieces: ["Designer denim", "Fitted cap", "Gold chain", "Clarks Desert Boot", "Varsity jacket"],
    vibes: ["NY Uptown", "Luxury Streetwear", "Classic Hip-hop"],
    looks: [
      { name: "Brooklyn Uptown", pieces: [{ item: "Fitted Cap", brand: "New Era" }, { item: "Slim-Fit Denim", brand: "True Religion" }, { item: "Desert Boot", brand: "Clarks" }] },
      { name: "NY Nights", pieces: [{ item: "Leather Jacket", brand: "Versace" }, { item: "Slim Chino", brand: "Gucci" }, { item: "Gold Rope Chain", brand: "Jacob & Co" }] },
      { name: "BK Fitted", pieces: [{ item: "Team Jersey", brand: "Mitchell & Ness" }, { item: "Fitted Cap", brand: "New Era" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Uptown Sunday", pieces: [{ item: "Polo Oxford Shirt", brand: "Ralph Lauren" }, { item: "Clean Denim", brand: "True Religion" }, { item: "Chelsea Boot", brand: "Timberland" }] },
      { name: "Gold Rope Heavy", pieces: [{ item: "Mink Coat", brand: "Custom Furrier" }, { item: "Gold Cuban Chain", brand: "Jacob & Co" }, { item: "Air Jordan 3", brand: "Nike" }] },
      { name: "Summer Cookout", pieces: [{ item: "Linen Polo", brand: "Ralph Lauren" }, { item: "Cargo Short", brand: "Polo Ralph Lauren" }, { item: "Huarache", brand: "Nike" }] },
      { name: "Bodega Run", pieces: [{ item: "Windbreaker", brand: "Tommy Hilfiger" }, { item: "Sweatpant", brand: "Champion" }, { item: "Air Max 95", brand: "Nike" }] },
      { name: "NY Fashion Week", pieces: [{ item: "Double-Breasted Suit", brand: "Tom Ford" }, { item: "Turtleneck", brand: "Zegna" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Court Ready", pieces: [{ item: "Basketball Shorts", brand: "Nike" }, { item: "Retro Polo", brand: "Polo Sport" }, { item: "Air Jordan 11", brand: "Nike" }] },
      { name: "Dinner at Nobu", pieces: [{ item: "Silk Shirt", brand: "Versace" }, { item: "Black Slacks", brand: "Tom Ford" }, { item: "Loafer", brand: "Prada" }] },
      { name: "Club Night", pieces: [{ item: "Balmain Blazer", brand: "Balmain" }, { item: "Black Skinny Jean", brand: "KSUBI" }, { item: "Chelsea Boot", brand: "Saint Laurent" }] },
      { name: "Park Slope Chill", pieces: [{ item: "Coach Jacket", brand: "Carhartt" }, { item: "White Tee", brand: "Hanes" }, { item: "New Balance 990", brand: "New Balance" }] },
    ],
  },
  {
    id: "denzel",
    name: "Denzel Washington",
    title: "Hollywood's Timeless Gentleman",
    style: "Classic American Elegance",
    description: "No trend, no gimmicks — just perfectly cut suits, Italian leather, and the quiet confidence of someone who has always known exactly who they are.",
    image: PHOTOS.denzel,
    accentColor: "#8899A0",
    era: "1980s–Present",
    knownFor: "Perfectly cut suits, understated elegance",
    signatureBrands: ["Tom Ford", "Giorgio Armani", "Brioni", "Zegna", "Gucci"],
    keyPieces: ["Perfectly-cut black suit", "White pocket square", "Oxford shirt", "Italian leather Oxford", "Understated watch"],
    vibes: ["Old Money", "Classic Elegance", "Power Dressing"],
    looks: [
      { name: "Hollywood Formal", pieces: [{ item: "Black Tuxedo", brand: "Tom Ford" }, { item: "French Cuff Shirt", brand: "Zegna" }, { item: "Patent Oxford", brand: "Gucci" }] },
      { name: "Press Day", pieces: [{ item: "Charcoal Suit", brand: "Giorgio Armani" }, { item: "Silk Tie", brand: "Brioni" }, { item: "Oxford Brogue", brand: "Edward Green" }] },
      { name: "Oscar Ceremony", pieces: [{ item: "White Tuxedo Jacket", brand: "Tom Ford" }, { item: "Black Trousers", brand: "Tom Ford" }, { item: "Patent Derby", brand: "Gucci" }] },
      { name: "Golden Globes", pieces: [{ item: "Navy Peaked-Lapel Suit", brand: "Brioni" }, { item: "Powder-Blue Tie", brand: "Charvet" }, { item: "Cap-Toe Oxford", brand: "John Lobb" }] },
      { name: "Premiere Night", pieces: [{ item: "Black Velvet Tuxedo", brand: "Giorgio Armani" }, { item: "White Tuxedo Shirt", brand: "Brioni" }, { item: "Velvet Loafer", brand: "Gucci" }] },
      { name: "Sunday Best", pieces: [{ item: "Grey Flannel Suit", brand: "Zegna" }, { item: "White Linen Shirt", brand: "Charvet" }, { item: "Suede Loafer", brand: "Edward Green" }] },
      { name: "Red Carpet Quiet", pieces: [{ item: "Midnight Navy Suit", brand: "Tom Ford" }, { item: "Knit Tie", brand: "The Row" }, { item: "Oxford Brogue", brand: "Berluti" }] },
      { name: "Press Junket", pieces: [{ item: "Camel Cashmere Overcoat", brand: "Loro Piana" }, { item: "Charcoal Suit", brand: "Armani" }, { item: "Leather Chelsea Boot", brand: "Gucci" }] },
      { name: "Gentleman Casual", pieces: [{ item: "Polo Shirt", brand: "Loro Piana" }, { item: "Slim Chino", brand: "Ralph Lauren Purple Label" }, { item: "Suede Loafer", brand: "Tod's" }] },
      { name: "Master Class", pieces: [{ item: "Tweed Sport Coat", brand: "Ralph Lauren" }, { item: "Roll-Neck Knit", brand: "Brunello Cucinelli" }, { item: "Oxford Trouser", brand: "Zegna" }] },
      { name: "Awards Season", pieces: [{ item: "Black Three-Piece Suit", brand: "Tom Ford" }, { item: "Silk Pocket Square", brand: "Hermès" }, { item: "Patent Oxford", brand: "Berluti" }] },
      { name: "Casual Friday", pieces: [{ item: "Cashmere Crewneck", brand: "Loro Piana" }, { item: "Slim Dark Denim", brand: "AG Jeans" }, { item: "Clean White Sneaker", brand: "Common Projects" }] },
    ],
  },
  {
    id: "snoop",
    name: "Snoop Dogg",
    title: "Long Beach's Most Stylish OG",
    style: "California Cool",
    description: "The OG of laid-back California luxury. Snoop evolved from Doggystyle Dickies to Gucci tracksuits — always relaxed, always dripping, always himself.",
    image: PHOTOS.snoop,
    accentColor: "#7A9E7E",
    era: "1992–Present",
    knownFor: "Tracksuits, braids, California 420 luxury",
    signatureBrands: ["Gucci", "Adidas", "Death Row", "Snoop Dogg x Skechers", "Coach"],
    keyPieces: ["Velour tracksuit", "G-funk cap", "Gucci loafer", "Gold rope", "Croc-skin accessories"],
    vibes: ["California Cool", "Old School Luxe", "Laid-back Hip-hop"],
    looks: [
      { name: "West Coast OG", pieces: [{ item: "Gucci Velour Tracksuit", brand: "Gucci" }, { item: "Bucket Hat", brand: "Kangol" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Gin & Juice Night", pieces: [{ item: "Silk Bowling Shirt", brand: "Dries Van Noten" }, { item: "Wide-leg Linen Trouser", brand: "The Row" }, { item: "Suede Loafer", brand: "Gucci" }] },
      { name: "420 Grateful", pieces: [{ item: "Tie-Dye Tee", brand: "Death Row Era" }, { item: "Dickies Pant", brand: "Dickies" }, { item: "Vans Old Skool", brand: "Vans" }] },
      { name: "Doggfather Luxe", pieces: [{ item: "Silk Gucci Tracksuit", brand: "Gucci" }, { item: "Bucket Hat", brand: "Kangol" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Long Beach Summer", pieces: [{ item: "Hawaiian Shirt", brand: "Reyn Spooner" }, { item: "Linen Pant", brand: "Loro Piana" }, { item: "Loafer", brand: "Gucci" }] },
      { name: "Super Bowl Half", pieces: [{ item: "Black Tracksuit", brand: "Adidas" }, { item: "White Trainers", brand: "Adidas" }, { item: "Kufi Cap", brand: "Custom" }] },
      { name: "California Dreamin", pieces: [{ item: "Logo Hoodie", brand: "Death Row Records" }, { item: "Slim Jogger", brand: "Adidas" }, { item: "Cortez", brand: "Nike" }] },
      { name: "Coach Snoop", pieces: [{ item: "Sports Polo", brand: "Adidas" }, { item: "Coaching Short", brand: "Adidas" }, { item: "New Balance 574", brand: "New Balance" }] },
      { name: "BET Awards", pieces: [{ item: "Purple Velvet Blazer", brand: "Saint Laurent" }, { item: "Black Turtleneck", brand: "Amiri" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Smoke & Mirrors", pieces: [{ item: "Shaggy Fur Coat", brand: "Custom" }, { item: "Black Leather Trouser", brand: "The Row" }, { item: "Patent Loafer", brand: "Gucci" }] },
      { name: "Cali Gold", pieces: [{ item: "White Linen Set", brand: "Loro Piana" }, { item: "Gold Chain", brand: "Jacob & Co" }, { item: "Espadrille", brand: "Rivieras" }] },
      { name: "Snoopzilla Funk", pieces: [{ item: "Sequin Jacket", brand: "Custom" }, { item: "Platform Boot", brand: "Sergio Rossi" }, { item: "Gold Medallion", brand: "Custom" }] },
    ],
  },
  {
    id: "jeezy",
    name: "Young Jeezy",
    title: "Atlanta Trap Royalty",
    style: "ATL Trap Luxe",
    description: "Jeezy turned Atlanta streets into a fashion statement. He brought the white tee movement to its peak and proved that trap music and luxury fashion were never mutually exclusive.",
    image: PHOTOS.jeezy,
    accentColor: "#A0A0A0",
    era: "2005–Present",
    knownFor: "Snowflake era, designer belts, ATL drip",
    signatureBrands: ["Versace", "Balenciaga", "Balmain", "Moncler", "Iceberg"],
    keyPieces: ["Moncler puffer", "Versace belt", "White tee", "Nike Air Force 1", "Gold Cuban chain"],
    vibes: ["Trap Luxe", "Luxury Streetwear", "ATL"],
    looks: [
      { name: "Snowman Season", pieces: [{ item: "Moncler Down Puffer", brand: "Moncler" }, { item: "Designer Denim", brand: "True Religion" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Corporate Thuggin", pieces: [{ item: "Versace Blazer", brand: "Versace" }, { item: "Balmain Jeans", brand: "Balmain" }, { item: "Luxury Boot", brand: "Giuseppe Zanotti" }] },
      { name: "ATL All-Star", pieces: [{ item: "White Air Force 1", brand: "Nike" }, { item: "White Tee", brand: "Fruit of the Loom" }, { item: "Designer Denim", brand: "Evisu" }] },
      { name: "Trap or Die", pieces: [{ item: "Moncler Vest", brand: "Moncler" }, { item: "Champion Hoodie", brand: "Champion" }, { item: "Air Jordan 11", brand: "Nike" }] },
      { name: "Certified Gansta", pieces: [{ item: "Iceberg Sweater", brand: "Iceberg" }, { item: "Dark Denim", brand: "True Religion" }, { item: "Timberland Boot", brand: "Timberland" }] },
      { name: "Business of Rap", pieces: [{ item: "Double-Breasted Suit", brand: "Tom Ford" }, { item: "White Spread Collar Shirt", brand: "Brioni" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Versace Everything", pieces: [{ item: "Baroque Shirt", brand: "Versace" }, { item: "Black Slim Pant", brand: "Gucci" }, { item: "Chelsea Boot", brand: "Versace" }] },
      { name: "Gold Standard", pieces: [{ item: "Mink Coat", brand: "Custom" }, { item: "Cuban Link Chain", brand: "Jacob & Co" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Snowflake Era", pieces: [{ item: "White Moncler Puffer", brand: "Moncler" }, { item: "White Tee", brand: "Hanes" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "ATL Uptown", pieces: [{ item: "Polo Oxford", brand: "Ralph Lauren" }, { item: "Straight Denim", brand: "True Religion" }, { item: "Boat Shoe", brand: "Timberland" }] },
      { name: "Label Boss", pieces: [{ item: "Pinstripe Suit", brand: "Brioni" }, { item: "Silk Tie", brand: "Hermès" }, { item: "Italian Loafer", brand: "Berluti" }] },
      { name: "Street General", pieces: [{ item: "Army-Green Camo Jacket", brand: "G-Star" }, { item: "Heavyweight Hoodie", brand: "Acne Studios" }, { item: "Cargo Pant", brand: "Carhartt" }] },
    ],
  },
  {
    id: "zendaya",
    name: "Zendaya",
    title: "Fashion's Reigning Queen",
    style: "Avant-garde Theatre",
    description: "From spider-web Valentino to robotic Mugler at the Met — Zendaya's stylist Law Roach transformed her into fashion's greatest theatrical act. Every look tells a story.",
    image: PHOTOS.zendaya,
    accentColor: "#D4A8B0",
    era: "2014–Present",
    knownFor: "Law Roach styling, Valentino, Met Gala moments",
    signatureBrands: ["Valentino", "Mugler", "Versace", "Louis Vuitton", "Armani"],
    keyPieces: ["Sculptural gown", "Spider-web heels", "Chainmail dress", "Romantic corset", "Statement jewelry"],
    vibes: ["Avant-garde", "Theatrical", "High Fashion"],
    looks: [
      { name: "Dune Premiere", pieces: [{ item: "Column Gown", brand: "Valentino" }, { item: "Statement Earrings", brand: "Bulgari" }, { item: "Strappy Heel", brand: "Roger Vivier" }] },
      { name: "Challengers", pieces: [{ item: "Colourblock Polo Dress", brand: "Louis Vuitton" }, { item: "Visor", brand: "Nike" }, { item: "Platform Sneaker", brand: "Adidas" }] },
      { name: "Spider-Man Edit", pieces: [{ item: "Chainmail Mini Dress", brand: "Valentino" }, { item: "Web-Detail Stiletto", brand: "Custom" }, { item: "Drop Earring", brand: "Tiffany & Co" }] },
      { name: "Euphoria Glam", pieces: [{ item: "Crystal Crop Top", brand: "Mugler" }, { item: "High-Waist Wide Leg", brand: "Tom Ford" }, { item: "Strappy Sandal", brand: "Amina Muaddi" }] },
      { name: "Valentino Roma", pieces: [{ item: "Hot-Pink Couture Gown", brand: "Valentino Haute Couture" }, { item: "Long White Glove", brand: "Custom" }, { item: "Crystal Heel", brand: "Valentino" }] },
      { name: "Met Gala Robot", pieces: [{ item: "Silver Robot Suit", brand: "Mugler Archive" }, { item: "Glove Boot", brand: "Mugler" }, { item: "Crystal Crown", brand: "Custom" }] },
      { name: "Joan of Arc", pieces: [{ item: "Armour-Inspired Gown", brand: "Versace" }, { item: "Chainmail Veil", brand: "Custom" }, { item: "Flat Thong Sandal", brand: "Valentino" }] },
      { name: "Tennis Princess", pieces: [{ item: "Pleated Mini Dress", brand: "Louis Vuitton" }, { item: "Knit Sock", brand: "Falke" }, { item: "Platform Tennis Shoe", brand: "Nike" }] },
      { name: "Old Hollywood Z", pieces: [{ item: "Black Column Gown", brand: "The Row" }, { item: "Opera Gloves", brand: "Fownes" }, { item: "Strappy Heel", brand: "Roger Vivier" }] },
      { name: "Retro Action", pieces: [{ item: "70s Floral Jumpsuit", brand: "Etro" }, { item: "Platform Sandal", brand: "Saint Laurent" }, { item: "Gold Hoop Earring", brand: "Jennifer Fisher" }] },
      { name: "Z By Day", pieces: [{ item: "Wide-Leg Denim", brand: "Agolde" }, { item: "Cropped Blazer", brand: "Toteme" }, { item: "Kitten-Heel Loafer", brand: "The Row" }] },
      { name: "Mugler Muse", pieces: [{ item: "Spirale Gown", brand: "Mugler" }, { item: "Pointed Stiletto", brand: "Louboutin" }, { item: "Sculptural Cuff", brand: "Bottega Veneta" }] },
    ],
  },
  {
    id: "harry",
    name: "Harry Styles",
    title: "The Gender-Fluid Rock God",
    style: "Vintage Eclectic Glamour",
    description: "Harry proved that pearl necklaces, feather boas, and Gucci jumpsuits belong on everyone. A vintage eclectic spirit that's part Elton John, part Mick Jagger, part utterly himself.",
    image: PHOTOS.harry,
    accentColor: "#C4A8C4",
    era: "2017–Present",
    knownFor: "Gucci muse, gender-fluid, vintage, feather boa",
    signatureBrands: ["Gucci", "Vivienne Westwood", "Palomo Spain", "JW Anderson", "Pleasing"],
    keyPieces: ["Flared trouser", "Feather boa", "Pearl necklace", "Platform Chelsea boot", "Colourful suit"],
    vibes: ["Eclectic", "Gender-Fluid", "Vintage Glam", "70s Revival"],
    looks: [
      { name: "Golden Hour", pieces: [{ item: "Colourblock Suit", brand: "Gucci" }, { item: "Ruffled Blouse", brand: "JW Anderson" }, { item: "Platform Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Fine Line Era", pieces: [{ item: "Pearl Necklace", brand: "Mikimoto" }, { item: "High-Waist Flare", brand: "Palomo Spain" }, { item: "Feather Jacket", brand: "Gucci" }] },
      { name: "Watermelon Sugar", pieces: [{ item: "Fishnet Vest", brand: "JW Anderson" }, { item: "Vintage Flare Trouser", brand: "Levi's Vintage" }, { item: "Platform Wedge", brand: "Stella McCartney" }] },
      { name: "Spheres Tour", pieces: [{ item: "Crystal Jumpsuit", brand: "Gucci" }, { item: "Elton-Era Glasses", brand: "Custom" }, { item: "Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Coachella King", pieces: [{ item: "Sheer Floral Blouse", brand: "Gucci" }, { item: "High-Waist Linen Short", brand: "Palomo Spain" }, { item: "Cowboy Boot", brand: "Vintage" }] },
      { name: "SNL Boa", pieces: [{ item: "Sequin Blazer", brand: "Gucci" }, { item: "Feather Boa", brand: "Custom" }, { item: "Velvet Flare", brand: "Gucci" }] },
      { name: "Gucci House", pieces: [{ item: "Gucci Cardigan Suit", brand: "Gucci" }, { item: "White Tee", brand: "Sunspel" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
      { name: "Harry's House", pieces: [{ item: "Patchwork Blazer", brand: "JW Anderson" }, { item: "Wide-Leg Trouser", brand: "Palomo Spain" }, { item: "Flatform Boot", brand: "Vivienne Westwood" }] },
      { name: "Tokyo Vintage", pieces: [{ item: "Vintage Leather Jacket", brand: "Vintage" }, { item: "Graphic Tee", brand: "Vintage" }, { item: "Straight Crop Trouser", brand: "Gucci" }] },
      { name: "Night Glitter", pieces: [{ item: "Full-Sequin Suit", brand: "Gucci" }, { item: "Sheer Blouse", brand: "Palomo Spain" }, { item: "Platform Chelsea Boot", brand: "Vivienne Westwood" }] },
      { name: "Garden Party", pieces: [{ item: "Floral Tea-Length Dress", brand: "Gucci Custom" }, { item: "Platform Mary Jane", brand: "Vivienne Westwood" }, { item: "Floral Crown", brand: "Custom" }] },
      { name: "Airport Departure", pieces: [{ item: "Oversized Shearling", brand: "Gucci" }, { item: "Wide-Leg Trouser", brand: "Toteme" }, { item: "Chelsea Boot", brand: "Vivienne Westwood" }] },
    ],
  },
  {
    id: "pharrell",
    name: "Pharrell Williams",
    title: "The Eternal Skater Visionary",
    style: "Eclectic Luxury Supreme",
    description: "Pharrell invented the massive Vivienne Westwood hat moment and now runs Louis Vuitton Men's. His style is an art installation — Chanel, skateboarding, Billionaire Boys Club, and the brain of a genius.",
    image: PHOTOS.pharrell,
    accentColor: "#C6A75E",
    era: "1999–Present",
    knownFor: "BBC Ice Cream, LV Men's Director, hat collector",
    signatureBrands: ["Louis Vuitton", "Chanel", "Billionaire Boys Club", "adidas", "Vivienne Westwood"],
    keyPieces: ["Giant western hat", "BBC logo tee", "Adidas Human Race", "Chanel accessories", "Custom LV sneaker"],
    vibes: ["Eclectic Luxury", "Skate Culture", "Art World"],
    looks: [
      { name: "LV Creative Director", pieces: [{ item: "Custom LV Suit", brand: "Louis Vuitton" }, { item: "Platform Sneaker", brand: "LV" }, { item: "Diamond Earring", brand: "Jacob & Co" }] },
      { name: "BBC OG", pieces: [{ item: "BBC Logo Tee", brand: "Billionaire Boys Club" }, { item: "Slim Jogger", brand: "Adidas" }, { item: "Human Race Sneaker", brand: "Adidas" }] },
      { name: "Vivienne Hat", pieces: [{ item: "Massive Tartan Hat", brand: "Vivienne Westwood" }, { item: "Tweed Jacket", brand: "Chanel" }, { item: "White Jeans", brand: "A.P.C." }] },
      { name: "Human Race Launch", pieces: [{ item: "Human Race Sneaker", brand: "Adidas x Pharrell" }, { item: "Graphic Tee", brand: "NERD" }, { item: "Slim Jogger", brand: "Adidas" }] },
      { name: "Skateboard P", pieces: [{ item: "Logo Hoodie", brand: "BBC Ice Cream" }, { item: "Skate Pant", brand: "Dickies" }, { item: "Skate Shoe", brand: "Vans" }] },
      { name: "Grammy Cowboy", pieces: [{ item: "Western Hat", brand: "Vivienne Westwood" }, { item: "Denim Jacket", brand: "Vintage Levi's" }, { item: "Cowboy Boot", brand: "Custom" }] },
      { name: "Chanel Bro", pieces: [{ item: "Tweed Jacket", brand: "Chanel" }, { item: "Chain Detail Pant", brand: "Chanel" }, { item: "Logo Sneaker", brand: "Chanel" }] },
      { name: "LV Men's FW", pieces: [{ item: "Tailored Coat", brand: "Louis Vuitton" }, { item: "Printed Shirt", brand: "Louis Vuitton" }, { item: "LV Sneaker", brand: "Louis Vuitton" }] },
      { name: "Art Basel", pieces: [{ item: "Colourblock Jacket", brand: "Kenzo" }, { item: "Wide-Leg Corduroy", brand: "Needles" }, { item: "Platform Sneaker", brand: "Sacai x Nike" }] },
      { name: "N.E.R.D. Rock", pieces: [{ item: "Vintage Band Tee", brand: "NERD Vintage" }, { item: "Slim Denim", brand: "Nudie" }, { item: "Vintage Sneaker", brand: "Adidas" }] },
      { name: "Neptune Fresh", pieces: [{ item: "Pastel Linen Set", brand: "Loro Piana" }, { item: "Massive Straw Hat", brand: "Vivienne Westwood" }, { item: "Platform Loafer", brand: "Louis Vuitton" }] },
      { name: "Happy Days", pieces: [{ item: "White Linen Suit", brand: "Loro Piana" }, { item: "Gucci Scarf", brand: "Gucci" }, { item: "Moccasin", brand: "Gucci" }] },
    ],
  },
  {
    id: "audrey",
    name: "Audrey Hepburn",
    title: "Hollywood's Eternal Muse",
    style: "Classic Hollywood Elegance",
    description: "The little black dress, the Givenchy trench, the Breakfast at Tiffany's neckline. Audrey's wardrobe defined Hollywood glamour without ever trying to compete — it simply arrived and stayed.",
    image: PHOTOS.audrey,
    accentColor: "#C0B090",
    era: "1950s–1960s",
    knownFor: "Givenchy muse, the LBD, Holly Golightly aesthetic",
    signatureBrands: ["Givenchy", "Balenciaga", "Ferragamo", "Valentino", "Tiffany & Co"],
    keyPieces: ["The little black dress", "White gloves", "Cigarette trouser", "Ballet flat", "Cat-eye sunglasses"],
    vibes: ["Classic Elegance", "Old Money", "Timeless"],
    looks: [
      { name: "Breakfast at Tiffany's", pieces: [{ item: "Black Sheath Dress", brand: "Givenchy" }, { item: "Long White Gloves", brand: "Fownes" }, { item: "Pearl Drop Earrings", brand: "Tiffany & Co" }] },
      { name: "Roman Holiday", pieces: [{ item: "Cigarette Trouser", brand: "Givenchy" }, { item: "Striped Blouse", brand: "Givenchy" }, { item: "Capri Ballet Flat", brand: "Ferragamo" }] },
      { name: "Sabrina Chic", pieces: [{ item: "Strapless Organza Gown", brand: "Givenchy" }, { item: "Elbow-Length Glove", brand: "Dents" }, { item: "Kitten Heel", brand: "Ferragamo" }] },
      { name: "War & Peace", pieces: [{ item: "Cashmere Twinset", brand: "Givenchy" }, { item: "Cigarette Trouser", brand: "Givenchy" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Paris Enchantment", pieces: [{ item: "Apple-Green Empire Gown", brand: "Givenchy Haute Couture" }, { item: "Long White Glove", brand: "Custom" }, { item: "Strappy Heel", brand: "Givenchy" }] },
      { name: "Funny Face", pieces: [{ item: "Red Trapeze Coat", brand: "Balenciaga" }, { item: "Black Roll-Neck", brand: "Givenchy" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Garden Tea", pieces: [{ item: "Broderie Anglaise Sundress", brand: "Givenchy" }, { item: "Wide-Brim Straw Hat", brand: "Custom" }, { item: "Espadrille Wedge", brand: "Ferragamo" }] },
      { name: "Charade Style", pieces: [{ item: "Red Plaid Suit Jacket", brand: "Givenchy" }, { item: "Slim Trouser", brand: "Givenchy" }, { item: "Oxford Pump", brand: "Ferragamo" }] },
      { name: "Simple Elegance", pieces: [{ item: "White Boat-Neck Top", brand: "Givenchy" }, { item: "Slim Black Trouser", brand: "Givenchy" }, { item: "Pearl Necklace", brand: "Tiffany & Co" }] },
      { name: "Princess Charity", pieces: [{ item: "Blush A-Line Gown", brand: "Valentino" }, { item: "Opera Glove", brand: "Fownes" }, { item: "Slingback Heel", brand: "Ferragamo" }] },
      { name: "Audrey At Work", pieces: [{ item: "White Wrap Blouse", brand: "Givenchy" }, { item: "Cropped Trouser", brand: "Givenchy" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Tiffany's Window", pieces: [{ item: "LBD", brand: "Givenchy" }, { item: "Cat-Eye Sunglasses", brand: "Oliver Goldsmith" }, { item: "Block Heel Pump", brand: "Ferragamo" }] },
    ],
  },
  {
    id: "marilyn",
    name: "Marilyn Monroe",
    title: "The Original Icon",
    style: "Old Hollywood Glamour",
    description: "She wore nothing but Chanel No. 5 and a smile, then wore the most famous dress in American history. Marilyn's sensuality was couture — calibrated, conscious, and entirely her own.",
    image: PHOTOS.marilyn,
    accentColor: "#F0D8C8",
    era: "1950s–1960s",
    knownFor: "Happy Birthday Mr. President gown, the white dress, Chanel",
    signatureBrands: ["Jean Louis", "Travilla", "Chanel", "Norman Norell", "Emilio Pucci"],
    keyPieces: ["Sequined column gown", "Red lips", "White halter dress", "Mink stole", "Diamond choker"],
    vibes: ["Old Hollywood", "Glamour", "Sensual Luxury"],
    looks: [
      { name: "Happy Birthday, Mr. President", pieces: [{ item: "Nude Sequined Column Gown", brand: "Jean Louis" }, { item: "Diamond Bracelet", brand: "Harry Winston" }, { item: "Barely-There Heel", brand: "Custom" }] },
      { name: "Manhattan Blonde", pieces: [{ item: "White Halter Dress", brand: "Travilla" }, { item: "Red Lip (Revlon)", brand: "Revlon" }, { item: "Block Heel Mule", brand: "Ferragamo" }] },
      { name: "Some Like It Hot", pieces: [{ item: "White Strapless Gown", brand: "Jean Louis" }, { item: "Diamond Drop Earring", brand: "Harry Winston" }, { item: "White Mule Heel", brand: "Custom" }] },
      { name: "Gentlemen Prefer", pieces: [{ item: "Pink Satin Strapless Gown", brand: "Travilla" }, { item: "Fur Stole", brand: "Custom" }, { item: "Platform Sandal", brand: "Custom" }] },
      { name: "Bus Stop Dream", pieces: [{ item: "Polka-Dot Sundress", brand: "Custom" }, { item: "Wide-Brim Sun Hat", brand: "Custom" }, { item: "Flat Espadrille", brand: "Custom" }] },
      { name: "Misfits", pieces: [{ item: "Pencil Skirt", brand: "Custom" }, { item: "Black Turtleneck", brand: "Custom" }, { item: "Kitten Heel", brand: "Ferragamo" }] },
      { name: "Diamond Girl", pieces: [{ item: "Hot-Pink Strapless Gown", brand: "Travilla" }, { item: "Long Gloves", brand: "Custom" }, { item: "Diamond Drop Earring", brand: "Harry Winston" }] },
      { name: "Marilyn at the Beach", pieces: [{ item: "Gold Lamé Bikini", brand: "Custom" }, { item: "White Linen Shirt", brand: "Custom" }, { item: "Flat Sandal", brand: "Custom" }] },
      { name: "Studio Portrait", pieces: [{ item: "Black Cocktail Dress", brand: "Norman Norell" }, { item: "Mink Stole", brand: "Custom" }, { item: "Stiletto", brand: "Ferragamo" }] },
      { name: "Norma Jean Casual", pieces: [{ item: "Cropped Sweater", brand: "Custom" }, { item: "High-Waist Trouser", brand: "Custom" }, { item: "Ballet Flat", brand: "Ferragamo" }] },
      { name: "Korea Pinup", pieces: [{ item: "Military Parka", brand: "Custom" }, { item: "High-Waist Jean Short", brand: "Custom" }, { item: "Ankle Boot", brand: "Custom" }] },
      { name: "Red Carpet Marilyn", pieces: [{ item: "Cream Pleated Halter", brand: "Travilla" }, { item: "Diamond Choker", brand: "Harry Winston" }, { item: "Open-Toe Slingback", brand: "Ferragamo" }] },
    ],
  },
  {
    id: "ladygaga",
    name: "Lady Gaga",
    title: "Fashion's Greatest Provocateur",
    style: "Theatrical Avant-garde",
    description: "Meat dresses, nine-inch armadillo shoes, Alexander McQueen bubbles — Gaga turned fashion into performance art and performance into fashion. The boundary doesn't exist for her.",
    image: PHOTOS.ladygaga,
    accentColor: "#B0A0C8",
    era: "2008–Present",
    knownFor: "McQueen Armadillo shoes, Haus of Gaga, Met Gala theatrics",
    signatureBrands: ["Alexander McQueen", "Versace", "Valentino", "Atelier Versace", "Schiaparelli"],
    keyPieces: ["Armadillo shoe (McQueen)", "Platinum wig", "Crystal bodysuit", "Architectural headpiece", "Avant-garde gloves"],
    vibes: ["Avant-garde", "Theatrical", "Provocation"],
    looks: [
      { name: "Bad Romance", pieces: [{ item: "Ivory Architectural Gown", brand: "Schiaparelli" }, { item: "Crystal Headpiece", brand: "Custom" }, { item: "Platform Heel", brand: "Alexander McQueen" }] },
      { name: "Joanne Tour", pieces: [{ item: "Pink Cowboy Hat", brand: "Haus of Gaga" }, { item: "Rhinestone Bodysuit", brand: "Atelier Versace" }, { item: "Thigh-High Boot", brand: "Versace" }] },
      { name: "Applause Era", pieces: [{ item: "Sculptural Black Bodysuit", brand: "Versace" }, { item: "Architectural Headpiece", brand: "Custom" }, { item: "Platform Heel", brand: "Alexander McQueen" }] },
      { name: "ARTPOP Launch", pieces: [{ item: "Botticelli-Inspired Gown", brand: "Atelier Versace" }, { item: "Crystal Tiara", brand: "Swarovski" }, { item: "Embellished Heel", brand: "Custom" }] },
      { name: "A Star Is Born", pieces: [{ item: "Sequin Long Gown", brand: "Custom" }, { item: "Teardrop Earrings", brand: "Custom" }, { item: "Stiletto", brand: "Louboutin" }] },
      { name: "Chromatica Ball", pieces: [{ item: "Pink Latex Bodysuit", brand: "Haus Labs x Mugler" }, { item: "Pink Platform Boot", brand: "Custom" }, { item: "Crystal Armor Glove", brand: "Custom" }] },
      { name: "Super Bowl XLVII", pieces: [{ item: "Red Spiked Bodysuit", brand: "Custom" }, { item: "Thigh-High Red Boot", brand: "Custom" }, { item: "Diamond Cuff", brand: "Harry Winston" }] },
      { name: "Met Gala Camp", pieces: [{ item: "Architectural Gown", brand: "Brandon Maxwell" }, { item: "Custom Headpiece", brand: "Brandon Maxwell" }, { item: "Clear Platform Heel", brand: "Custom" }] },
      { name: "Oscars Glamour", pieces: [{ item: "Periwinkle Satin Ball Gown", brand: "Alexander McQueen" }, { item: "Diamond Jewelry", brand: "Tiffany & Co" }, { item: "Strappy Heel", brand: "Custom" }] },
      { name: "Joker Night", pieces: [{ item: "Purple Long-Sleeve Gown", brand: "Valentino" }, { item: "Statement Red Lip", brand: "Haus Labs" }, { item: "Metallic Stiletto", brand: "Louboutin" }] },
      { name: "VMA Meat Dress", pieces: [{ item: "Meat-Sculpted Gown", brand: "Franc Fernandez" }, { item: "Meat Platform Heel", brand: "Franc Fernandez" }, { item: "Meat Hat (Archive)", brand: "Franc Fernandez" }] },
      { name: "Street Gaga", pieces: [{ item: "Sequin Minidress", brand: "Versace" }, { item: "Oversize Shades", brand: "GCDS" }, { item: "Platform Sneaker", brand: "Versace" }] },
    ],
  },
  {
    id: "chloe",
    name: "Chloé Zhao",
    title: "Hollywood's Quiet Revolutionary",
    style: "Understated Nomadic",
    description: "The Oscar-winning director who wore jeans to the Academy Awards. Chloé's style is deliberate minimalism — the anti-Hollywood statement that said more than any couture gown.",
    image: PHOTOS.chloe,
    accentColor: "#8A9E8A",
    era: "2018–Present",
    knownFor: "Nomadic minimalism, jeans at the Oscars, quiet statement",
    signatureBrands: ["The Row", "Lemaire", "Toteme", "COS", "Acne Studios"],
    keyPieces: ["Relaxed denim", "Cashmere knit", "Simple leather boot", "Linen trouser", "Minimal jewellery"],
    vibes: ["Quiet Luxury", "Minimalism", "Nomadic"],
    looks: [
      { name: "Oscar Night Rebel", pieces: [{ item: "High-Rise Denim", brand: "Agolde" }, { item: "Cashmere Knit", brand: "The Row" }, { item: "Chelsea Boot", brand: "The Row" }] },
      { name: "Eternals Press", pieces: [{ item: "Wide-Leg Linen Trouser", brand: "Toteme" }, { item: "Silk Blouse", brand: "Equipment" }, { item: "Leather Mule", brand: "Lemaire" }] },
      { name: "Sundance Quiet", pieces: [{ item: "Camel Parka", brand: "Acne Studios" }, { item: "Slim Denim", brand: "Agolde" }, { item: "Suede Boot", brand: "The Row" }] },
      { name: "BAFTA Minimalist", pieces: [{ item: "Black Wide-Leg Trouser", brand: "The Row" }, { item: "Black Cashmere Turtleneck", brand: "The Row" }, { item: "Ballet Flat", brand: "The Row" }] },
      { name: "Nomadland Spirit", pieces: [{ item: "Indigo Chambray Shirt", brand: "Lemaire" }, { item: "Relaxed Canvas Trouser", brand: "Lemaire" }, { item: "Desert Boot", brand: "Clarks" }] },
      { name: "Cannes Nature", pieces: [{ item: "Linen Wrap Dress", brand: "Toteme" }, { item: "Flat Sandal", brand: "Birkenstock" }, { item: "Minimal Gold Ring", brand: "Sophie Buhai" }] },
      { name: "LA Producer", pieces: [{ item: "Tailored Blazer", brand: "COS" }, { item: "White Tee", brand: "Sunspel" }, { item: "Simple Sneaker", brand: "Common Projects" }] },
      { name: "Brooklyn Loft", pieces: [{ item: "Knit Cardigan", brand: "Acne Studios" }, { item: "Wide-Leg Trouser", brand: "Lemaire" }, { item: "Chelsea Boot", brand: "Acne Studios" }] },
      { name: "Festival Circuit", pieces: [{ item: "Shearling Jacket", brand: "Ganni" }, { item: "Slim Denim", brand: "A.P.C." }, { item: "Sneaker", brand: "Veja" }] },
      { name: "Academy Member", pieces: [{ item: "Ivory Silk Blouse", brand: "Tibi" }, { item: "High-Rise Trouser", brand: "Toteme" }, { item: "Pointed Flat", brand: "The Row" }] },
      { name: "Behind Camera", pieces: [{ item: "Field Jacket", brand: "Filson" }, { item: "Military Trouser", brand: "Acne Studios" }, { item: "Work Boot", brand: "Red Wing" }] },
      { name: "Golden Globe", pieces: [{ item: "Stone-Grey Wrap Coat", brand: "Lemaire" }, { item: "Slim Trouser", brand: "The Row" }, { item: "Ankle Boot", brand: "Acne Studios" }] },
    ],
  },
  {
    id: "asap",
    name: "A$AP Rocky",
    title: "Fashion's Crown Prince",
    style: "Luxury Art-world Streetwear",
    description: "He wore Raf Simons before anyone knew the name. Rocky became the rapper-as-fashion-editor archetype — his Met Gala quilted vest and avant-garde layering blurred fashion and art.",
    image: PHOTOS.asap,
    accentColor: "#9898A8",
    era: "2011–Present",
    knownFor: "Raf Simons OG, fashion week front-row king, art-world meets hip-hop",
    signatureBrands: ["Raf Simons", "Gucci", "Calvin Klein", "Rick Owens", "Dior Homme"],
    keyPieces: ["Printed scarf", "Quilted vest", "Chunky brogues", "Kilt / wrap skirt", "Layered chains"],
    vibes: ["Luxury Streetwear", "Art World", "Avant-garde"],
    looks: [
      { name: "Raf Era", pieces: [{ item: "Printed Knit Sweater", brand: "Raf Simons" }, { item: "Slim Denim", brand: "Raf Simons" }, { item: "Chunky Brogue", brand: "Raf Simons" }] },
      { name: "Gucci Head", pieces: [{ item: "Print Silk Shirt", brand: "Gucci" }, { item: "Vintage Denim", brand: "Levi's Vintage" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
      { name: "Dior Homme", pieces: [{ item: "Fitted Suit", brand: "Dior Homme" }, { item: "Slim Tie", brand: "Dior" }, { item: "Oxford Shoe", brand: "Dior" }] },
      { name: "Calvin Klein", pieces: [{ item: "Minimalist White Tee", brand: "Calvin Klein" }, { item: "Slim Denim", brand: "Calvin Klein" }, { item: "White Sneaker", brand: "Calvin Klein" }] },
      { name: "Met Gala Quilt", pieces: [{ item: "Quilted Patchwork Vest", brand: "Custom" }, { item: "Slim Trouser", brand: "Prada" }, { item: "Chelsea Boot", brand: "Raf Simons" }] },
      { name: "Flower Boy", pieces: [{ item: "Floral Shirt", brand: "Gucci" }, { item: "Wide-Leg Cream Trouser", brand: "Prada" }, { item: "Chunky Sandal", brand: "Marni" }] },
      { name: "Art Basel Miami", pieces: [{ item: "Graphic Tee", brand: "Supreme x CDG" }, { item: "Layered Gold Chain", brand: "Custom" }, { item: "Baggy Trouser", brand: "ERL" }] },
      { name: "Harlem Prep", pieces: [{ item: "Navy Blazer", brand: "Ralph Lauren" }, { item: "Plaid Shirt", brand: "Ralph Lauren" }, { item: "Horsebit Loafer", brand: "Gucci" }] },
      { name: "Fashion Forward", pieces: [{ item: "Deconstructed Jacket", brand: "Maison Margiela" }, { item: "Layered Kilt", brand: "Vivienne Westwood" }, { item: "Boot", brand: "Margiela" }] },
      { name: "Rick World", pieces: [{ item: "Long Leather Coat", brand: "Rick Owens" }, { item: "Black Turtleneck", brand: "Rick Owens" }, { item: "DRKSHDW Sneaker", brand: "Rick Owens" }] },
      { name: "Brooklyn Finest", pieces: [{ item: "Stone Island Jacket", brand: "Stone Island" }, { item: "Cargo Trouser", brand: "Maharishi" }, { item: "Retro Sneaker", brand: "New Balance" }] },
      { name: "Fenty Flame", pieces: [{ item: "Leather Jacket", brand: "Amiri" }, { item: "Slim Denim", brand: "Amiri" }, { item: "Leather Sneaker", brand: "Amiri" }] },
    ],
  },
  {
    id: "lewis",
    name: "Lewis Hamilton",
    title: "Formula One's Fashion Rebel",
    style: "Race-day Luxury",
    description: "Lewis broke F1's stuffy dress code and never looked back. Custom Tommy Hilfiger, Burberry editorial shoots, and front-row fashion week appearances made him the sport's first true fashion icon.",
    image: PHOTOS.lewis,
    accentColor: "#9898A8",
    era: "2009–Present",
    knownFor: "Tommy Hilfiger collab, Burberry, Valentino, fashion week regular",
    signatureBrands: ["Tommy Hilfiger x Lewis", "Valentino", "Burberry", "Mercedes-AMG gear", "Chrome Hearts"],
    keyPieces: ["Custom race suit", "Chrome Hearts sunglasses", "Statement coat", "Custom sneakers", "Gold chain"],
    vibes: ["Race-day Luxe", "Power Dressing", "Street Couture"],
    looks: [
      { name: "Paddock Ready", pieces: [{ item: "Custom Embroidered Jacket", brand: "Tommy x Lewis" }, { item: "Wide-leg Cargo", brand: "Valentino" }, { item: "Platform Sneaker", brand: "Valentino" }] },
      { name: "Fashion Week Front Row", pieces: [{ item: "Statement Fur Coat", brand: "Burberry" }, { item: "Leather Trouser", brand: "Valentino" }, { item: "Chrome Hearts Sunglasses", brand: "Chrome Hearts" }] },
      { name: "Monaco Pit", pieces: [{ item: "Custom F1 Race Suit", brand: "Mercedes-AMG Petronas" }, { item: "Chrome Hearts Helmet Wrap", brand: "Chrome Hearts" }, { item: "Racing Boot", brand: "Puma" }] },
      { name: "Valentino Red", pieces: [{ item: "Red Suit", brand: "Valentino" }, { item: "Black Poloneck", brand: "Valentino" }, { item: "Garavani Sneaker", brand: "Valentino" }] },
      { name: "Tokyo Fashion", pieces: [{ item: "Patchwork Jacket", brand: "NIGO x LV" }, { item: "Wide Trouser", brand: "Sacai" }, { item: "High-Top Sneaker", brand: "Nike x Sacai" }] },
      { name: "F1 Media Day", pieces: [{ item: "Gold Embroidered Jacket", brand: "Tom Ford" }, { item: "Black Trouser", brand: "Tom Ford" }, { item: "Chelsea Boot", brand: "Tom Ford" }] },
      { name: "Hollywood Hills", pieces: [{ item: "Relaxed Blazer", brand: "Saint Laurent" }, { item: "White Shirt", brand: "Sunspel" }, { item: "Loafer", brand: "Berluti" }] },
      { name: "Burberry Campaign", pieces: [{ item: "Heritage Trench", brand: "Burberry" }, { item: "Slim Denim", brand: "Acne Studios" }, { item: "Chelsea Boot", brand: "Burberry" }] },
      { name: "Grammy Scene", pieces: [{ item: "Metallic Silver Suit", brand: "Valentino" }, { item: "Black Turtleneck", brand: "Prada" }, { item: "Platform Shoe", brand: "Valentino" }] },
      { name: "London Season", pieces: [{ item: "Tailored Overcoat", brand: "Alexander McQueen" }, { item: "Roll-Neck Knit", brand: "Raf Simons" }, { item: "Oxford", brand: "Berluti" }] },
      { name: "Spa Weekend", pieces: [{ item: "Cashmere Jogger", brand: "Loro Piana" }, { item: "Logo Tee", brand: "Chrome Hearts" }, { item: "Runner", brand: "New Balance" }] },
      { name: "Victory Podium", pieces: [{ item: "Custom Team Jacket", brand: "Mercedes Custom" }, { item: "Champion Shorts", brand: "Mercedes Custom" }, { item: "Race Boot", brand: "Puma" }] },
    ],
  },
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    title: "The NBA's Most Original Dresser",
    style: "Unique NBA Editorial",
    description: "SGA doesn't follow trends — he sets them. Quiet luxury, unique Japanese brands, odd-ratio silhouettes, and editorial styling that belongs in a magazine, not just a locker room.",
    image: PHOTOS.sga,
    accentColor: "#8E9EAB",
    era: "2020–Present",
    knownFor: "Arena tunnel fits, editorial styling, quiet luxury NBA",
    signatureBrands: ["The Row", "Toteme", "Comme des Garçons", "Yohji Yamamoto", "New Balance"],
    keyPieces: ["Oversized trench coat", "Relaxed wide-leg trousers", "Plain white tee", "Minimalist sneaker", "Stack of rings"],
    vibes: ["Quiet Luxury", "NBA Tunnel", "Editorial Minimal"],
    looks: [
      { name: "Tunnel Walk", pieces: [{ item: "Oversized Trench", brand: "The Row" }, { item: "Wide-Leg Trouser", brand: "Toteme" }, { item: "Minimalist Sneaker", brand: "New Balance" }] },
      { name: "OKC Quiet", pieces: [{ item: "CDG Knit Polo", brand: "Comme des Garçons" }, { item: "Relaxed Trouser", brand: "Yohji Yamamoto" }, { item: "Simple Loafer", brand: "Lemaire" }] },
      { name: "Pre-Game Quiet", pieces: [{ item: "Oversized Knit Coat", brand: "Comme des Garçons" }, { item: "Wide Linen Trouser", brand: "Lemaire" }, { item: "Derby Shoe", brand: "Common Projects" }] },
      { name: "Media Day", pieces: [{ item: "Structured Blazer", brand: "The Row" }, { item: "Black Turtleneck", brand: "The Row" }, { item: "Chelsea Boot", brand: "The Row" }] },
      { name: "Japanese Edit", pieces: [{ item: "Deconstructed Suit", brand: "Yohji Yamamoto" }, { item: "Asymmetric Shirt", brand: "Issey Miyake" }, { item: "Clean Sneaker", brand: "New Balance" }] },
      { name: "OKC Royalty", pieces: [{ item: "Thunder-Blue Suit", brand: "Brioni Custom" }, { item: "White Dress Shirt", brand: "Charvet" }, { item: "Oxford", brand: "Berluti" }] },
      { name: "Off-Day Chill", pieces: [{ item: "Relaxed Linen Set", brand: "Lemaire" }, { item: "Simple Tee", brand: "Sunspel" }, { item: "Minimalist Sneaker", brand: "Veja" }] },
      { name: "All-Star Weekend", pieces: [{ item: "Velvet Blazer", brand: "Loro Piana" }, { item: "Slim Trouser", brand: "Toteme" }, { item: "Platform Loafer", brand: "Marni" }] },
      { name: "Travel Day", pieces: [{ item: "Camel Cashmere Overcoat", brand: "The Row" }, { item: "Wide Cropped Trouser", brand: "Toteme" }, { item: "Sock Boot", brand: "Common Projects" }] },
      { name: "Archive Dig", pieces: [{ item: "Vintage Cargo Trouser", brand: "Helmut Lang Archive" }, { item: "Graphic Tee", brand: "Comme des Garçons" }, { item: "Archive Sneaker", brand: "New Balance" }] },
      { name: "Silent Statement", pieces: [{ item: "All-White Linen Suit", brand: "The Row" }, { item: "White Sneaker", brand: "Common Projects" }, { item: "Minimal Ring Stack", brand: "Tom Wood" }] },
      { name: "Tunnel Vision", pieces: [{ item: "Asymmetric Coat", brand: "Issey Miyake Pleats" }, { item: "Wide Trouser", brand: "Yohji Yamamoto" }, { item: "Avant-Garde Sneaker", brand: "Salehe x New Balance" }] },
    ],
  },
  {
    id: "nas",
    name: "Nas",
    title: "Queens Bridge's Eternal Style King",
    style: "Classic New York",
    description: "Nas dressed like money before money talked the way it does now. Timeless NY — Timberlands, leather bubble coats, and just enough gold. He proved that classic never ages.",
    image: PHOTOS.nas,
    accentColor: "#B8A888",
    era: "1994–Present",
    knownFor: "Timberlands, classic NY hip-hop, bubble coat era",
    signatureBrands: ["Timberland", "Phat Farm", "Ralph Lauren", "Hermès", "Tom Ford"],
    keyPieces: ["Timberland boot", "Bubble goose coat", "Gold chains", "Fitted baseball cap", "Luxury watch"],
    vibes: ["NY Classic", "Old School Hip-hop", "Quiet Luxury"],
    looks: [
      { name: "Illmatic Era", pieces: [{ item: "Bubble Goose Coat", brand: "Northface" }, { item: "Timberland 6-Inch Boot", brand: "Timberland" }, { item: "Fitted Cap", brand: "New Era" }] },
      { name: "Kings Disease", pieces: [{ item: "Tom Ford Suit", brand: "Tom Ford" }, { item: "Hermès Belt", brand: "Hermès" }, { item: "Oxford Boot", brand: "Berluti" }] },
      { name: "QB Finest", pieces: [{ item: "Coogi Sweater", brand: "Coogi" }, { item: "Dark Denim", brand: "Polo Jeans" }, { item: "Air Jordan 3", brand: "Nike" }] },
      { name: "It Was Written", pieces: [{ item: "Leather Jacket", brand: "Custom" }, { item: "Gold Rope Chain", brand: "Jacob & Co" }, { item: "Timberland Boot", brand: "Timberland" }] },
      { name: "Street's Disciple", pieces: [{ item: "Linen Suit", brand: "Custom" }, { item: "Cuban Link Chain", brand: "Jacob & Co" }, { item: "Gucci Loafer", brand: "Gucci" }] },
      { name: "Nas x Harvard", pieces: [{ item: "Navy Blazer", brand: "Ralph Lauren" }, { item: "Oxford Shirt", brand: "Polo Ralph Lauren" }, { item: "Oxford Brogue", brand: "Allen Edmonds" }] },
      { name: "Stillmatic Season", pieces: [{ item: "Sheepskin Coat", brand: "Custom" }, { item: "Ski Goggles", brand: "Oakley" }, { item: "Timberland Boot", brand: "Timberland" }] },
      { name: "NY State of Mind", pieces: [{ item: "Polo Down Jacket", brand: "Ralph Lauren" }, { item: "Fitted Cap", brand: "New Era" }, { item: "Air Force 1", brand: "Nike" }] },
      { name: "Queens King", pieces: [{ item: "Zegna Suit", brand: "Zegna" }, { item: "Hermès Tie", brand: "Hermès" }, { item: "Patent Loafer", brand: "Gucci" }] },
      { name: "Life Is Good", pieces: [{ item: "Camp Collar Shirt", brand: "Loro Piana" }, { item: "Linen Trouser", brand: "Loro Piana" }, { item: "Canvas Sneaker", brand: "Rivieras" }] },
      { name: "Bourbon & Verse", pieces: [{ item: "Cashmere Turtleneck", brand: "Brunello Cucinelli" }, { item: "Slim Dark Trouser", brand: "Tom Ford" }, { item: "Chelsea Boot", brand: "Gucci" }] },
      { name: "Vintage Nas", pieces: [{ item: "Starter Jacket", brand: "Starter" }, { item: "Classic Denim", brand: "Levi's 501" }, { item: "Air Max 95", brand: "Nike" }] },
    ],
  },
];
