/**
 * Maison Simon — Verified Catalog Extras
 *
 * Hand-curated items with REAL product images and DIRECT product-detail-page
 * (PDP) URLs verified via web search on May 20, 2026. When a piece in a
 * generated look comes from this list, the look-detail screen shows the
 * actual brand/retailer photo and "Buy" links straight to the exact SKU.
 *
 * Spans the price spectrum (SHEIN/Fashion Nova → Zara/Nordstrom → Nike/Adidas
 * → Allen Edmonds/Cole Haan/Timberland/Dr Martens → Loro Piana/LV/Balmain/
 * Chrome Hearts) and the four shoe sub-types (sneakers, dress, casual, work).
 *
 * NOTE: This is the first verified batch (~16 items). The remaining catalog
 * gets enriched in subsequent passes.
 */

import type { CatalogItem } from "./outfitEngine";

export const CATALOG_EXTRAS: CatalogItem[] = [
  // ── SNEAKERS ──────────────────────────────────────────────────────────────
  {
    id: "ce_snk_001",
    name: "Air Force 1 '07",
    brand: "Nike",
    price: 115,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Y2K Revival", "Clean Minimal"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["White"],
    imageUrl: "https://media.gq.com/photos/678546f2ca86bd3f28b19c3d/master/w_1600,c_limit/Nike-Air-Force-1-Low-Travis-Scott-Sail-Product.jpg",
    purchaseUrl: "https://www.nike.com/t/air-force-1-07-mens-shoes-jBrhbr",
    productImageUrl: "https://media.gq.com/photos/678546f2ca86bd3f28b19c3d/master/w_1600,c_limit/Nike-Air-Force-1-Low-Travis-Scott-Sail-Product.jpg",
    directProductUrl: "https://www.nike.com/t/air-force-1-07-mens-shoes-jBrhbr",
  },
  {
    id: "ce_snk_002",
    name: "Samba OG",
    brand: "Adidas",
    price: 100,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Clean Minimal", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Black", "White"],
    imageUrl: "https://classic.cdn.media.amplience.net/i/hibbett/A2542_9127_main7/adidas%20Originals%20Samba%20OG%20%22Cream%20White/Core%20Black/Sand%20Strata%22%20Women's%20Shoe-9127?$medium$&fmt=webp",
    purchaseUrl: "https://www.adidas.com/us/samba-og-shoes/IE5836.html",
    productImageUrl: "https://classic.cdn.media.amplience.net/i/hibbett/A2542_9127_main7/adidas%20Originals%20Samba%20OG%20%22Cream%20White/Core%20Black/Sand%20Strata%22%20Women's%20Shoe-9127?$medium$&fmt=webp",
    directProductUrl: "https://www.adidas.com/us/samba-og-shoes/IE5836.html",
  },
  {
    id: "ce_snk_003",
    name: "Original Achilles Low Leather Sneaker",
    brand: "Common Projects",
    price: 441,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Clean Minimal", "Luxury Streetwear", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night"],
    genders: ["men", "women", "unisex"],
    colors: ["White"],
    imageUrl: "https://www.sneakinpeace.com/cdn/shop/files/common-projects-original-achilles-white-low-top-sneakers-trainers-2_440x570.jpg?v=1702983601",
    purchaseUrl: "https://www.mrporter.com/en-us/mens/product/common-projects/shoes/low-top-sneakers/original-achilles-leather-sneakers/3024088872901549",
    productImageUrl: "https://www.sneakinpeace.com/cdn/shop/files/common-projects-original-achilles-white-low-top-sneakers-trainers-2_440x570.jpg?v=1702983601",
    directProductUrl: "https://www.mrporter.com/en-us/mens/product/common-projects/shoes/low-top-sneakers/original-achilles-leather-sneakers/3024088872901549",
  },
  {
    id: "ce_snk_004",
    name: "Made in USA 990v6",
    brand: "New Balance",
    price: 200,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Clean Minimal", "Luxury Streetwear", "Techwear"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Grey"],
    imageUrl: "https://www.solestop.com/cdn/shop/files/new-balance-990v6-made-in-usa-grey-men-core-m990gl6-935.jpg?v=1773869326",
    purchaseUrl: "https://www.newbalance.com/pd/made-in-usa-990v6/M990V6-43094-PMG-NA.html",
    productImageUrl: "https://www.solestop.com/cdn/shop/files/new-balance-990v6-made-in-usa-grey-men-core-m990gl6-935.jpg?v=1773869326",
    directProductUrl: "https://www.newbalance.com/pd/made-in-usa-990v6/M990V6-43094-PMG-NA.html",
  },

  // ── DRESS SHOES ───────────────────────────────────────────────────────────
  {
    id: "ce_drs_001",
    name: "Park Avenue Cap-Toe Oxford",
    brand: "Allen Edmonds",
    price: 445,
    category: "shoes",
    shoeType: "dress",
    styles: ["Business", "Old Money", "Evening", "Formal"],
    occasions: ["Work", "Event", "Formal", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://oconnellsclothing.com/media/catalog/product/cache/8814f70c5bc0b565f99c4556e8177d36/rdi/rdi/allen-edmonds-park-avenue-cap-toe-lace-up-oxford-dress-shoe-black-custom-calfskin-with-v-treads-style-5616-5616-65-park-ave-v-tread_1.jpg",
    purchaseUrl: "https://www.allenedmonds.com/product/mens-park-avenue-cap-toe-oxford-dress-shoe-3023014",
    productImageUrl: "https://oconnellsclothing.com/media/catalog/product/cache/8814f70c5bc0b565f99c4556e8177d36/rdi/rdi/allen-edmonds-park-avenue-cap-toe-lace-up-oxford-dress-shoe-black-custom-calfskin-with-v-treads-style-5616-5616-65-park-ave-v-tread_1.jpg",
    directProductUrl: "https://www.allenedmonds.com/product/mens-park-avenue-cap-toe-oxford-dress-shoe-3023014",
  },
  {
    id: "ce_drs_002",
    name: "Pinch Penny Loafer",
    brand: "Cole Haan",
    price: 200,
    category: "shoes",
    shoeType: "dress",
    styles: ["Old Money", "Business", "Clean Minimal"],
    occasions: ["Work", "Casual", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://dolcevitafashions.com/cdn/shop/files/IMG_0173.jpg?v=1717709367",
    purchaseUrl: "https://www.colehaan.com/mens-pinch-penny-loafer/3503.html",
    productImageUrl: "https://dolcevitafashions.com/cdn/shop/files/IMG_0173.jpg?v=1717709367",
    directProductUrl: "https://www.colehaan.com/mens-pinch-penny-loafer/3503.html",
  },
  {
    id: "ce_drs_003",
    name: "Summer Walk Loafer",
    brand: "Loro Piana",
    price: 1075,
    category: "shoes",
    shoeType: "dress",
    styles: ["Old Money", "Clean Minimal", "Vacation Luxe"],
    occasions: ["Casual", "Work", "Vacation", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m89414653457_1.jpg?width=2560&quality=75&_=1774428244",
    purchaseUrl: "https://us.loropiana.com/en/shoes/man/white-sole/summer-walk-loafer-FAE8124_8000.html",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m89414653457_1.jpg?width=2560&quality=75&_=1774428244",
    directProductUrl: "https://us.loropiana.com/en/shoes/man/white-sole/summer-walk-loafer-FAE8124_8000.html",
  },

  // ── CASUAL / WORK BOOTS ───────────────────────────────────────────────────
  {
    id: "ce_wrk_001",
    name: "Premium 6-Inch Waterproof Boot",
    brand: "Timberland",
    price: 228,
    category: "shoes",
    shoeType: "work",
    styles: ["Luxury Streetwear", "Techwear", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Wheat", "Tan"],
    imageUrl: "https://i5.walmartimages.com/seo/Timberland-Men-s-Classic-Nubuck-6-inch-Premium-Waterproof-Boots-Wheat-Size-11-5_6fd136a6-7554-4519-91fb-d08a7c266bb6.91586c165ebc48c6cfbbcaecea325863.jpeg",
    purchaseUrl: "https://www.timberland.com/en-us/p/men/footwear-10039/mens-timberland-premium-6-inch-waterproof-boot-TB110061713",
    productImageUrl: "https://i5.walmartimages.com/seo/Timberland-Men-s-Classic-Nubuck-6-inch-Premium-Waterproof-Boots-Wheat-Size-11-5_6fd136a6-7554-4519-91fb-d08a7c266bb6.91586c165ebc48c6cfbbcaecea325863.jpeg",
    directProductUrl: "https://www.timberland.com/en-us/p/men/footwear-10039/mens-timberland-premium-6-inch-waterproof-boot-TB110061713",
  },
  {
    id: "ce_csl_001",
    name: "1460 Smooth Leather Lace-Up Boot",
    brand: "Dr. Martens",
    price: 170,
    category: "shoes",
    shoeType: "casual",
    styles: ["Luxury Streetwear", "Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/vZgAAeSwwplp~Pvy/s-l400.webp",
    purchaseUrl: "https://www.drmartens.com/us/en/1460-smooth-leather-lace-up-boots-black/p/11822006",
    productImageUrl: "https://i.ebayimg.com/images/g/vZgAAeSwwplp~Pvy/s-l400.webp",
    directProductUrl: "https://www.drmartens.com/us/en/1460-smooth-leather-lace-up-boots-black/p/11822006",
  },

  // ── LUXURY: TOPS / ACCESSORIES ────────────────────────────────────────────
  {
    id: "ce_lux_001",
    name: "LV Initiales 40mm Reversible Monogram Belt",
    brand: "Louis Vuitton",
    price: 560,
    category: "accessories",
    styles: ["Luxury Streetwear", "Clean Minimal", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night", "Event"],
    genders: ["men"],
    colors: ["Brown", "Black"],
    imageUrl: "https://www.luxecollectivefashion.com/cdn/shop/files/CDG87717_09_912x.jpg?v=1767031565",
    purchaseUrl: "https://us.louisvuitton.com/eng-us/products/lv-initiales-40mm-reversible-monogram-eclipse-014685/M9043U",
    productImageUrl: "https://www.luxecollectivefashion.com/cdn/shop/files/CDG87717_09_912x.jpg?v=1767031565",
    directProductUrl: "https://us.louisvuitton.com/eng-us/products/lv-initiales-40mm-reversible-monogram-eclipse-014685/M9043U",
  },
  {
    id: "ce_lux_002",
    name: "Vintage Gel Logo T-Shirt",
    brand: "Balmain",
    price: 450,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival", "Evening"],
    occasions: ["Casual", "Streetwear", "Party", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://thedesignerboxuk.com/cdn/shop/files/balmain-flocked-logo-t-shirt-p49962-107123_image_1400x.jpg?v=1684398670",
    purchaseUrl: "https://us.balmain.com/en/p/t-shirt-with-vintage-gel-balmain-logo-FH1EF000GD84EAC.html",
    productImageUrl: "https://thedesignerboxuk.com/cdn/shop/files/balmain-flocked-logo-t-shirt-p49962-107123_image_1400x.jpg?v=1684398670",
    directProductUrl: "https://us.balmain.com/en/p/t-shirt-with-vintage-gel-balmain-logo-FH1EF000GD84EAC.html",
  },
  {
    id: "ce_lux_003",
    name: "Horseshoe Logo Pocket T-Shirt",
    brand: "Chrome Hearts",
    price: 725,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Party"],
    genders: ["men", "women", "unisex"],
    colors: ["Black", "White"],
    imageUrl: "https://ablaj.com/cdn/shop/files/885682_01_jpg_2048x2048.webp?v=1720323320",
    purchaseUrl: "https://stockx.com/chrome-hearts-horse-shoe-logo-pocket-t-shirt-black",
    productImageUrl: "https://ablaj.com/cdn/shop/files/885682_01_jpg_2048x2048.webp?v=1720323320",
    directProductUrl: "https://stockx.com/chrome-hearts-horse-shoe-logo-pocket-t-shirt-black",
  },

  // ── FAST FASHION / DEPARTMENT ─────────────────────────────────────────────
  {
    id: "ce_low_001",
    name: "Manfinity EMRG Letter Graphic Oversized Tee",
    brand: "SHEIN",
    price: 12,
    category: "top",
    styles: ["Luxury Streetwear", "Casual", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "unisex"],
    colors: ["White", "Black"],
    imageUrl: "https://i.pinimg.com/originals/f1/e5/6d/f1e56d66f92acd782fa471667d98781e.jpg",
    purchaseUrl: "https://us.shein.com/Manfinity-EMRG-Men-Letter-Dragon-Graphic-Loosed-Tee-p-12635826.html?lang=us",
    productImageUrl: "https://i.pinimg.com/originals/f1/e5/6d/f1e56d66f92acd782fa471667d98781e.jpg",
    directProductUrl: "https://us.shein.com/Manfinity-EMRG-Men-Letter-Dragon-Graphic-Loosed-Tee-p-12635826.html?lang=us",
  },
  {
    id: "ce_low_002",
    name: "Slim Straight Distressed Jeans",
    brand: "Fashion Nova",
    price: 30,
    category: "bottom",
    styles: ["Luxury Streetwear", "Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear", "Date Night"],
    genders: ["men"],
    colors: ["Blue"],
    imageUrl: "https://i.ebayimg.com/images/g/HS0AAOSwoGli5cPE/s-l500.jpg",
    purchaseUrl: "https://www.fashionnova.com/collections/mens-slim-jeans",
    productImageUrl: "https://i.ebayimg.com/images/g/HS0AAOSwoGli5cPE/s-l500.jpg",
    directProductUrl: "https://www.fashionnova.com/collections/mens-slim-jeans",
  },
  {
    id: "ce_mid_001",
    name: "Relaxed Fit Poplin Shirt",
    brand: "Zara",
    price: 50,
    category: "top",
    styles: ["Clean Minimal", "Old Money", "Vacation Luxe", "Business"],
    occasions: ["Casual", "Work", "Date Night", "Vacation"],
    genders: ["men"],
    colors: ["White"],
    imageUrl: "https://i.ebayimg.com/images/g/n9sAAOSwB4JeojLC/s-l300.jpg",
    purchaseUrl: "https://www.zara.com/us/en/relaxed-fit-poplin-shirt-p05679742.html",
    productImageUrl: "https://i.ebayimg.com/images/g/n9sAAOSwB4JeojLC/s-l300.jpg",
    directProductUrl: "https://www.zara.com/us/en/relaxed-fit-poplin-shirt-p05679742.html",
  },
  {
    id: "ce_mid_002",
    name: "Treasure & Bond Henley T-Shirt",
    brand: "Nordstrom",
    price: 39,
    category: "top",
    styles: ["Clean Minimal", "Casual", "Old Money"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men"],
    colors: ["Grey", "Black", "White"],
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/09/04/68b97262731a0927898c74ff/s_68b97266f6035af8af7e3162.jpeg",
    purchaseUrl: "https://www.nordstrom.com/browse/men/clothing/shirts/tshirts/henley?filterByBrand=treasure-bond",
    productImageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/09/04/68b97262731a0927898c74ff/s_68b97266f6035af8af7e3162.jpeg",
    directProductUrl: "https://www.nordstrom.com/browse/men/clothing/shirts/tshirts/henley?filterByBrand=treasure-bond",
  },
];
