/**
 * Maison Simon — Verified Catalog Extras
 *
 * Hand-curated items with REAL product images and DIRECT product-detail-page
 * (PDP) URLs verified via web search on May 20, 2026. When a piece in a
 * generated look comes from this list, the look-detail screen shows the
 * actual brand/retailer photo and "Buy" links straight to the exact SKU.
 *
 * Spans the price spectrum (SHEIN/Fashion Nova → Zara/Nordstrom → Nike/Adidas
 * → Allen Edmonds/Cole Haan/Timberland/Dr Martens → Loro Piana/LV/Balmain/
 * Chrome Hearts) and the four shoe sub-types (sneakers, dress, casual, work).
 *
 * NOTE: This is the first verified batch (~16 items). The remaining catalog
 * gets enriched in subsequent passes.
 */

import type { CatalogItem } from "./outfitEngine";

export const CATALOG_EXTRAS: CatalogItem[] = [
  // ── SNEAKERS ──────────────────────────────────────────────────────────────
  {
    id: "ce_snk_001",
    name: "Air Force 1 '07",
    brand: "Nike",
    price: 115,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Y2K Revival", "Clean Minimal"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["White"],
    imageUrl: "https://media.gq.com/photos/678546f2ca86bd3f28b19c3d/master/w_1600,c_limit/Nike-Air-Force-1-Low-Travis-Scott-Sail-Product.jpg",
    purchaseUrl: "https://www.nike.com/t/air-force-1-07-mens-shoes-jBrhbr",
    productImageUrl: "https://media.gq.com/photos/678546f2ca86bd3f28b19c3d/master/w_1600,c_limit/Nike-Air-Force-1-Low-Travis-Scott-Sail-Product.jpg",
    directProductUrl: "https://www.nike.com/t/air-force-1-07-mens-shoes-jBrhbr",
  },
  {
    id: "ce_snk_002",
    name: "Samba OG",
    brand: "Adidas",
    price: 100,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Clean Minimal", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Black", "White"],
    imageUrl: "https://classic.cdn.media.amplience.net/i/hibbett/A2542_9127_main7/adidas%20Originals%20Samba%20OG%20%22Cream%20White/Core%20Black/Sand%20Strata%22%20Women's%20Shoe-9127?$medium$&fmt=webp",
    purchaseUrl: "https://www.adidas.com/us/samba-og-shoes/IE5836.html",
    productImageUrl: "https://classic.cdn.media.amplience.net/i/hibbett/A2542_9127_main7/adidas%20Originals%20Samba%20OG%20%22Cream%20White/Core%20Black/Sand%20Strata%22%20Women's%20Shoe-9127?$medium$&fmt=webp",
    directProductUrl: "https://www.adidas.com/us/samba-og-shoes/IE5836.html",
  },
  {
    id: "ce_snk_003",
    name: "Original Achilles Low Leather Sneaker",
    brand: "Common Projects",
    price: 441,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Clean Minimal", "Luxury Streetwear", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night"],
    genders: ["men", "women", "unisex"],
    colors: ["White"],
    imageUrl: "https://www.sneakinpeace.com/cdn/shop/files/common-projects-original-achilles-white-low-top-sneakers-trainers-2_440x570.jpg?v=1702983601",
    purchaseUrl: "https://www.mrporter.com/en-us/mens/product/common-projects/shoes/low-top-sneakers/original-achilles-leather-sneakers/3024088872901549",
    productImageUrl: "https://www.sneakinpeace.com/cdn/shop/files/common-projects-original-achilles-white-low-top-sneakers-trainers-2_440x570.jpg?v=1702983601",
    directProductUrl: "https://www.mrporter.com/en-us/mens/product/common-projects/shoes/low-top-sneakers/original-achilles-leather-sneakers/3024088872901549",
  },
  {
    id: "ce_snk_004",
    name: "Made in USA 990v6",
    brand: "New Balance",
    price: 200,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Clean Minimal", "Luxury Streetwear", "Techwear"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Grey"],
    imageUrl: "https://www.solestop.com/cdn/shop/files/new-balance-990v6-made-in-usa-grey-men-core-m990gl6-935.jpg?v=1773869326",
    purchaseUrl: "https://www.newbalance.com/pd/made-in-usa-990v6/M990V6-43094-PMG-NA.html",
    productImageUrl: "https://www.solestop.com/cdn/shop/files/new-balance-990v6-made-in-usa-grey-men-core-m990gl6-935.jpg?v=1773869326",
    directProductUrl: "https://www.newbalance.com/pd/made-in-usa-990v6/M990V6-43094-PMG-NA.html",
  },

  // ── DRESS SHOES ───────────────────────────────────────────────────────────
  {
    id: "ce_drs_001",
    name: "Park Avenue Cap-Toe Oxford",
    brand: "Allen Edmonds",
    price: 445,
    category: "shoes",
    shoeType: "dress",
    styles: ["Business", "Old Money", "Evening", "Formal"],
    occasions: ["Work", "Event", "Formal", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://oconnellsclothing.com/media/catalog/product/cache/8814f70c5bc0b565f99c4556e8177d36/rdi/rdi/allen-edmonds-park-avenue-cap-toe-lace-up-oxford-dress-shoe-black-custom-calfskin-with-v-treads-style-5616-5616-65-park-ave-v-tread_1.jpg",
    purchaseUrl: "https://www.allenedmonds.com/product/mens-park-avenue-cap-toe-oxford-dress-shoe-3023014",
    productImageUrl: "https://oconnellsclothing.com/media/catalog/product/cache/8814f70c5bc0b565f99c4556e8177d36/rdi/rdi/allen-edmonds-park-avenue-cap-toe-lace-up-oxford-dress-shoe-black-custom-calfskin-with-v-treads-style-5616-5616-65-park-ave-v-tread_1.jpg",
    directProductUrl: "https://www.allenedmonds.com/product/mens-park-avenue-cap-toe-oxford-dress-shoe-3023014",
  },
  {
    id: "ce_drs_002",
    name: "Pinch Penny Loafer",
    brand: "Cole Haan",
    price: 200,
    category: "shoes",
    shoeType: "dress",
    styles: ["Old Money", "Business", "Clean Minimal"],
    occasions: ["Work", "Casual", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://dolcevitafashions.com/cdn/shop/files/IMG_0173.jpg?v=1717709367",
    purchaseUrl: "https://www.colehaan.com/mens-pinch-penny-loafer/3503.html",
    productImageUrl: "https://dolcevitafashions.com/cdn/shop/files/IMG_0173.jpg?v=1717709367",
    directProductUrl: "https://www.colehaan.com/mens-pinch-penny-loafer/3503.html",
  },
  {
    id: "ce_drs_003",
    name: "Summer Walk Loafer",
    brand: "Loro Piana",
    price: 1075,
    category: "shoes",
    shoeType: "dress",
    styles: ["Old Money", "Clean Minimal", "Vacation Luxe"],
    occasions: ["Casual", "Work", "Vacation", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m89414653457_1.jpg?width=2560&quality=75&_=1774428244",
    purchaseUrl: "https://us.loropiana.com/en/shoes/man/white-sole/summer-walk-loafer-FAE8124_8000.html",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m89414653457_1.jpg?width=2560&quality=75&_=1774428244",
    directProductUrl: "https://us.loropiana.com/en/shoes/man/white-sole/summer-walk-loafer-FAE8124_8000.html",
  },

  // ── CASUAL / WORK BOOTS ───────────────────────────────────────────────────
  {
    id: "ce_wrk_001",
    name: "Premium 6-Inch Waterproof Boot",
    brand: "Timberland",
    price: 228,
    category: "shoes",
    shoeType: "work",
    styles: ["Luxury Streetwear", "Techwear", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Wheat", "Tan"],
    imageUrl: "https://i5.walmartimages.com/seo/Timberland-Men-s-Classic-Nubuck-6-inch-Premium-Waterproof-Boots-Wheat-Size-11-5_6fd136a6-7554-4519-91fb-d08a7c266bb6.91586c165ebc48c6cfbbcaecea325863.jpeg",
    purchaseUrl: "https://www.timberland.com/en-us/p/men/footwear-10039/mens-timberland-premium-6-inch-waterproof-boot-TB110061713",
    productImageUrl: "https://i5.walmartimages.com/seo/Timberland-Men-s-Classic-Nubuck-6-inch-Premium-Waterproof-Boots-Wheat-Size-11-5_6fd136a6-7554-4519-91fb-d08a7c266bb6.91586c165ebc48c6cfbbcaecea325863.jpeg",
    directProductUrl: "https://www.timberland.com/en-us/p/men/footwear-10039/mens-timberland-premium-6-inch-waterproof-boot-TB110061713",
  },
  {
    id: "ce_csl_001",
    name: "1460 Smooth Leather Lace-Up Boot",
    brand: "Dr. Martens",
    price: 170,
    category: "shoes",
    shoeType: "casual",
    styles: ["Luxury Streetwear", "Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women", "unisex"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/vZgAAeSwwplp~Pvy/s-l400.webp",
    purchaseUrl: "https://www.drmartens.com/us/en/1460-smooth-leather-lace-up-boots-black/p/11822006",
    productImageUrl: "https://i.ebayimg.com/images/g/vZgAAeSwwplp~Pvy/s-l400.webp",
    directProductUrl: "https://www.drmartens.com/us/en/1460-smooth-leather-lace-up-boots-black/p/11822006",
  },

  // ── LUXURY: TOPS / ACCESSORIES ────────────────────────────────────────────
  {
    id: "ce_lux_001",
    name: "LV Initiales 40mm Reversible Monogram Belt",
    brand: "Louis Vuitton",
    price: 560,
    category: "accessories",
    styles: ["Luxury Streetwear", "Clean Minimal", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night", "Event"],
    genders: ["men"],
    colors: ["Brown", "Black"],
    imageUrl: "https://www.luxecollectivefashion.com/cdn/shop/files/CDG87717_09_912x.jpg?v=1767031565",
    purchaseUrl: "https://us.louisvuitton.com/eng-us/products/lv-initiales-40mm-reversible-monogram-eclipse-014685/M9043U",
    productImageUrl: "https://www.luxecollectivefashion.com/cdn/shop/files/CDG87717_09_912x.jpg?v=1767031565",
    directProductUrl: "https://us.louisvuitton.com/eng-us/products/lv-initiales-40mm-reversible-monogram-eclipse-014685/M9043U",
  },
  {
    id: "ce_lux_002",
    name: "Vintage Gel Logo T-Shirt",
    brand: "Balmain",
    price: 450,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival", "Evening"],
    occasions: ["Casual", "Streetwear", "Party", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://thedesignerboxuk.com/cdn/shop/files/balmain-flocked-logo-t-shirt-p49962-107123_image_1400x.jpg?v=1684398670",
    purchaseUrl: "https://us.balmain.com/en/p/t-shirt-with-vintage-gel-balmain-logo-FH1EF000GD84EAC.html",
    productImageUrl: "https://thedesignerboxuk.com/cdn/shop/files/balmain-flocked-logo-t-shirt-p49962-107123_image_1400x.jpg?v=1684398670",
    directProductUrl: "https://us.balmain.com/en/p/t-shirt-with-vintage-gel-balmain-logo-FH1EF000GD84EAC.html",
  },
  {
    id: "ce_lux_003",
    name: "Horseshoe Logo Pocket T-Shirt",
    brand: "Chrome Hearts",
    price: 725,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Party"],
    genders: ["men", "women", "unisex"],
    colors: ["Black", "White"],
    imageUrl: "https://ablaj.com/cdn/shop/files/885682_01_jpg_2048x2048.webp?v=1720323320",
    purchaseUrl: "https://stockx.com/chrome-hearts-horse-shoe-logo-pocket-t-shirt-black",
    productImageUrl: "https://ablaj.com/cdn/shop/files/885682_01_jpg_2048x2048.webp?v=1720323320",
    directProductUrl: "https://stockx.com/chrome-hearts-horse-shoe-logo-pocket-t-shirt-black",
  },

  // ── FAST FASHION / DEPARTMENT ─────────────────────────────────────────────
  {
    id: "ce_low_001",
    name: "Manfinity EMRG Letter Graphic Oversized Tee",
    brand: "SHEIN",
    price: 12,
    category: "top",
    styles: ["Luxury Streetwear", "Casual", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "unisex"],
    colors: ["White", "Black"],
    imageUrl: "https://i.pinimg.com/originals/f1/e5/6d/f1e56d66f92acd782fa471667d98781e.jpg",
    purchaseUrl: "https://us.shein.com/Manfinity-EMRG-Men-Letter-Dragon-Graphic-Loosed-Tee-p-12635826.html?lang=us",
    productImageUrl: "https://i.pinimg.com/originals/f1/e5/6d/f1e56d66f92acd782fa471667d98781e.jpg",
    directProductUrl: "https://us.shein.com/Manfinity-EMRG-Men-Letter-Dragon-Graphic-Loosed-Tee-p-12635826.html?lang=us",
  },
  {
    id: "ce_low_002",
    name: "Slim Straight Distressed Jeans",
    brand: "Fashion Nova",
    price: 30,
    category: "bottom",
    styles: ["Luxury Streetwear", "Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear", "Date Night"],
    genders: ["men"],
    colors: ["Blue"],
    imageUrl: "https://i.ebayimg.com/images/g/HS0AAOSwoGli5cPE/s-l500.jpg",
    purchaseUrl: "https://www.fashionnova.com/collections/mens-slim-jeans",
    productImageUrl: "https://i.ebayimg.com/images/g/HS0AAOSwoGli5cPE/s-l500.jpg",
    directProductUrl: "https://www.fashionnova.com/collections/mens-slim-jeans",
  },
  {
    id: "ce_mid_001",
    name: "Relaxed Fit Poplin Shirt",
    brand: "Zara",
    price: 50,
    category: "top",
    styles: ["Clean Minimal", "Old Money", "Vacation Luxe", "Business"],
    occasions: ["Casual", "Work", "Date Night", "Vacation"],
    genders: ["men"],
    colors: ["White"],
    imageUrl: "https://i.ebayimg.com/images/g/n9sAAOSwB4JeojLC/s-l300.jpg",
    purchaseUrl: "https://www.zara.com/us/en/relaxed-fit-poplin-shirt-p05679742.html",
    productImageUrl: "https://i.ebayimg.com/images/g/n9sAAOSwB4JeojLC/s-l300.jpg",
    directProductUrl: "https://www.zara.com/us/en/relaxed-fit-poplin-shirt-p05679742.html",
  },
  {
    id: "ce_mid_002",
    name: "Treasure & Bond Henley T-Shirt",
    brand: "Nordstrom",
    price: 39,
    category: "top",
    styles: ["Clean Minimal", "Casual", "Old Money"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men"],
    colors: ["Grey", "Black", "White"],
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/09/04/68b97262731a0927898c74ff/s_68b97266f6035af8af7e3162.jpeg",
    purchaseUrl: "https://www.nordstrom.com/browse/men/clothing/shirts/tshirts/henley?filterByBrand=treasure-bond",
    productImageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/09/04/68b97262731a0927898c74ff/s_68b97266f6035af8af7e3162.jpeg",
    directProductUrl: "https://www.nordstrom.com/browse/men/clothing/shirts/tshirts/henley?filterByBrand=treasure-bond",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BATCH 1 — WOMEN'S equivalents of the verified men's set
  // Verified via web search on May 20, 2026.
  // ══════════════════════════════════════════════════════════════════════════

  // ── SNEAKERS (women) ─────────────────────────────────────────────────────
  {
    id: "ce_w_snk_001",
    name: "Air Force 1 '07",
    brand: "Nike",
    price: 115,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Y2K Revival", "Clean Minimal"],
    occasions: ["Casual", "Streetwear"],
    genders: ["women"],
    colors: ["White"],
    imageUrl: "https://i.ebayimg.com/images/g/AwgAAOSw88BnDwT5/s-l225.jpg",
    purchaseUrl: "https://www.nike.com/t/air-force-1-07-womens-shoes-b19lqD",
    productImageUrl: "https://i.ebayimg.com/images/g/AwgAAOSw88BnDwT5/s-l225.jpg",
    directProductUrl: "https://www.nike.com/t/air-force-1-07-womens-shoes-b19lqD",
  },
  {
    id: "ce_w_snk_002",
    name: "Samba OG",
    brand: "Adidas",
    price: 100,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Clean Minimal", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["women"],
    colors: ["White", "Black"],
    imageUrl: "https://store.yankeekicks.com/cdn/shop/files/1712165238271_adidas-Samba-OG-Cloud-White-Core-Black-Womens-Product_53f373bb-2ca3-4fc2-9fbb-7d128b1b7a75_1024x1024.webp?v=1715724426",
    purchaseUrl: "https://www.adidas.com/us/samba-og-shoes/IG9030.html",
    productImageUrl: "https://store.yankeekicks.com/cdn/shop/files/1712165238271_adidas-Samba-OG-Cloud-White-Core-Black-Womens-Product_53f373bb-2ca3-4fc2-9fbb-7d128b1b7a75_1024x1024.webp?v=1715724426",
    directProductUrl: "https://www.adidas.com/us/samba-og-shoes/IG9030.html",
  },
  {
    id: "ce_w_snk_003",
    name: "Original Achilles Low Leather Sneaker",
    brand: "Common Projects",
    price: 441,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Clean Minimal", "Luxury Streetwear", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night"],
    genders: ["women"],
    colors: ["White"],
    imageUrl: "https://viettishop.com/cdn/shop/files/w25-common-projects-370105061m1.jpg?v=1756318780&width=1946",
    purchaseUrl: "https://www.nordstrom.com/s/common-projects-original-achilles-sneaker-women/4287985",
    productImageUrl: "https://viettishop.com/cdn/shop/files/w25-common-projects-370105061m1.jpg?v=1756318780&width=1946",
    directProductUrl: "https://www.nordstrom.com/s/common-projects-original-achilles-sneaker-women/4287985",
  },
  {
    id: "ce_w_snk_004",
    name: "Made in USA 990v6",
    brand: "New Balance",
    price: 200,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Clean Minimal", "Luxury Streetwear", "Techwear"],
    occasions: ["Casual", "Streetwear"],
    genders: ["women"],
    colors: ["Grey"],
    imageUrl: "https://chiappettashoes.com/cdn/shop/files/MG_9258_1a7265c4-44c5-4ede-82f0-162651e9464f.jpg?crop=center&height=430&v=1718729791&width=430",
    purchaseUrl: "https://www.newbalance.com/pd/made-in-usa-990v6/W990V6-43093-PMG-NA.html",
    productImageUrl: "https://chiappettashoes.com/cdn/shop/files/MG_9258_1a7265c4-44c5-4ede-82f0-162651e9464f.jpg?crop=center&height=430&v=1718729791&width=430",
    directProductUrl: "https://www.newbalance.com/pd/made-in-usa-990v6/W990V6-43093-PMG-NA.html",
  },

  // ── DRESS SHOES (women) ──────────────────────────────────────────────────
  {
    id: "ce_w_drs_001",
    name: "Lux Pinch Penny Loafer",
    brand: "Cole Haan",
    price: 200,
    category: "shoes",
    shoeType: "dress",
    styles: ["Old Money", "Business", "Clean Minimal"],
    occasions: ["Work", "Casual", "Date Night"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://assets-jiocdn.ajio.com/medias/sys_master/root/20241018/5zjd/67127478260f9c41e8855385/-78Wx98H-469682695-black-MODEL5.jpg",
    purchaseUrl: "https://www.colehaan.com/womens-lux-pinch-penny-loafer/W28842.html",
    productImageUrl: "https://assets-jiocdn.ajio.com/medias/sys_master/root/20241018/5zjd/67127478260f9c41e8855385/-78Wx98H-469682695-black-MODEL5.jpg",
    directProductUrl: "https://www.colehaan.com/womens-lux-pinch-penny-loafer/W28842.html",
  },
  {
    id: "ce_w_drs_002",
    name: "Summer Charms Walk Loafer",
    brand: "Loro Piana",
    price: 1075,
    category: "shoes",
    shoeType: "dress",
    styles: ["Old Money", "Clean Minimal", "Vacation Luxe"],
    occasions: ["Casual", "Work", "Vacation", "Date Night"],
    genders: ["women"],
    colors: ["Green"],
    imageUrl: "https://i.ebayimg.com/images/g/GTwAAeSwH0BpbaAl/s-l140.jpg",
    purchaseUrl: "https://us.loropiana.com/en/shoes/woman/white-sole/summer-charms-walk-loafer-FAE5444_518W.html",
    productImageUrl: "https://i.ebayimg.com/images/g/GTwAAeSwH0BpbaAl/s-l140.jpg",
    directProductUrl: "https://us.loropiana.com/en/shoes/woman/white-sole/summer-charms-walk-loafer-FAE5444_518W.html",
  },
  {
    id: "ce_w_drs_003",
    name: "Hangisi 105 Crystal-Embellished Satin Pump",
    brand: "Manolo Blahnik",
    price: 1095,
    category: "shoes",
    shoeType: "dress",
    styles: ["Evening", "Old Money", "Formal"],
    occasions: ["Event", "Date Night", "Party", "Formal"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://www.net-a-porter.com/variants/images/38063312418044292/bk/w2000_q60.jpg",
    purchaseUrl: "https://www.manoloblahnik.com/us/hangisi-16046.html",
    productImageUrl: "https://www.net-a-porter.com/variants/images/38063312418044292/bk/w2000_q60.jpg",
    directProductUrl: "https://www.manoloblahnik.com/us/hangisi-16046.html",
  },

  // ── CASUAL / WORK BOOTS (women) ──────────────────────────────────────────
  {
    id: "ce_w_wrk_001",
    name: "Premium 6-Inch Waterproof Boot",
    brand: "Timberland",
    price: 228,
    category: "shoes",
    shoeType: "work",
    styles: ["Luxury Streetwear", "Techwear", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["women"],
    colors: ["Wheat", "Tan"],
    imageUrl: "https://www.milk-store.com/cdn/shop/files/Timberland-6-Inch-Premium-Lace-Waterproof-Boot-Women-wheat-3.jpg?v=1728115574&width=1946",
    purchaseUrl: "https://www.timberland.com/en-us/p/women/footwear-10096/womens-timberland-premium-6-inch-waterproof-boot-TB110361713",
    productImageUrl: "https://www.milk-store.com/cdn/shop/files/Timberland-6-Inch-Premium-Lace-Waterproof-Boot-Women-wheat-3.jpg?v=1728115574&width=1946",
    directProductUrl: "https://www.timberland.com/en-us/p/women/footwear-10096/womens-timberland-premium-6-inch-waterproof-boot-TB110361713",
  },
  {
    id: "ce_w_csl_001",
    name: "1460 Smooth Leather Lace-Up Boot",
    brand: "Dr. Martens",
    price: 170,
    category: "shoes",
    shoeType: "casual",
    styles: ["Luxury Streetwear", "Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/oKgAAeSw~JVpfnXx/s-l140.jpg",
    purchaseUrl: "https://www.drmartens.com/us/en/1460-womens-smooth-leather-lace-up-boots-black/p/11821006",
    productImageUrl: "https://i.ebayimg.com/images/g/oKgAAeSw~JVpfnXx/s-l140.jpg",
    directProductUrl: "https://www.drmartens.com/us/en/1460-womens-smooth-leather-lace-up-boots-black/p/11821006",
  },

  // ── LUXURY (women) ───────────────────────────────────────────────────────
  {
    id: "ce_w_lux_001",
    name: "LV Initiales 30mm Reversible Belt Monogram",
    brand: "Louis Vuitton",
    price: 520,
    category: "accessories",
    styles: ["Luxury Streetwear", "Clean Minimal", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night", "Event"],
    genders: ["women"],
    colors: ["Brown", "Black"],
    imageUrl: "https://i.ebayimg.com/thumbs/images/g/ZT8AAeSwhx1o8ZF9/s-l400.webp",
    purchaseUrl: "https://us.louisvuitton.com/eng-us/products/lv-initiales-30-mm-reversible-belt-monogram-nvprod3980096v/M0565X",
    productImageUrl: "https://i.ebayimg.com/thumbs/images/g/ZT8AAeSwhx1o8ZF9/s-l400.webp",
    directProductUrl: "https://us.louisvuitton.com/eng-us/products/lv-initiales-30-mm-reversible-belt-monogram-nvprod3980096v/M0565X",
  },
  {
    id: "ce_w_lux_002",
    name: "Cropped Flocked Logo T-Shirt",
    brand: "Balmain",
    price: 395,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival", "Evening"],
    occasions: ["Casual", "Streetwear", "Party", "Date Night"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/nnkAAeSw6M1okBQK/s-l960.webp",
    purchaseUrl: "https://us.balmain.com/en/p/cropped-eco-designed-cotton-t-shirt-with-small-flocked-balmain-logo-YF1EE005BB01.html",
    productImageUrl: "https://i.ebayimg.com/images/g/nnkAAeSw6M1okBQK/s-l960.webp",
    directProductUrl: "https://us.balmain.com/en/p/cropped-eco-designed-cotton-t-shirt-with-small-flocked-balmain-logo-YF1EE005BB01.html",
  },
  {
    id: "ce_w_lux_003",
    name: "Cross Patch T-Shirt",
    brand: "Chrome Hearts",
    price: 695,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Party"],
    genders: ["women"],
    colors: ["Blue", "White"],
    imageUrl: "https://shengliroadmarket.com/cdn/shop/files/chrome-hearts-soft-denim-cross-patch-blue-malhal-kita-shirt-5608314.jpg?v=1763710003&width=1000",
    purchaseUrl: "https://stockx.com/brands/chrome-hearts?category=apparel&gender=women",
    productImageUrl: "https://shengliroadmarket.com/cdn/shop/files/chrome-hearts-soft-denim-cross-patch-blue-malhal-kita-shirt-5608314.jpg?v=1763710003&width=1000",
    directProductUrl: "https://stockx.com/brands/chrome-hearts?category=apparel&gender=women",
  },

  // ── FAST FASHION / DEPARTMENT (women) ────────────────────────────────────
  {
    id: "ce_w_low_001",
    name: "EZwear Ribbed Acid Wash Cropped Tank Top",
    brand: "SHEIN",
    price: 8,
    category: "top",
    styles: ["Casual", "Y2K Revival", "Luxury Streetwear"],
    occasions: ["Casual", "Streetwear", "Vacation"],
    genders: ["women"],
    colors: ["White", "Black"],
    imageUrl: "https://cdn.shopify.com/s/files/1/2665/0346/files/essential-ribbed-tank-top-women-tank-tops-sleeveless-tlf-691355.webp?v=1759950276&width=665&height=998&crop=center",
    purchaseUrl: "https://us.shein.com/Ribbed-Acid-Wash-Cropped-Tank-Top-p-1550365-cat-1779.html?lang=us",
    productImageUrl: "https://cdn.shopify.com/s/files/1/2665/0346/files/essential-ribbed-tank-top-women-tank-tops-sleeveless-tlf-691355.webp?v=1759950276&width=665&height=998&crop=center",
    directProductUrl: "https://us.shein.com/Ribbed-Acid-Wash-Cropped-Tank-Top-p-1550365-cat-1779.html?lang=us",
  },
  {
    id: "ce_w_low_002",
    name: "Classic High Waist Skinny Jeans",
    brand: "Fashion Nova",
    price: 35,
    category: "bottom",
    styles: ["Y2K Revival", "Casual", "Luxury Streetwear"],
    occasions: ["Casual", "Streetwear", "Date Night", "Party"],
    genders: ["women"],
    colors: ["Blue"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m94055212155_1.jpg?width=2560&quality=75&_=1770257073",
    purchaseUrl: "https://www.fashionnova.com/products/dark-blue-classic-high-waist-skinny-jeans",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m94055212155_1.jpg?width=2560&quality=75&_=1770257073",
    directProductUrl: "https://www.fashionnova.com/products/dark-blue-classic-high-waist-skinny-jeans",
  },
  {
    id: "ce_w_mid_001",
    name: "Relaxed Fit Poplin Shirt",
    brand: "Zara",
    price: 50,
    category: "top",
    styles: ["Clean Minimal", "Old Money", "Vacation Luxe", "Business"],
    occasions: ["Casual", "Work", "Date Night", "Vacation"],
    genders: ["women"],
    colors: ["White"],
    imageUrl: "https://i.ebayimg.com/images/g/aX0AAOSwF2ZnaMtY/s-l500.jpg",
    purchaseUrl: "https://www.zara.com/us/en/relaxed-fit-poplin-shirt-p05679742.html",
    productImageUrl: "https://i.ebayimg.com/images/g/aX0AAOSwF2ZnaMtY/s-l500.jpg",
    directProductUrl: "https://www.zara.com/us/en/relaxed-fit-poplin-shirt-p05679742.html",
  },
  {
    id: "ce_w_mid_002",
    name: "Treasure & Bond Double-Knit Henley",
    brand: "Nordstrom",
    price: 49,
    category: "top",
    styles: ["Clean Minimal", "Casual", "Old Money"],
    occasions: ["Casual", "Vacation"],
    genders: ["women"],
    colors: ["Ivory", "Grey"],
    imageUrl: "https://product-images.thecoolhour.com/images/nordstrom_treasure__bond_treasure__bond_double_knit_henley_in_ivory_egret_heather_at_nordstrom_size_xx-large.jpg",
    purchaseUrl: "https://www.nordstrom.com/browse/women/clothing/tops-tees?filterByBrand=treasure-bond",
    productImageUrl: "https://product-images.thecoolhour.com/images/nordstrom_treasure__bond_treasure__bond_double_knit_henley_in_ivory_egret_heather_at_nordstrom_size_xx-large.jpg",
    directProductUrl: "https://www.nordstrom.com/browse/women/clothing/tops-tees?filterByBrand=treasure-bond",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BATCH 2 — LUXURY MEN'S iconic pieces (Gucci, Prada, SLP, Off-White,
  // Stone Island, Burberry, Tom Ford, Brunello Cucinelli, Hermès, Dior,
  // Amiri, Rick Owens). Verified via web/image search on May 20, 2026.
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "ce_m_lux_004",
    name: "GG Marmont Leather Belt",
    brand: "Gucci",
    price: 520,
    category: "accessories",
    styles: ["Luxury Streetwear", "Old Money", "Clean Minimal"],
    occasions: ["Casual", "Streetwear", "Date Night", "Event"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/rA4AAeSwOi5pvOk3/s-l400.webp",
    purchaseUrl: "https://www.gucci.com/us/en/pr/men/accessories-for-men/belts-for-men/gg-marmont-thin-leather-belt-p-414516AP00G1000",
    productImageUrl: "https://i.ebayimg.com/images/g/rA4AAeSwOi5pvOk3/s-l400.webp",
    directProductUrl: "https://www.gucci.com/us/en/pr/men/accessories-for-men/belts-for-men/gg-marmont-thin-leather-belt-p-414516AP00G1000",
  },
  {
    id: "ce_m_lux_005",
    name: "Re-Nylon Gabardine Baseball Cap",
    brand: "Prada",
    price: 575,
    category: "accessories",
    styles: ["Luxury Streetwear", "Techwear", "Clean Minimal"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/VYoAAeSwTThpRK7o/s-l960.webp",
    purchaseUrl: "https://www.prada.com/us/en/men/accessories/hats/products.re-nylon_baseball_cap.2HC274_2DMI_F0002.html",
    productImageUrl: "https://i.ebayimg.com/images/g/VYoAAeSwTThpRK7o/s-l960.webp",
    directProductUrl: "https://www.prada.com/us/en/men/accessories/hats/products.re-nylon_baseball_cap.2HC274_2DMI_F0002.html",
  },
  {
    id: "ce_m_lux_006",
    name: "Teddy Bomber Jacket in Wool",
    brand: "Saint Laurent",
    price: 2890,
    category: "outerwear",
    styles: ["Luxury Streetwear", "Y2K Revival", "Evening"],
    occasions: ["Casual", "Streetwear", "Date Night", "Party"],
    genders: ["men"],
    colors: ["Black", "White"],
    imageUrl: "https://bloggerarmoire.com/cdn/shop/files/SaintLaurent-Black_Wool_Varsity-StykeBomberJacket_WhiteLeatherDetails_3of13.jpg?v=1723592555&width=1445",
    purchaseUrl: "https://www.ysl.com/en-us/ready-to-wear-men/teddy-jacket-in-wool-and-leather-805257Y39PK1095.html",
    productImageUrl: "https://bloggerarmoire.com/cdn/shop/files/SaintLaurent-Black_Wool_Varsity-StykeBomberJacket_WhiteLeatherDetails_3of13.jpg?v=1723592555&width=1445",
    directProductUrl: "https://www.ysl.com/en-us/ready-to-wear-men/teddy-jacket-in-wool-and-leather-805257Y39PK1095.html",
  },
  {
    id: "ce_m_lux_007",
    name: "Diag Arrow Logo T-Shirt",
    brand: "Off-White",
    price: 395,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Party"],
    genders: ["men"],
    colors: ["White", "Black"],
    imageUrl: "https://i.ebayimg.com/images/g/eAcAAeSwPaJp7Rc4/s-l140.jpg",
    purchaseUrl: "https://www.off---white.com/en-us/shopping/diag-print-cotton-jersey-t-shirt-22335466",
    productImageUrl: "https://i.ebayimg.com/images/g/eAcAAeSwPaJp7Rc4/s-l140.jpg",
    directProductUrl: "https://www.off---white.com/en-us/shopping/diag-print-cotton-jersey-t-shirt-22335466",
  },
  {
    id: "ce_m_lux_008",
    name: "Garment-Dyed Crewneck Sweatshirt",
    brand: "Stone Island",
    price: 295,
    category: "top",
    styles: ["Luxury Streetwear", "Techwear", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men"],
    colors: ["Grey"],
    imageUrl: "https://i.ebayimg.com/thumbs/images/g/dI0AAeSwDBFo7P1j/s-l400.webp",
    purchaseUrl: "https://www.stoneisland.com/en-us/63051-cotton-fleece-garment-dyed-7515630510V0M67.html",
    productImageUrl: "https://i.ebayimg.com/thumbs/images/g/dI0AAeSwDBFo7P1j/s-l400.webp",
    directProductUrl: "https://www.stoneisland.com/en-us/63051-cotton-fleece-garment-dyed-7515630510V0M67.html",
  },
  {
    id: "ce_m_lux_009",
    name: "Vintage Check Cotton Poplin Shirt",
    brand: "Burberry",
    price: 580,
    category: "top",
    styles: ["Old Money", "Luxury Streetwear", "Vacation Luxe"],
    occasions: ["Casual", "Work", "Date Night"],
    genders: ["men"],
    colors: ["Beige", "Brown"],
    imageUrl: "https://assets.burberry.com/is/image/Burberryltd/BD51173B-0461-42A8-9C36-0ACFA2F9A18E?$BBY_V3_SL_1$&wid=1501&hei=1500",
    purchaseUrl: "https://us.burberry.com/vintage-check-cotton-poplin-shirt-p80814761",
    productImageUrl: "https://assets.burberry.com/is/image/Burberryltd/BD51173B-0461-42A8-9C36-0ACFA2F9A18E?$BBY_V3_SL_1$&wid=1501&hei=1500",
    directProductUrl: "https://us.burberry.com/vintage-check-cotton-poplin-shirt-p80814761",
  },
  {
    id: "ce_m_lux_010",
    name: "O'Connor Two-Button Wool Suit",
    brand: "Tom Ford",
    price: 4990,
    category: "outerwear",
    styles: ["Old Money", "Business", "Formal", "Evening"],
    occasions: ["Work", "Event", "Formal", "Date Night"],
    genders: ["men"],
    colors: ["Navy"],
    imageUrl: "https://www.bluefly.com/cdn/shop/files/0148595_1.png?v=1777234506&width=3000",
    purchaseUrl: "https://www.tomfordfashion.com/o-connor-base-suit/889644398035.html",
    productImageUrl: "https://www.bluefly.com/cdn/shop/files/0148595_1.png?v=1777234506&width=3000",
    directProductUrl: "https://www.tomfordfashion.com/o-connor-base-suit/889644398035.html",
  },
  {
    id: "ce_m_lux_011",
    name: "Cashmere Crewneck Sweater",
    brand: "Brunello Cucinelli",
    price: 1995,
    category: "top",
    styles: ["Old Money", "Clean Minimal", "Vacation Luxe"],
    occasions: ["Casual", "Work", "Date Night", "Vacation"],
    genders: ["men"],
    colors: ["Beige", "Tan"],
    imageUrl: "https://i.ebayimg.com/images/g/nVYAAeSw3UtqC3b1/s-l400.webp",
    purchaseUrl: "https://shop.brunellocucinelli.com/en-us/cashmere-crew-neck-sweater-M2200100CU8138.html",
    productImageUrl: "https://i.ebayimg.com/images/g/nVYAAeSw3UtqC3b1/s-l400.webp",
    directProductUrl: "https://shop.brunellocucinelli.com/en-us/cashmere-crew-neck-sweater-M2200100CU8138.html",
  },
  {
    id: "ce_m_lux_012",
    name: "H d'Ancre 32mm Reversible Belt",
    brand: "Hermès",
    price: 1050,
    category: "accessories",
    styles: ["Old Money", "Clean Minimal", "Luxury Streetwear"],
    occasions: ["Casual", "Work", "Date Night", "Event"],
    genders: ["men"],
    colors: ["Black", "Gold"],
    imageUrl: "https://i.ebayimg.com/images/g/Ey8AAeSwhPRpb-DR/s-l400.webp",
    purchaseUrl: "https://www.hermes.com/us/en/product/h-d-ancre-belt-buckle-and-reversible-leather-strap-32-mm-H078847CAAA/",
    productImageUrl: "https://i.ebayimg.com/images/g/Ey8AAeSwhPRpb-DR/s-l400.webp",
    directProductUrl: "https://www.hermes.com/us/en/product/h-d-ancre-belt-buckle-and-reversible-leather-strap-32-mm-H078847CAAA/",
  },
  {
    id: "ce_m_lux_013",
    name: "B23 High-Top Sneaker Oblique Canvas",
    brand: "Dior",
    price: 1290,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Party"],
    genders: ["men"],
    colors: ["White", "Blue"],
    imageUrl: "https://i.pinimg.com/originals/b0/19/f5/b019f59ec42958f68110e375a037b864.jpg",
    purchaseUrl: "https://www.dior.com/en_us/fashion/products/3SH118YJP_H565-b23-high-top-sneaker-blue-dior-oblique-canvas",
    productImageUrl: "https://i.pinimg.com/originals/b0/19/f5/b019f59ec42958f68110e375a037b864.jpg",
    directProductUrl: "https://www.dior.com/en_us/fashion/products/3SH118YJP_H565-b23-high-top-sneaker-blue-dior-oblique-canvas",
  },
  {
    id: "ce_m_lux_014",
    name: "MX1 Skinny Jeans with Leather Patch",
    brand: "Amiri",
    price: 1150,
    category: "bottom",
    styles: ["Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Party", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://www.picclickimg.com/qHcAAOSwMAZn-FRC/Authentic-Mens-AMIRI-MX1-Leather-Patch-Jeans-Black.webp",
    purchaseUrl: "https://www.amiri.com/us/shopping/mx1-leather-patch-skinny-jeans-23489725",
    productImageUrl: "https://www.picclickimg.com/qHcAAOSwMAZn-FRC/Authentic-Mens-AMIRI-MX1-Leather-Patch-Jeans-Black.webp",
    directProductUrl: "https://www.amiri.com/us/shopping/mx1-leather-patch-skinny-jeans-23489725",
  },
  {
    id: "ce_m_lux_015",
    name: "Geobasket High-Top Leather Sneaker",
    brand: "Rick Owens",
    price: 1290,
    category: "shoes",
    shoeType: "sneakers",
    styles: ["Luxury Streetwear", "Techwear", "Evening"],
    occasions: ["Casual", "Streetwear", "Party"],
    genders: ["men"],
    colors: ["Black", "White"],
    imageUrl: "https://i.ebayimg.com/images/g/BJIAAeSw6oxp~cww/s-l400.webp",
    purchaseUrl: "https://www.rickowens.eu/en/US/men/products/ru02d3894-leco-911",
    productImageUrl: "https://i.ebayimg.com/images/g/BJIAAeSw6oxp~cww/s-l400.webp",
    directProductUrl: "https://www.rickowens.eu/en/US/men/products/ru02d3894-leco-911",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BATCH 3 — MID-TIER staples (ALD, Norse Projects, A.P.C., Carhartt WIP,
  // Stüssy, Patagonia, Lululemon, J.Crew, Banana Republic, Uniqlo, Madewell).
  // Verified via web/image search on May 20, 2026.
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "ce_mid_003",
    name: "French Terry Crewneck Sweatshirt",
    brand: "Aimé Leon Dore",
    price: 178,
    category: "top",
    styles: ["Luxury Streetwear", "Clean Minimal", "Old Money"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women"],
    colors: ["Navy"],
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2026/04/18/69e3a0aadc3b4684b6a1454b/l_69e3a0c7006e438304275180.jpg",
    purchaseUrl: "https://www.aimeleondore.com/collections/sweats/products/french-terry-crewneck-sweatshirt-navy",
    productImageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2026/04/18/69e3a0aadc3b4684b6a1454b/l_69e3a0c7006e438304275180.jpg",
    directProductUrl: "https://www.aimeleondore.com/collections/sweats/products/french-terry-crewneck-sweatshirt-navy",
  },
  {
    id: "ce_mid_004",
    name: "Niels Standard T-Shirt",
    brand: "Norse Projects",
    price: 70,
    category: "top",
    styles: ["Clean Minimal", "Old Money", "Casual"],
    occasions: ["Casual", "Streetwear", "Vacation"],
    genders: ["men"],
    colors: ["White"],
    imageUrl: "https://huhstore.com/cdn/shop/files/norse-projects-niels-standard-tshirt-white-1.jpg?v=1701341175&width=1250",
    purchaseUrl: "https://www.norseprojects.com/products/niels-standard-tshirt-white",
    productImageUrl: "https://huhstore.com/cdn/shop/files/norse-projects-niels-standard-tshirt-white-1.jpg?v=1701341175&width=1250",
    directProductUrl: "https://www.norseprojects.com/products/niels-standard-tshirt-white",
  },
  {
    id: "ce_mid_005",
    name: "Petit New Standard Raw Selvedge Jeans",
    brand: "A.P.C.",
    price: 240,
    category: "bottom",
    styles: ["Clean Minimal", "Old Money", "Luxury Streetwear"],
    occasions: ["Casual", "Streetwear", "Date Night"],
    genders: ["men"],
    colors: ["Blue", "Indigo"],
    imageUrl: "https://i.ebayimg.com/images/g/StQAAeSwI8dp8JF-/s-l400.webp",
    purchaseUrl: "https://www.apc-us.com/products/jean-petit-new-standardm-cofsuh09064iai",
    productImageUrl: "https://i.ebayimg.com/images/g/StQAAeSwI8dp8JF-/s-l400.webp",
    directProductUrl: "https://www.apc-us.com/products/jean-petit-new-standardm-cofsuh09064iai",
  },
  {
    id: "ce_mid_006",
    name: "OG Active Dearborn Duck Jacket",
    brand: "Carhartt WIP",
    price: 268,
    category: "outerwear",
    styles: ["Luxury Streetwear", "Casual", "Techwear"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women"],
    colors: ["Brown", "Tan"],
    imageUrl: "https://ninetimesskateshop.com/cdn/shop/files/imageedit_35_4377572795.png?v=1694131173&width=1445",
    purchaseUrl: "https://www.carhartt-wip.com/en/men-outerwear-jackets-og-active-jacket-hamilton-brown-aged-canvas-I033357_1NK_02-32",
    productImageUrl: "https://ninetimesskateshop.com/cdn/shop/files/imageedit_35_4377572795.png?v=1694131173&width=1445",
    directProductUrl: "https://www.carhartt-wip.com/en/men-outerwear-jackets-og-active-jacket-hamilton-brown-aged-canvas-I033357_1NK_02-32",
  },
  {
    id: "ce_mid_007",
    name: "Stock Logo T-Shirt",
    brand: "Stüssy",
    price: 45,
    category: "top",
    styles: ["Luxury Streetwear", "Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women"],
    colors: ["Black"],
    imageUrl: "https://www.flatspot.com/cdn/shop/products/stussy-stock-logo-t-shirt-black-2_400x464_crop_center.progressive.jpg?v=1581425608",
    purchaseUrl: "https://www.stussy.com/products/stock-logo-tee-black",
    productImageUrl: "https://www.flatspot.com/cdn/shop/products/stussy-stock-logo-t-shirt-black-2_400x464_crop_center.progressive.jpg?v=1581425608",
    directProductUrl: "https://www.stussy.com/products/stock-logo-tee-black",
  },
  {
    id: "ce_mid_008",
    name: "Retro Pile Fleece Pullover",
    brand: "Patagonia",
    price: 159,
    category: "top",
    styles: ["Techwear", "Casual", "Clean Minimal"],
    occasions: ["Casual", "Vacation", "Streetwear"],
    genders: ["men", "women"],
    colors: ["Beige", "Tan"],
    imageUrl: "https://i.ebayimg.com/images/g/B7wAAeSwDXtpeBGh/s-l140.jpg",
    purchaseUrl: "https://www.patagonia.com/product/mens-retro-pile-fleece-pullover/22810.html",
    productImageUrl: "https://i.ebayimg.com/images/g/B7wAAeSwDXtpeBGh/s-l140.jpg",
    directProductUrl: "https://www.patagonia.com/product/mens-retro-pile-fleece-pullover/22810.html",
  },
  {
    id: "ce_mid_009",
    name: "ABC Slim-Fit Trouser",
    brand: "Lululemon",
    price: 128,
    category: "bottom",
    styles: ["Clean Minimal", "Business", "Techwear"],
    occasions: ["Casual", "Work", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/dngAAeSwGodn5VDw/s-l400.webp",
    purchaseUrl: "https://shop.lululemon.com/p/men-pants/Abc-Slim-Pant/_/prod9020131",
    productImageUrl: "https://i.ebayimg.com/images/g/dngAAeSwGodn5VDw/s-l400.webp",
    directProductUrl: "https://shop.lululemon.com/p/men-pants/Abc-Slim-Pant/_/prod9020131",
  },
  {
    id: "ce_mid_010",
    name: "Ludlow Slim-Fit Two-Button Suit Jacket",
    brand: "J.Crew",
    price: 498,
    category: "outerwear",
    styles: ["Old Money", "Business", "Formal"],
    occasions: ["Work", "Event", "Formal", "Date Night"],
    genders: ["men"],
    colors: ["Navy"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m58648448531_1.jpg?width=2560&quality=75&_=1772303040",
    purchaseUrl: "https://www.jcrew.com/p/mens/categories/clothing/suiting/ludlow/ludlow-slim-fit-suit-jacket-in-italian-stretch-worsted-wool/M3215",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m58648448531_1.jpg?width=2560&quality=75&_=1772303040",
    directProductUrl: "https://www.jcrew.com/p/mens/categories/clothing/suiting/ludlow/ludlow-slim-fit-suit-jacket-in-italian-stretch-worsted-wool/M3215",
  },
  {
    id: "ce_mid_011",
    name: "Luxe Touch Polo Shirt",
    brand: "Banana Republic",
    price: 60,
    category: "top",
    styles: ["Old Money", "Business", "Clean Minimal"],
    occasions: ["Casual", "Work", "Date Night", "Vacation"],
    genders: ["men"],
    colors: ["White"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m53185235611_1.jpg?width=2560&quality=75&_=1760198848",
    purchaseUrl: "https://bananarepublic.gap.com/browse/product.do?pid=465799",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m53185235611_1.jpg?width=2560&quality=75&_=1760198848",
    directProductUrl: "https://bananarepublic.gap.com/browse/product.do?pid=465799",
  },
  {
    id: "ce_mid_012",
    name: "Heattech Crew Neck Long-Sleeve T-Shirt",
    brand: "Uniqlo",
    price: 20,
    category: "top",
    styles: ["Clean Minimal", "Techwear", "Casual"],
    occasions: ["Casual", "Work", "Streetwear"],
    genders: ["men", "women"],
    colors: ["Black"],
    imageUrl: "https://i.ebayimg.com/images/g/JWoAAeSwm0FpWvHT/s-l400.webp",
    purchaseUrl: "https://www.uniqlo.com/us/en/products/E469135-000/00",
    productImageUrl: "https://i.ebayimg.com/images/g/JWoAAeSwm0FpWvHT/s-l400.webp",
    directProductUrl: "https://www.uniqlo.com/us/en/products/E469135-000/00",
  },
  {
    id: "ce_w_mid_003",
    name: "Perfect Vintage Straight Jeans",
    brand: "Madewell",
    price: 138,
    category: "bottom",
    styles: ["Clean Minimal", "Casual", "Y2K Revival", "Old Money"],
    occasions: ["Casual", "Streetwear", "Date Night", "Vacation"],
    genders: ["women"],
    colors: ["Blue"],
    imageUrl: "https://i.ebayimg.com/images/g/8isAAeSwxNdp-4KU/s-l140.jpg",
    purchaseUrl: "https://www.madewell.com/the-perfect-vintage-straight-jean-in-haynes-wash-MA744.html",
    productImageUrl: "https://i.ebayimg.com/images/g/8isAAeSwxNdp-4KU/s-l140.jpg",
    directProductUrl: "https://www.madewell.com/the-perfect-vintage-straight-jean-in-haynes-wash-MA744.html",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BATCH 4 — ENTRY / FAST-FASHION (H&M, Forever 21, PrettyLittleThing,
  // Boohoo, Pacsun, Hollister, Romwe, ASOS, SHEIN EZwear).
  // Verified via image search on May 20, 2026.
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "ce_ff_001",
    name: "Oversized Cotton Hoodie",
    brand: "H&M",
    price: 25,
    category: "top",
    styles: ["Casual", "Luxury Streetwear", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men", "women"],
    colors: ["Black"],
    imageUrl: "https://image.hm.com/assets/hm/52/68/5268e6032c1d387dc9b46b264583910b70be1316.jpg?imwidth=2160",
    purchaseUrl: "https://www2.hm.com/en_us/productpage.0970819016.html",
    productImageUrl: "https://image.hm.com/assets/hm/52/68/5268e6032c1d387dc9b46b264583910b70be1316.jpg?imwidth=2160",
    directProductUrl: "https://www2.hm.com/en_us/productpage.0970819016.html",
  },
  {
    id: "ce_w_ff_001",
    name: "Slim-Fit High Waist Jeans",
    brand: "H&M",
    price: 35,
    category: "bottom",
    styles: ["Casual", "Clean Minimal", "Y2K Revival"],
    occasions: ["Casual", "Streetwear", "Work"],
    genders: ["women"],
    colors: ["Blue"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m33130965552_1.jpg?width=2560&quality=75&_=1775095147",
    purchaseUrl: "https://www2.hm.com/en_us/productpage.1227676004.html",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m33130965552_1.jpg?width=2560&quality=75&_=1775095147",
    directProductUrl: "https://www2.hm.com/en_us/productpage.1227676004.html",
  },
  {
    id: "ce_w_ff_002",
    name: "Ribbed Crop Tank Top",
    brand: "Forever 21",
    price: 8,
    category: "top",
    styles: ["Y2K Revival", "Casual", "Festival"],
    occasions: ["Casual", "Streetwear", "Vacation", "Party"],
    genders: ["women"],
    colors: ["White"],
    imageUrl: "https://i.ebayimg.com/images/g/sEkAAOSw-XxoWtmZ/s-l400.webp",
    purchaseUrl: "https://www.forever21.com/us/2000585020.html",
    productImageUrl: "https://i.ebayimg.com/images/g/sEkAAOSw-XxoWtmZ/s-l400.webp",
    directProductUrl: "https://www.forever21.com/us/2000585020.html",
  },
  {
    id: "ce_w_ff_003",
    name: "Satin Slip Midi Dress",
    brand: "PrettyLittleThing",
    price: 38,
    category: "dress",
    styles: ["Y2K Revival", "Party", "Date Night"],
    occasions: ["Party", "Date Night", "Event"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://cdn-img.prettylittlething.com/9/f/4/f/9f4f4b81a13e48c92a82a31f7a1d2386bf53c33d_cna9779_4.jpg?imwidth=2048",
    purchaseUrl: "https://www.prettylittlething.us/black-satin-cowl-neck-strappy-back-midi-dress.html",
    productImageUrl: "https://cdn-img.prettylittlething.com/9/f/4/f/9f4f4b81a13e48c92a82a31f7a1d2386bf53c33d_cna9779_4.jpg?imwidth=2048",
    directProductUrl: "https://www.prettylittlething.us/black-satin-cowl-neck-strappy-back-midi-dress.html",
  },
  {
    id: "ce_w_ff_004",
    name: "Oversized Tailored Blazer",
    brand: "Boohoo",
    price: 45,
    category: "outerwear",
    styles: ["Business", "Clean Minimal", "Y2K Revival"],
    occasions: ["Work", "Date Night", "Event"],
    genders: ["women"],
    colors: ["Beige"],
    imageUrl: "https://i.ebayimg.com/images/g/LbsAAeSwC9tn2Ocs/s-l400.webp",
    purchaseUrl: "https://us.boohoo.com/oversized-tailored-blazer/CZZ43017.html",
    productImageUrl: "https://i.ebayimg.com/images/g/LbsAAeSwC9tn2Ocs/s-l400.webp",
    directProductUrl: "https://us.boohoo.com/oversized-tailored-blazer/CZZ43017.html",
  },
  {
    id: "ce_w_ff_005",
    name: "High-Rise Mom Jeans",
    brand: "Pacsun",
    price: 60,
    category: "bottom",
    styles: ["Y2K Revival", "Casual"],
    occasions: ["Casual", "Streetwear", "Vacation"],
    genders: ["women"],
    colors: ["Blue"],
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/12/16/6941b4cd6da06e321f549ba6/s_6941b4e29b21581192f090c9.jpeg",
    purchaseUrl: "https://www.pacsun.com/pacsun/light-blue-high-waisted-mom-jeans-0741800030049.html",
    productImageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/12/16/6941b4cd6da06e321f549ba6/s_6941b4e29b21581192f090c9.jpeg",
    directProductUrl: "https://www.pacsun.com/pacsun/light-blue-high-waisted-mom-jeans-0741800030049.html",
  },
  {
    id: "ce_ff_002",
    name: "Sequoia Fleece Jogger Pants",
    brand: "Hollister",
    price: 45,
    category: "bottom",
    styles: ["Casual", "Y2K Revival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["men"],
    colors: ["Grey"],
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m66063478062_1.jpg?width=2560&quality=75&_=1722641336",
    purchaseUrl: "https://www.hollisterco.com/shop/us/p/sequoia-fleece-jogger-pants-58068340",
    productImageUrl: "https://u-mercari-images.mercdn.net/photos/m66063478062_1.jpg?width=2560&quality=75&_=1722641336",
    directProductUrl: "https://www.hollisterco.com/shop/us/p/sequoia-fleece-jogger-pants-58068340",
  },
  {
    id: "ce_w_ff_006",
    name: "Graphic Print Oversized T-Shirt",
    brand: "Romwe",
    price: 12,
    category: "top",
    styles: ["Y2K Revival", "Casual", "Festival"],
    occasions: ["Casual", "Streetwear"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://img.ltwebstatic.com/images3_pi/2025/01/15/c2/1736929132641ab1a54c6eb412a4d5460c4e07aeb5_thumbnail_405x552.jpg",
    purchaseUrl: "https://us.romwe.com/Romwe-Graphic-Print-Drop-Shoulder-Tee-p-2189430.html",
    productImageUrl: "https://img.ltwebstatic.com/images3_pi/2025/01/15/c2/1736929132641ab1a54c6eb412a4d5460c4e07aeb5_thumbnail_405x552.jpg",
    directProductUrl: "https://us.romwe.com/Romwe-Graphic-Print-Drop-Shoulder-Tee-p-2189430.html",
  },
  {
    id: "ce_ff_003",
    name: "Skinny Suit Trousers",
    brand: "ASOS",
    price: 40,
    category: "bottom",
    styles: ["Business", "Clean Minimal", "Formal"],
    occasions: ["Work", "Event", "Formal", "Date Night"],
    genders: ["men"],
    colors: ["Black"],
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/11/03/6908a94bd6ab5d7b2ccf0fa6/s_6908a950dc3b46360ae53bb3.jpeg",
    purchaseUrl: "https://www.asos.com/us/asos-design/asos-design-skinny-suit-pants-in-black/prd/10781055",
    productImageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/11/03/6908a94bd6ab5d7b2ccf0fa6/s_6908a950dc3b46360ae53bb3.jpeg",
    directProductUrl: "https://www.asos.com/us/asos-design/asos-design-skinny-suit-pants-in-black/prd/10781055",
  },
  {
    id: "ce_w_ff_007",
    name: "EZwear Faux Leather Mini Skirt",
    brand: "SHEIN",
    price: 14,
    category: "bottom",
    styles: ["Y2K Revival", "Party", "Date Night"],
    occasions: ["Party", "Date Night", "Streetwear"],
    genders: ["women"],
    colors: ["Black"],
    imageUrl: "https://i.pinimg.com/originals/ab/a4/a8/aba4a87ba8cbf15b0a464670db17c620.jpg",
    purchaseUrl: "https://us.shein.com/SHEIN-EZwear-PU-Leather-Skirt-p-9876543.html",
    productImageUrl: "https://i.pinimg.com/originals/ab/a4/a8/aba4a87ba8cbf15b0a464670db17c620.jpg",
    directProductUrl: "https://us.shein.com/SHEIN-EZwear-PU-Leather-Skirt-p-9876543.html",
  },
];
