uploads = []
outputs = []

[[generated]]
id = "i9NsmC_TxX3EEQwdXYDvw"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "maison simon app icon"

[[generated]]
id = "oD_ZLMWEuae2rfoT4FjP7"
uri = "file://artifacts/mobile/assets/images/hero_banner.png"
type = "image"
title = "hero fashion banner"

[[generated]]
id = "FCIsvyUM2C3kMTycV6ffs"
uri = "file://artifacts/mobile/assets/images/look_old_money.png"
type = "image"
title = "old money look"

[[generated]]
id = "4gPh5W66uZKZ4XHn3I5qs"
uri = "file://artifacts/mobile/assets/images/look_streetwear.png"
type = "image"
title = "luxury streetwear look"

[[generated]]
id = "EwU77xRER14eNP4PKb2Ta"
uri = "file://artifacts/mobile/assets/images/look_vacation.png"
type = "image"
title = "vacation luxe look"

[[generated]]
id = "KNLQ-59kWg8UF1-PkWoPX"
uri = "file://artifacts/mobile/assets/images/look_techwear.png"
type = "image"
title = "techwear look"

[[generated]]
id = "365vYaOSlhwhRqrF30L62"
uri = "file://artifacts/mobile/assets/images/splash_bg.png"
type = "image"
title = "luxury splash background"

[[generated]]
id = "8yEuLesNzVy3wPA9WBLPF"
uri = "file://artifacts/mobile/assets/images/splash_hero.png"
type = "image"
title = "splash hero editorial"

[[generated]]
id = "JndDBqchrQ4xznoeJfuk2"
uri = "file://artifacts/mobile/assets/images/occasion_casual.png"
type = "image"
title = "casual occasion card"

[[generated]]
id = "z0Z4gQFnICYSxb0vNh9D0"
uri = "file://artifacts/mobile/assets/images/occasion_date.png"
type = "image"
title = "date night occasion card"

[[generated]]
id = "5-fQFVtRzwIZL0O-xTMfl"
uri = "file://artifacts/mobile/assets/images/occasion_work.png"
type = "image"
title = "work occasion card"

[[generated]]
id = "0vqqDuX591q6cbpxubaNJ"
uri = "file://artifacts/mobile/assets/images/occasion_vacation.png"
type = "image"
title = "vacation occasion card"

[[generated]]
id = "lH1UTpl_kgrlvOKqCc7oW"
uri = "file://artifacts/mobile/assets/images/occasion_event.png"
type = "image"
title = "event occasion card"

[[generated]]
id = "i9Il5QkYLbFp8C7V61pwF"
uri = "file://artifacts/mobile/assets/images/occasion_street.png"
type = "image"
title = "streetwear occasion card"

[[generated]]
id = "ozI7U3v0v8bivX9fHuc88"
uri = "file://artifacts/mobile/assets/images/streetwear_hero_men.png"
type = "image"
title = "streetwear hero men"
